In [1]:
import time
import MetaTrader5 as mt5
import sys

# display data on the MetaTrader 5 package
print("MetaTrader5 package author: ", mt5.__author__)
print("MetaTrader5 package version: ", mt5.__version__)

MetaTrader5 package author:  MetaQuotes Ltd.
MetaTrader5 package version:  5.0.5200

Ejemplo data por hora con mt5

In [2]:
mt5.symbols_get("*BTC*")

In [ ]:
import MetaTrader5 as mt5
import pandas as pd
from datetime import datetime

# Initialize MT5 connection
if not mt5.initialize():
    print("initialize() failed, error code =", mt5.last_error())
    quit()

# Define symbol and timeframe
symbol = "EURUSD"
timeframe = mt5.TIMEFRAME_H1 # Hourly timeframe

# Define the number of bars to retrieve or a specific date range
# Option 1: Get the last N bars
num_bars = 100
rates = mt5.copy_rates_from_pos(symbol, timeframe, 0, num_bars)

# Option 2: Get bars within a specific date range
# from_date = datetime(2024, 1, 1)
# to_date = datetime(2024, 1, 31)
# rates = mt5.copy_rates_range(symbol, timeframe, from_date, to_date)

# Check if data was retrieved successfully
if rates is None:
    print(f"Failed to get rates for {symbol}, error code =", mt5.last_error())
else:
    # Create a pandas DataFrame from the retrieved data
    rates_frame = pd.DataFrame(rates)
    # Convert time in seconds to datetime objects
    rates_frame['time'] = pd.to_datetime(rates_frame['time'], unit='s')
    # Set time as index
    rates_frame.set_index('time', inplace=True)

    # Print the OHLC data
    print(rates_frame[['open', 'high', 'low', 'close']])

# Shutdown MT5 connection
mt5.shutdown()

initialize() failed, error code = (-6, 'Terminal: Authorization failed')
Failed to get rates for EURUSD, error code = (-10004, 'No IPC connection')

True

:

In [12]:
# GENDATA
import MetaTrader5 as mt5
import pandas as pd

# Inicializar MT5
mt5.initialize()

#symbols = mt5.symbols_get("*BTC*")
#for s in symbols:
#    print(s.name)
    
# Nombre del símbolo (depende de tu broker, a veces es BTCUSD, BTCUSD.m, etc.)
symbol = "BTCUSD"

# Seleccionar símbolo
mt5.symbol_select(symbol, True)

# Descargar datos: 100 velas de 1 hora (TIMEFRAME_H1)
rates = mt5.copy_rates_from_pos(symbol, mt5.TIMEFRAME_H1, 0, 60000)

#print(rates)
# Convertir a DataFrame para trabajar cómodo
df = pd.DataFrame(rates)

df['time'] = pd.to_datetime(df['time'], unit='s')

display(df.tail())

# Cerrar MT5
mt5.shutdown()

,time,open,high,low,close,tick_volume,spread,real_volume
35885,2025-12-01 16:00:00,84673.43,85447.83,84023.74,84542.64,9265,1260,0
35886,2025-12-01 17:00:00,84544.23,85262.46,84432.61,84935.73,6280,1260,0
35887,2025-12-01 18:00:00,84938.83,85564.32,84701.52,85182.72,5649,1260,0
35888,2025-12-01 19:00:00,85185.38,85294.49,84590.68,85018.00,5651,1260,0
35889,2025-12-01 20:00:00,85013.93,85836.25,84994.14,85465.64,2810,1260,0

True

In [13]:
df.head()

,time,open,high,low,close,tick_volume,spread,real_volume
0,2021-10-27 16:00:00,58734.06,59042.92,58532.74,58856.56,1347,586,0
1,2021-10-27 17:00:00,58856.56,59166.83,58831.57,58942.47,2065,1402,0
2,2021-10-28 09:00:00,60431.05,61276.66,60360.70,61048.85,2631,3977,0
3,2021-10-28 10:00:00,61048.79,61231.67,60814.46,61042.45,4085,3349,0
4,2021-10-28 11:00:00,61041.32,61106.04,60732.14,60999.73,3942,681,0

In [8]:
import yfinance as yf

# Definir ticker y periodo
ticker = 'BTC-USD'  # ejemplo Apple
data = yf.download(ticker, start = '2024-01-01', interval='60m')  # intervalo de 60 minutos

data

C:\Users\mvaldiviad\AppData\Local\Temp\ipykernel_27176\1663591736.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  data = yf.download(ticker, start = '2024-01-01', interval='60m')  # intervalo de 60 minutos
[*********************100%***********************]  1 of 1 completed

Price,Close,High,Low,Open,Volume
Ticker,BTC-USD,BTC-USD,BTC-USD,BTC-USD,BTC-USD
Datetime,,,,,
2024-01-01 00:00:00+00:00,42477.253906,42517.601562,42277.726562,42280.234375,0
2024-01-01 01:00:00+00:00,42622.898438,42718.710938,42433.785156,42471.402344,200035328
2024-01-01 02:00:00+00:00,42576.601562,42611.335938,42506.359375,42611.335938,0
2024-01-01 03:00:00+00:00,42320.730469,42581.007812,42270.757812,42575.968750,118417408
2024-01-01 04:00:00+00:00,42387.164062,42387.164062,42227.984375,42325.042969,34720768
...,...,...,...,...,...
2025-09-24 14:00:00+00:00,113775.187500,113887.015625,112853.421875,112853.421875,784695296
2025-09-24 15:00:00+00:00,113425.500000,113908.062500,113337.796875,113755.726562,1738788864
2025-09-24 16:00:00+00:00,113755.843750,113775.875000,113225.695312,113368.562500,3422179328
2025-09-24 17:00:00+00:00,113806.867188,113981.898438,113678.539062,113773.851562,5904379904
2025-09-24 18:00:00+00:00,113664.546875,113852.554688,113597.125000,113797.835938,2033688576

# Parseo de string

In [2]:
def checkear_ordenes_pendientes(valor, tipo, precio):
    # Establish connection to MT5
    if not mt5.initialize():
        print("initialize() failed, error code =", mt5.last_error())
        quit()

    # Get all pending orders
    # Use mt5.orders_get() to retrieve all orders.
    # Filter for pending orders based on their type (e.g., mt5.ORDER_TYPE_BUY_LIMIT, mt5.ORDER_TYPE_SELL_STOP, etc.)
    # A more robust approach would be to check if the order is a pending order.
    pending_orders = mt5.orders_get()
    for orden in pending_orders:
        precio_open = orden.price_open
        tipo_orden = orden.type
        simbolo = orden.symbol
        if (simbolo == valor) and (tipo_orden == mt5.ORDER_TYPE_BUY_LIMIT) and (tipo == 'buy') and (precio_open == float(precio)):
            print('Encontrada')
            return True # La encuentra

    return False # No la encuentra

def checkear_posiciones_activas(valor, precio):
    # Establish connection to MT5
    if not mt5.initialize():
        print("initialize() failed, error code =", mt5.last_error())
        quit()

    # Get all pending orders
    # Use mt5.orders_get() to retrieve all orders.
    # Filter for pending orders based on their type (e.g., mt5.ORDER_TYPE_BUY_LIMIT, mt5.ORDER_TYPE_SELL_STOP, etc.)
    # A more robust approach would be to check if the order is a pending order.
    pending_orders = mt5.positions_get()
    for orden in pending_orders:
        precio_open = orden.price_open
        tipo_orden = orden.type
        simbolo = orden.symbol
        if (simbolo == valor) and (precio_open == float(precio)):
            print('Encontrada')
            return True # La encuentra

    return False # No la encuentra

In [3]:
mt5.last_error()

(0, '')

In [4]:
string = """
Señales Julio-Agosto:⏲️ ORDENES PENDIENTES

Buy Limit BTCUSD 107574.91 SL: 73700
Buy Limit BTCUSD 108734.15 SL: 73700
Buy Limit BTCUSD 109912.4 SL: 73700
Buy Limit BTCUSD 110312.59 SL: 73700
Buy Limit BTCUSD 110874.1 SL: 73700
Buy Limit BTCUSD 112785.01 SL: 73700
Buy Limit BTCUSD 113701.87 SL: 73700
Buy Limit BTCUSD 114809.59 SL: 73700
Buy Limit BTCUSD 115858.77 SL: 73700
Buy Limit BTCUSD 116155.74 SL: 73700
Buy Limit BTCUSD 116997.8 SL: 73700
Buy Limit BTCUSD .69 SL: 73700

Buy Limit ETHUSD 3827.38 SL: 1280
Buy Limit ETHUSD 3991.49 SL: 1280
Buy Limit ETHUSD 4026.12 SL: 1280
Buy Limit ETHUSD 4168.01 SL: 1280
Buy Limit ETHUSD 4170.72 SL: 1280
Buy Limit ETHUSD 4209.6 SL: 1280
Buy Limit ETHUSD 4264.44 SL: 1280
Buy Limit ETHUSD 4304.52 SL: 1280
Buy Limit ETHUSD 4329.77 SL: 1280

Buy Limit TSLA 292.29 SL: 198
Buy Limit TSLA 300.74 SL: 198
Buy Limit TSLA 306.95 SL: 198
Buy Limit TSLA 320.91 SL: 198

> Señales Julio-Agosto:
🚀 SL ETHUSD $4418

> Señales Julio-Agosto:
⏱️📈 Buy limit Creada ETHUSD $4403.9, Sl: 1280

> Señales Julio-Agosto:
⏱️📈 Buy limit Ejecutada BTCUSD $117414.9, Sl: 1280
🚀 SL ETHUSD $4425

Cierre ETHUSD $4550

Compra ETHUSD $4565.09, Sl: 1280
"""

In [5]:
string = """
Señales Julio-Agosto:⏲️ ORDENES PENDIENTES

Buy Limit BTCUSD 107574.91 SL: 73700
Buy Limit TSLA 320.91 SL: 198

> Señales Julio-Agosto:
🚀 SL ETHUSD $4150.3

> Señales Julio-Agosto:
⏱️📈 Buy limit Creada ETHUSD $4201.5, Sl: 1280

> Señales Julio-Agosto:
⏱️📈 Buy limit Ejecutada BTCUSD $117414.9, Sl: 1280
🚀 SL ETHUSD $4200

Cierre ETHUSD $4550

Compra ETHUSD $4565.09, Sl: 1280
"""


string = """
ORDENES PENDIENTES

Buy Limit ETHUSD 3827.38 SL: 1280
Buy Limit ETHUSD 3991.49 SL: 1280
Buy Limit ETHUSD 4026.12 SL: 1280
Buy Limit ETHUSD 4166.36 SL: 1280
"""

string = """
Compra TSLA $331.99, Sl: 198
"""

In [6]:
lista = string.split('\n')
print(lista)
lista2 = []
for l in lista:
    if l != '':
        lista2.append(l.strip())
print(lista2)#[-1]

['', 'Compra TSLA $331.99, Sl: 198', '']
['Compra TSLA $331.99, Sl: 198']

In [7]:
for l in lista2:
    l2 = l.split(' ')
    print(l2)

['Compra', 'TSLA', '$331.99,', 'Sl:', '198']

In [8]:
def crear_all_cases(string):
    lista = string.split('\n')
    lista2 = []
    for l in lista:
        if l != '':
            lista2.append(l.strip())
    print(lista2)#[-1]

    #lista2 = lista2[:3]
    all_cases = []
    for l in lista2:
        l2 = l.split(' ')
        dict_l = {}
        print(l2)
        if 'buy' in l.lower() or 'sell' in l.lower(): # Ordenes pendientes
            
            evaluar_si_es_limit = False
            siguiente_es_valor = False
            siguiente_es_sl = False
            siguiente_es_precio = False
            dict_l['ejecutada'] = False # Por defecto
            dict_l['creada'] = False # Por defecto
            dict_l['nombre'] = 'buy/sell'
            for k in l2:
                if k.lower() == 'ejecutada':
                    dict_l['ejecutada'] = True
                if k.lower() == 'creada':
                    dict_l['creada'] = True
                if siguiente_es_sl:
                    dict_l['sl'] = float(k.replace('$',''))
                    siguiente_es_sl = False
                if siguiente_es_precio:
                    #print('PRECIO', k)
                    dict_l['precio'] = float(k.replace('$','').replace(',',''))
                    siguiente_es_precio = False
                if siguiente_es_valor and (k.lower() not in ['creada', 'ejecutada']):
                    dict_l['valor'] = k
                    siguiente_es_precio = True
                    siguiente_es_valor = False
                    #print('siguiente es precio',dict_l['valor'])

                if evaluar_si_es_limit and (k.lower() == 'limit'):
                    dict_l['limit'] = True
                elif evaluar_si_es_limit and (k.lower() != 'limit'):
                    dict_l['limit'] = False

                if evaluar_si_es_limit:
                    evaluar_si_es_limit = False
                    siguiente_es_valor = True
                if (k.lower() == 'buy') or (k.lower() == 'sell'):
                    dict_l['tipo'] = k
                    evaluar_si_es_limit = True
                if k.lower().replace(':', '') == 'sl':
                    dict_l['sl'] = k
                    siguiente_es_sl = True
                
            #print(l2, dict_l)
            #sys.exit()
        elif ('SL' in l2) or ('sl' in l2):
            print('CAMBIO SL')
            dict_l['nombre'] = 'cambio SL'
            dict_l['tipo'] = 'cambio SL'
            siguiente_es_sl = False
            siguiente_es_valor = False
            for k in l2:
                if siguiente_es_sl:
                    dict_l['sl'] = float(k.replace('$',''))
                    siguiente_es_sl = False
                if siguiente_es_valor:
                    dict_l['valor'] = k
                    siguiente_es_sl = True
                    siguiente_es_valor = False
                if k.lower().replace(':', '') == 'sl':
                    siguiente_es_valor = True
        elif ('Señales' in l2) or ('señales' in l2) or ('Pendientes' in l2) or ('PENDIENTES' in l2):
            continue
            None # Es el título del grupo (arriba en cada mensaje)
        elif ('Cierre' in l2) or ('cierre' in l2):
            dict_l['nombre'] = 'Cierre operación'
            dict_l['tipo'] = 'Cierre'
            siguiente_es_precio = False
            for k in l2:
                if siguiente_es_precio:
                    dict_l['precio'] = float(k.replace('$',''))
                    siguiente_es_precio = False
                if siguiente_es_valor:
                    dict_l['valor'] = k
                    siguiente_es_precio = True
                    siguiente_es_valor = False
                if k.lower().replace(':', '') == 'cierre':
                    siguiente_es_valor = True
            #print(l2, dict_l)
        elif ('Compra' in l2) or ('compra' in l2): # Ordenes pendientes
            dict_l['nombre'] = 'Compra ejecutada'
            #sys.exit('Revisar lógica abajo')
            siguiente_es_valor = False
            siguiente_es_sl = False
            for k in l2:
                if siguiente_es_sl:
                    dict_l['sl'] = float(k.replace('$',''))
                    siguiente_es_sl = False

                if siguiente_es_valor and (k.lower() not in ['creada', 'ejecutada']):
                    print('K', k)
                    dict_l['valor'] = k
                    siguiente_es_valor = False

                if k.lower().replace(':', '') == 'compra':
                    siguiente_es_valor = True

                if (k.lower() == 'compra'):
                    dict_l['tipo'] = k
                if k.lower().replace(':', '') == 'sl':
                    dict_l['sl'] = k
                    siguiente_es_sl = True
        else:
            print('No identificado:')
            print(l2) #, dict_l)
            sys.exit()
        
        print('l2', l2)
        print('dict_l', dict_l)
        all_cases.append(dict_l)
    
    return all_cases
            
            
            

# De cada elemento de la lista, elimina cualquie

In [9]:
#symbol_info = mt5.symbol_info("TSLA")
#print("Filling modes permitidos para TSLA:", symbol_info.filling_mode)

In [10]:
all_cases = crear_all_cases(string)

['Compra TSLA $331.99, Sl: 198']
['Compra', 'TSLA', '$331.99,', 'Sl:', '198']
K TSLA
l2 ['Compra', 'TSLA', '$331.99,', 'Sl:', '198']
dict_l {'nombre': 'Compra ejecutada', 'tipo': 'Compra', 'valor': 'TSLA', 'sl': 198.0}

# Conexión completa

In [11]:
import yfinance as yf
import datetime as dt
import pandas as  pd

In [12]:
def obtener_z_score(valor, price, t = 14):
    
    today = dt.date.today()
    df = yf.download(tickers=valor, period=f'{2 * t}d', interval='1d', end = today)
    df = df.reset_index() # Se resetea el índice
    df = df[df['Date'] < pd.to_datetime(today)] # Se elimina el día actual incompleto
    df.columns = ['Date', 'Close', 'High', 'Low', 'Open', 'Volume']
    
    #df = df.tail(t)
    df['MA'] = df['Close'].rolling(window=t).mean()
    df['STD'] = df['Close'].rolling(window=t).std()
    df['Upper'] = df['MA'] + (df['STD'] * 2)
    df['Lower'] = df['MA'] - (df['STD'] * 2)
    
    MA, std = df['MA'].values[-1], df['STD'].values[-1]
    #print(f'Close: {close}, MA: {MA}, STD: {std}')
    #df['Z_score'] = (df['Close'] - df['MA']) / df['STD']
    #display(df)
    
    z_score_actual = float((price - MA) / std)
    print(f'Z-score actual: {z_score_actual}')
    return z_score_actual

In [13]:
def generate_request_buy_limit(valor, order_type = '', sl = '', volumen = 0, precio = 0):
    
    # Parámetros extraídos del string
    symbol = valor
    symbol_info = mt5.symbol_info(symbol)
    #point = symbol_info.point
    #price = mt5.symbol_info_tick(symbol).ask

    #print(price, sl)

    request = {
        "action": mt5.TRADE_ACTION_PENDING,
        "symbol": symbol,
        "volume": volumen,
        "type": order_type,
        "price": precio,
        "sl": float(sl),
        "deviation": 10,
        "magic": 123456,
        "comment": "Orden BUY desde Python",
        "type_time": mt5.ORDER_TIME_GTC,
        "type_filling": mt5.ORDER_FILLING_FOK,
    }
    
    return request


def generate_request_buy(valor, order_type = '', sl = '', volumen = 0, precio = 0):
    
    # Parámetros extraídos del string
    symbol = valor
    symbol_info = mt5.symbol_info(symbol)
    point = symbol_info.point
    price = mt5.symbol_info_tick(symbol).ask

    #print(price, sl)

    request = {
        "action": mt5.TRADE_ACTION_DEAL,
        "symbol": symbol,
        "volume": volumen,
        "type": order_type,
        "price": price,
        "sl": float(sl),
        "deviation": 10,
        "magic": 123456,
        "comment": "Orden BUY desde Python",
        "type_time": mt5.ORDER_TIME_GTC,
        "type_filling": mt5.ORDER_FILLING_IOC,
        }
    
    return request

In [14]:
symbol = 'TSLA'
mt5.initialize()
account_info = mt5.account_info()
mt5.symbol_info_tick(symbol).ask

329.36

In [15]:
def generar_max_proporcion(z_score, regla):
    # regla = [min no importa el caso, max a z_score = -2, max a z_score = 0, max a z_score = 2, max no importa el caso]
    # máxima proporción de la cuenta que se va a usar en la operación
    # 1. interpolar

    if (z_score >= 0):
        max_proporcion = regla[2] + ( (z_score - 0) * (regla[1] - regla[2]) / (2 - 0) ) # ecuación de la recta
    else:
        max_proporcion = regla[3] + ( (z_score - (-2)) * (regla[2] - regla[3]) / (0 - (-2)) ) # ecuación de la recta
    
    if max_proporcion < regla[0]:
        max_proporcion = regla[0]
    if max_proporcion > regla[-1]:
        max_proporcion = regla[-1]
    
    return max_proporcion

In [16]:
def obtener_dinero_cuenta():
    mt5.initialize()
    account_info = mt5.account_info()
    balance = account_info.balance
    if account_info is None:
        print("No se pudo obtener la información de la cuenta (uso por defecto)")
        balance = 1000 # TO DO: Cada vez que se lea, almacenar y rescatar ese número por defecto
        mt5.shutdown()
        sys.exit()
    return balance

obtener_dinero_cuenta()

2000.0

In [17]:
regla = [3, 3.5, 4, 4.5, 5]

In [18]:
float(yf.Ticker('ETH-USD').history(period='1d')['Close'][0])

C:\Users\mvaldiviad\AppData\Local\Temp\ipykernel_22024\3598902058.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  float(yf.Ticker('ETH-USD').history(period='1d')['Close'][0])

4344.083984375

In [19]:
# lote es cuantas unidades del activo van en un lote
# SL_LP: SL de largo plazo (para abrir operación)

info_valores = {'BTCUSD': {'apalancamiento': 400, 'lote': 1, 'yfsymbol': 'BTC-USD', 'min_lotaje': 0.01}, 
                'ETHUSD': {'apalancamiento': 400, 'lote': 1, 'yfsymbol': 'ETH-USD', 'min_lotaje': 0.1},
                'TSLA': {'apalancamiento': 20, 'lote': 10, 'yfsymbol': 'TSLA', 'min_lotaje': 0.01}
                
        }
                

alpha_SL = 0.04
for valor in info_valores.keys():
    precio_actual = float(yf.Ticker(info_valores[valor]['yfsymbol']).history(period='1d')['Close'][0])
    info_valores[valor]['SL_LP'] = precio_actual * (1 - alpha_SL)

info_valores

C:\Users\mvaldiviad\AppData\Local\Temp\ipykernel_22024\1467446120.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  precio_actual = float(yf.Ticker(info_valores[valor]['yfsymbol']).history(period='1d')['Close'][0])
C:\Users\mvaldiviad\AppData\Local\Temp\ipykernel_22024\1467446120.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  precio_actual = float(yf.Ticker(info_valores[valor]['yfsymbol']).history(period='1d')['Close'][0])
C:\Users\mvaldiviad\AppData\Local\Temp\ipykernel_22024\1467446120.py:13: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  precio_actual = float(yf.Ticker(info_valores[valor]['yfsymbol']).history(period='1d')['Close'][0])

{'BTCUSD': {'apalancamiento': 400,
  'lote': 1,
  'yfsymbol': 'BTC-USD',
  'min_lotaje': 0.01,
  'SL_LP': 106829.0925},
 'ETHUSD': {'apalancamiento': 400,
  'lote': 1,
  'yfsymbol': 'ETH-USD',
  'min_lotaje': 0.1,
  'SL_LP': 4170.320625},
 'TSLA': {'apalancamiento': 20,
  'lote': 10,
  'yfsymbol': 'TSLA',
  'min_lotaje': 0.01,
  'SL_LP': 316.156787109375}}

In [20]:
def definir_lotes(valor, info_valores, regla):

    if valor in info_valores.keys():
        lote_size = info_valores[valor]['lote']
        apalancamiento = info_valores[valor]['apalancamiento']
        yf_symbol = info_valores[valor]['yfsymbol']
        sl_lp = info_valores[valor]['SL_LP']
        min_lotaje = info_valores[valor]['min_lotaje']
    
    #print(lote, apalancamiento)

    balance = obtener_dinero_cuenta()
    try:
        price = mt5.symbol_info_tick(valor).ask
    except:
        print('Error al obtener precio de', valor)
        return 0, sl_lp
    print('Precio actual:', price)
    z_score = obtener_z_score(yf_symbol, price)

    max_proporcion = generar_max_proporcion(z_score, regla)
    lotes_ejecucion = ((balance * (max_proporcion / 100) / (lote_size * (price - sl_lp))) // min_lotaje) * min_lotaje # al final, división parte entera y, se compra esa cantida de veces, el mínimo
    usd_invertidos = price * lote_size * lotes_ejecucion / apalancamiento
    print(f'Lotes a ejecutar: {lotes_ejecucion} | USD invertidos: {usd_invertidos}')
    return lotes_ejecucion, sl_lp
#definir_lotes('BTCUSD', info_valores)

In [21]:
def ejecutar_orden(request, symbol, volume, price):
    if 'sl' in request.keys(): #250902
        request['sl'] = float(round(request['sl'], 0))
        
    if volume == 0:
        print('No se ejecuta por volumen = 0')
        return None
    # send a trading request
    result = mt5.order_send(request)
    # check the execution result
    print("1. order_send(): by {} {} lots at {} with deviation={} points".format(symbol, volume, price, 10));
    #print(result)
    if result.retcode != mt5.TRADE_RETCODE_DONE:
        print("2. order_send failed, retcode={}".format(result.retcode))
        # request the result as a dictionary and display it element by element
        result_dict = result._asdict()
        for field in result_dict.keys():
            print("   {}={}".format(field, result_dict[field]))
            # if this is a trading request structure, display it element by element as well
            if field == "request":
                traderequest_dict = result_dict[field]._asdict()
                for tradereq_filed in traderequest_dict:
                    print("       traderequest: {}={}".format(tradereq_filed, traderequest_dict[tradereq_filed]))
        print("shutdown() and quit")
        mt5.shutdown()
        quit()
    
    return None

In [22]:
def contar_operaciones_abiertas():
    # Establish connection to MT5
    if not mt5.initialize():
        print("initialize() failed, error code =", mt5.last_error())
        quit()

    # Get all pending orders
    # Use mt5.orders_get() to retrieve all orders.
    # Filter for pending orders based on their type (e.g., mt5.ORDER_TYPE_BUY_LIMIT, mt5.ORDER_TYPE_SELL_STOP, etc.)
    # A more robust approach would be to check if the order is a pending order.
    # obtener ordenes abiertas actualmente
    actual_positions = mt5.positions_get(symbol = valor)
    return len(actual_positions)

In [23]:
def cambiar_SL(valor, sl):
  
    # Establish connection to MT5
    if not mt5.initialize():
        print("initialize() failed, error code =", mt5.last_error())
        quit()

    # Get all pending orders
    # Use mt5.orders_get() to retrieve all orders.
    # Filter for pending orders based on their type (e.g., mt5.ORDER_TYPE_BUY_LIMIT, mt5.ORDER_TYPE_SELL_STOP, etc.)
    # A more robust approach would be to check if the order is a pending order.
    # obtener ordenes abiertas actualmente
    actual_positions = mt5.positions_get(symbol = valor)

    verify = True
    if actual_positions is None:
        print("No pending orders found or orders_get() failed.")
    else:
        for position in actual_positions:
            print(position)
            # Hacer cambio de SL
            print(position.ticket)
            #print(position.sl)
            #sys.exit('Cambiar SL')
            print('SL', sl)
            
            request = {
            "action": mt5.TRADE_ACTION_SLTP,
            "position": position.ticket,
            "symbol": valor,
            "sl": sl,
            "magic": 234000, # Example magic number
            "comment": "Modify SL via Python"
            }
            
            result = mt5.order_send(request)
            if result.retcode == mt5.TRADE_RETCODE_DONE:
                print(f"Stop Loss modified successfully for position {position.ticket}.")
            else:
                print(f"Failed to modify Stop Loss: {result.comment}")
                verify = False
        if verify:
            print(f'Cambios exitosos para: {valor}')
    
    return None

In [ ]:
def cerrar_operaciones_abiertas(valor):
    
    if not mt5.initialize():
        print("initialize() failed, error code =", mt5.last_error())
        quit()
    
    positions = mt5.positions_get(symbol = valor)
    if positions is None:
        print("No positions found, error code =", mt5.last_error())
        mt5.shutdown()
        quit()
    
    for position in positions:
        # Determine the closing action (SELL for BUY positions, BUY for SELL positions)
        if position.type == mt5.ORDER_TYPE_BUY:
            order_type = mt5.ORDER_TYPE_SELL
            price = mt5.symbol_info_tick(position.symbol).bid # Use Bid price for closing BUY
        elif position.type == mt5.ORDER_TYPE_SELL:
            order_type = mt5.ORDER_TYPE_BUY
            price = mt5.symbol_info_tick(position.symbol).ask # Use Ask price for closing SELL
        else:
            continue # Skip if position type is not BUY or SELL
        
        # DEtermina si tiene ganancia o no
        print('IMPORTANTE PARA CONTROL DE CIERRE')
        profit = position.profit
        if profit > 0:
            print(f'La posición {position.ticket} tiene ganancia de {profit}')
        else:
            print(f'La posición {position.ticket} tiene pérdida de {profit}')
            

        # Prepare the close request
        request = {
            "action": mt5.TRADE_ACTION_DEAL,
            "symbol": position.symbol,
            "volume": position.volume,
            "type": order_type,
            "price": price,
            "deviation": 10, # Adjust deviation as needed
            "position": position.ticket,
            "comment": "Closing position by symbol",
            "type_filling": mt5.ORDER_FILLING_FOK, # Or other filling types
        }

        # Send the close request
        result = mt5.order_send(request)
        if result.retcode != mt5.TRADE_RETCODE_DONE:
            print(f"Failed to close position {position.ticket}, retcode={result.retcode}")
        else:
            print(f"Position {position.ticket} closed successfully.")
    
    return None

Iteración

In [25]:
contar_operaciones_abiertas()

0

In [26]:
for i, d_t in enumerate(all_cases):
    C = contar_operaciones_abiertas()
    
    if d_t == {}:
        continue
    
    print(d_t)
    if (d_t.get('nombre') == 'buy/sell') and (d_t.get('limit')) and (not d_t.get('ejecutada')) and (not d_t.get('creada')):
        # Si no es ni creada ni ejecutada (ordenes pendientes, checkear que efectivamente están [TO DO: Ver función ckeckear_ordenes_pendientes (sin eliminar las pendientes, solo confirmarlas)])
        valor = d_t.get('valor')
        #SL = d_t.get('sl') No se considera por ahora, se considera uno propio
        tipo = d_t.get('tipo').lower()
        precio = d_t.get('precio')

        encontrada = checkear_ordenes_pendientes(valor, tipo, precio)
        if not encontrada: # Si no se encuentra, se crea el buy limit   
            if tipo == 'buy':
                order_type = mt5.ORDER_TYPE_BUY_LIMIT
            else:
                order_type = mt5.ORDER_TYPE_SELL_LIMIT
            
            #print(order_type)
            lotes_ejecucion, sl = definir_lotes(valor, info_valores, regla)
            request = generate_request_buy_limit(valor, order_type, sl = sl, volumen = lotes_ejecucion, precio = precio)        
            #sys.exit()
            ejecutar_orden(request, valor, lotes_ejecucion, precio)
            
        print('Falta hacer chequeo de ordenes pendientes')
    elif (d_t.get('nombre') == 'buy/sell') and (d_t.get('limit')) and (not d_t.get('ejecutada')) and (d_t.get('creada')):
        valor = d_t.get('valor')
        #SL = d_t.get('sl') No se considera por ahora, se considera uno propio
        tipo = d_t.get('tipo').lower()
        precio = d_t.get('precio')
        if tipo == 'buy':
            order_type = mt5.ORDER_TYPE_BUY_LIMIT
        else:
            order_type = mt5.ORDER_TYPE_SELL_LIMIT
        
        #print(order_type)
        lotes_ejecucion, sl = definir_lotes(valor, info_valores, regla)
        request = generate_request_buy_limit(valor, order_type, sl = sl, volumen = lotes_ejecucion, precio = precio)        
        #sys.exit()
        ejecutar_orden(request, valor, lotes_ejecucion, precio)
        #sys.exit()
    elif (d_t.get('nombre') == 'buy/sell') and (d_t.get('limit')) and (d_t.get('ejecutada')) and (not d_t.get('creada')):
        print('Alerta de orden ejecutada [BUY LIMIT]')
        
        valor = d_t.get('valor')
        #SL = d_t.get('sl') No se considera por ahora, se considera uno propio
        tipo = d_t.get('tipo').lower()
        precio = d_t.get('precio')
        encontrada_pendiente = checkear_ordenes_pendientes(valor, tipo, precio)
        encontrada_activa = checkear_posiciones_activas(valor, precio)
        
        if encontrada_activa and not encontrada_pendiente:
            print('OK, la orden ya fue ejecutada')
            continue
        elif encontrada_pendiente and not encontrada_activa:
            print('La orden está pendiente, no se ha ejecutado aún [Revisar que se ejecute!!!]')
            continue
        elif encontrada_pendiente and encontrada_activa:
            print('La orden está pendiente y además hay una posición abierta [Caso extraño, revisar!!!]')
            continue
        elif not encontrada_pendiente and not encontrada_activa:
            print('Ejecutar')
            order_type = mt5.ORDER_TYPE_BUY
        
            lotes_ejecucion, sl = definir_lotes(valor, info_valores, regla)
            request = generate_request_buy(valor, order_type, sl = sl, volumen = lotes_ejecucion, precio = precio)        
            #sys.exit()
            ejecutar_orden(request, valor, lotes_ejecucion, precio)
        
        
        print(d_t)
        
        if contar_operaciones_abiertas() == C + 1:
            print('OK, la orden fue ejecutada')
        print('C', C, 'Contar operaciones abiertas', contar_operaciones_abiertas())
        
        
        # confirmar que las posiciones abiertas aumentan en 1
        
        
    elif (d_t.get('nombre') == 'cambio SL'):
        valor = d_t.get('valor')
        sl = d_t.get('sl')
        
        # Hacer cambio SL
        cambiar_SL(valor, sl)
    
    elif (d_t.get('nombre') == 'Cierre operación'):
        valor = d_t.get('valor')
        cerrar_operaciones_abiertas(valor)
    
    elif (d_t.get('nombre') == 'Compra ejecutada'):
        valor = d_t.get('valor')
        #SL = d_t.get('sl') No se considera por ahora, se considera uno propio
        tipo = d_t.get('tipo').lower()
        order_type = mt5.ORDER_TYPE_BUY
        
        lotes_ejecucion, sl = definir_lotes(valor, info_valores, regla)
        request = generate_request_buy(valor, order_type, sl = sl, volumen = lotes_ejecucion)        
        #sys.exit()
        if 'price' in request.keys(): # n250902
            del request['price']
        print(request)
        
        #sys.exit()
        precio = "A"
        ejecutar_orden(request, valor, lotes_ejecucion, precio)
        
    else:
        print(d_t)
        sys.exit('Este caso no está reconocido')

{'nombre': 'Compra ejecutada', 'tipo': 'Compra', 'valor': 'TSLA', 'sl': 198.0}
Precio actual: 329.43

C:\Users\mvaldiviad\AppData\Local\Temp\ipykernel_22024\3667237314.py:4: FutureWarning: YF.download() has changed argument auto_adjust default to True
  df = yf.download(tickers=valor, period=f'{2 * t}d', interval='1d', end = today)
[*********************100%***********************]  1 of 1 completed

Z-score actual: -0.8404994260855303
Lotes a ejecutar: 0.63 | USD invertidos: 103.77045000000001
{'action': 1, 'symbol': 'TSLA', 'volume': 0.63, 'type': 0, 'sl': 316.156787109375, 'deviation': 10, 'magic': 123456, 'comment': 'Orden BUY desde Python', 'type_time': 0, 'type_filling': 1}
1. order_send(): by TSLA 0.63 lots at A with deviation=10 points
2. order_send failed, retcode=10030
   retcode=10030
   deal=0
   order=0
   volume=0.0
   price=0.0
   bid=0.0
   ask=0.0
   comment=Unsupported filling mode
   request_id=0
   retcode_external=0
   request=TradeRequest(action=1, magic=123456, order=0, symbol='TSLA', volume=0.63, price=0.0, stoplimit=0.0, sl=316.0, tp=0.0, deviation=10, type=0, type_filling=1, type_time=0, expiration=0, comment='Orden BUY desde Python', position=0, position_by=0)
       traderequest: action=1
       traderequest: magic=123456
       traderequest: order=0
       traderequest: symbol=TSLA
       traderequest: volume=0.63
       traderequest: price=0.0
       traderequest: stoplimit=0.0
       traderequest: sl=316.0
       traderequest: tp=0.0
       traderequest: deviation=10
       traderequest: type=0
       traderequest: type_filling=1
       traderequest: type_time=0
       traderequest: expiration=0
       traderequest: comment=Orden BUY desde Python
       traderequest: position=0
       traderequest: position_by=0
shutdown() and quit

In [ ]:
sys.exit()

SystemExit:

c:\Users\mvaldiviad\AppData\Local\anaconda3\envs\revenAI\Lib\site-packages\IPython\core\interactiveshell.py:3675: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

:

# Conexión con MT5

In [ ]:
# establish connection to the MetaTrader 5 terminal
if not mt5.initialize():
    print("initialize() failed, error code =", mt5.last_error())
    quit()


# Parámetros extraídos del string
symbol = "BTCUSD"
order_type = mt5.ORDER_TYPE_BUY_LIMIT
price = 105679
sl = 73000
volume = 0.01  # puedes ajustar el volumen

symbol_info = mt5.symbol_info(symbol)
point = symbol_info.point
price = mt5.symbol_info_tick(symbol).ask
sl = 70000.0 #price - 5000  # Ejemplo: SL 5000 puntos abajo
#tp = 150000.0 #price + 5000  # Ejemplo: TP 5000 puntos arriba

print(price, sl, tp)


request = {
    "action": mt5.TRADE_ACTION_DEAL,
    "symbol": symbol,
    "volume": volume,
    "type": mt5.ORDER_TYPE_BUY,
    "price": price,
    "sl": sl,
    #"tp": tp,
    "deviation": 10,
    "magic": 123456,
    "comment": "Orden BUY desde Python",
    "type_time": mt5.ORDER_TIME_GTC,
    "type_filling": mt5.ORDER_FILLING_IOC,
}


def ejecutar_orden(request):
    if 'sl' in request.keys():
        request['sl'] = float(round(request['sl'], 0))
    
    print('R2', request)
    # send a trading request
    result = mt5.order_send(request)
    # check the execution result
    print("1. order_send(): by {} {} lots at {} with deviation={} points".format(symbol, volume, price, 10));
    if result.retcode != mt5.TRADE_RETCODE_DONE:
        print("2. order_send failed, retcode={}".format(result.retcode))
        print(mt5.last_error())
        # request the result as a dictionary and display it element by element
        result_dict = result._asdict()
        for field in result_dict.keys():
            print("   {}={}".format(field, result_dict[field]))
            # if this is a trading request structure, display it element by element as well
            if field == "request":
                traderequest_dict = result_dict[field]._asdict()
                for tradereq_filed in traderequest_dict:
                    print("       traderequest: {}={}".format(tradereq_filed, traderequest_dict[tradereq_filed]))
        print("shutdown() and quit")
        mt5.shutdown()
        quit()

ejecutar_orden(request)

# Otros

In [ ]:
request

In [ ]:
request

In [ ]:
request = {
    "action": mt5.TRADE_ACTION_DEAL,
    "symbol": symbol,
    "volume": volume,
    "type": mt5.ORDER_TYPE_BUY,
    "price": price,
    "sl": sl,
    "tp": tp,
    "deviation": 10,
    "magic": 123456,
    "comment": "Orden BUY desde Python",
    "type_time": mt5.ORDER_TIME_GTC,
    "type_filling": mt5.ORDER_FILLING_IOC,
}

request

In [ ]:
"    request = {
        "action": mt5.TRADE_ACTION_DEAL,
        "symbol": symbol,
        "volume": volumen,
        "type": order_type,
        "price": price,
        "sl": float(sl),
        "deviation": 10,
        "magic": 123456,
        "comment": "Orden BUY desde Python",
        "type_time": mt5.ORDER_TIME_GTC,
        "type_filling": mt5.ORDER_FILLING_IOC,
        }"

In [24]:
import MetaTrader5 as mt5

# Inicializa la conexión con MetaTrader 5
#mt5.initialize()

symbol = 'TSLA'
mt5.initialize()
account_info = mt5.account_info()
print(mt5.symbol_info_tick(symbol).ask)

# Definir el símbolo
#symbol = "TSLA"

# Verifica si el símbolo está seleccionado correctamente
if not mt5.symbol_select(symbol, True):
    print(f"No se pudo seleccionar el símbolo {symbol}")
    mt5.shutdown()
    quit()

# Crea la solicitud de orden con un tipo de llenado compatible
request = {
    "action": mt5.TRADE_ACTION_DEAL,
    "symbol": symbol,
    "volume": 0.01,
    #"price": 330.92,
    "sl": 317.0,
    #"tp": 0.0,
    "deviation": 10,
    "type": mt5.ORDER_TYPE_BUY,
    #"type_filling": mt5.ORDER_FILLING_IOC,  # Cambié a RETURN que es más común
    "type_time": mt5.ORDER_TIME_GTC,
    "comment": "Orden BUY desde Python",
    "magic": 123450,
    #"expiration": 0,
    #"position": 0,
}

# Enviar la orden
result = mt5.order_send(request)

print(result)
if result.retcode != mt5.TRADE_RETCODE_DONE:
    print(f"Error al enviar la orden: {result.retcode}")
else:
    print(f"Orden enviada correctamente: {result}")

# Cerrar la conexión
mt5.shutdown()

328.56
OrderSendResult(retcode=10009, deal=160215323, order=220923013, volume=0.01, price=328.53999999999996, bid=328.46, ask=328.53999999999996, comment='Orden BUY desde ', request_id=3549767643, retcode_external=0, request=TradeRequest(action=1, magic=123450, order=0, symbol='TSLA', volume=0.01, price=0.0, stoplimit=0.0, sl=317.0, tp=0.0, deviation=10, type=0, type_filling=0, type_time=0, expiration=0, comment='Orden BUY desde Python', position=0, position_by=0))
Orden enviada correctamente: OrderSendResult(retcode=10009, deal=160215323, order=220923013, volume=0.01, price=328.53999999999996, bid=328.46, ask=328.53999999999996, comment='Orden BUY desde ', request_id=3549767643, retcode_external=0, request=TradeRequest(action=1, magic=123450, order=0, symbol='TSLA', volume=0.01, price=0.0, stoplimit=0.0, sl=317.0, tp=0.0, deviation=10, type=0, type_filling=0, type_time=0, expiration=0, comment='Orden BUY desde Python', position=0, position_by=0))

True

In [11]:
mt5.last_error()

(1, 'Success')

In [2]:
result

OrderSendResult(retcode=10030, deal=0, order=0, volume=0.0, price=0.0, bid=0.0, ask=0.0, comment='Unsupported filling mode', request_id=0, retcode_external=0, request=TradeRequest(action=1, magic=123456, order=0, symbol='TSLA', volume=0.62, price=330.92, stoplimit=0.0, sl=317.6351953125, tp=0.0, deviation=10, type=0, type_filling=2, type_time=0, expiration=0, comment='Orden BUY desde Python', position=0, position_by=0))