# Librerías y Módulos

In [1]:
import sys

# Obtener la lista de kernels
kernels = !jupyter kernelspec list

# Mostrar la lista de kernels para referencia
print(kernels)

# Buscar si 'mi_entorno' está en la lista de kernels
kernel_name = "mi_entorno"
kernel_found = False

for line in kernels:
    if kernel_name in line:
        kernel_found = True
        break

# Comprueba si el kernel de ejecución es mi_entorno
if not kernel_found:
    print(f'Kernel debe ser: {kernel_name}')
    #sys.exit()

print(f'Kernel correcto: {kernel_name}')

['"jupyter" no se reconoce como un comando interno o externo,', 'programa o archivo por lotes ejecutable.']
Kernel debe ser: mi_entorno
Kernel correcto: mi_entorno

## Librerías

In [2]:
import pandas as pd
import sys

import warnings
warnings.filterwarnings("ignore")

In [3]:
sys.path.insert(0, '')
from Clase_Valor_240902 import Valor
from Transversal import leer_activos, leer_parametros

In [4]:
# Prueba de funcionamiento

import yfinance as yf
df = yf.download('AAPL')

df = df.reset_index()
df['Date'] = pd.to_datetime(df['Date'], format = '%Y-%m-%d').dt.date


#display(df)
#self.raw_data = self.raw_data_new.reset_index() # Se resetea el índice
#self.raw_data['Date'] = pd.to_datetime(self.raw_data['Date'], format = '%Y-%m-%d').dt.date # Traspaso a formato día
#self.ultima_fecha_data = self.raw_data['Date'].max() # Último día para el que existen los datos


df.columns = ['Date', 'Close', 'High', 'Low', 'Open', 'Volume']
df

YF.download() has changed argument auto_adjust default to True

[*********************100%***********************]  1 of 1 completed

             Date       Close        High         Low        Open     Volume
0      1980-12-12    0.098597    0.099025    0.098597    0.098597  469033600
1      1980-12-15    0.093453    0.093881    0.093453    0.093881  175884800
2      1980-12-16    0.086594    0.087022    0.086594    0.087022  105728000
3      1980-12-17    0.088737    0.089165    0.088737    0.088737   86441600
4      1980-12-18    0.091310    0.091738    0.091310    0.091310   73449600
...           ...         ...         ...         ...         ...        ...
11225  2025-06-27  201.080002  203.220001  200.000000  201.889999   73188600
11226  2025-06-30  205.169998  207.389999  199.259995  202.009995   91912800
11227  2025-07-01  207.820007  210.190002  206.139999  206.669998   78788900
11228  2025-07-02  212.440002  213.339996  208.139999  208.910004   67941800
11229  2025-07-03  213.550003  214.649994  211.810104  212.145004   34697317

[11230 rows x 6 columns]

In [5]:
df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d').dt.date.astype('str')
df[df['Date'] >= '2025-02-12']

             Date       Close        High         Low        Open    Volume
11132  2025-02-12  236.559784  236.649678  230.377888  230.897211  45243300
11133  2025-02-13  241.213684  242.022621  235.261498  236.599739  53614100
11134  2025-02-14  244.279663  245.228416  240.674390  240.934044  40896200
11135  2025-02-18  244.149841  244.858903  241.523281  243.830253  48822500
11136  2025-02-19  244.549301  245.687808  242.841549  244.339585  32204200
...           ...         ...         ...         ...         ...       ...
11225  2025-06-27  201.080002  203.220001  200.000000  201.889999  73188600
11226  2025-06-30  205.169998  207.389999  199.259995  202.009995  91912800
11227  2025-07-01  207.820007  210.190002  206.139999  206.669998  78788900
11228  2025-07-02  212.440002  213.339996  208.139999  208.910004  67941800
11229  2025-07-03  213.550003  214.649994  211.810104  212.145004  34697317

[98 rows x 6 columns]

# Parámetros

In [6]:
reextraer_todo = True # Parámetro: SI es True, se vuelven a extraer todos los datos. Si es False, se extraen solo los valores que no estén actualizados hasta ayer
output = True

In [7]:
carpeta_input, cofre, seguimiento, saving_step = leer_parametros()

# Lectura de activos

In [8]:
df_activos = leer_activos(carpeta_input)
df_activos

    SIMBOLO                      NOMBRE
0      AAPL                  Apple Inc.
1      AMZN                      Amazon
2     BRK-A         Berkshire Hathaway
3   BTC-USD                     Bitcoin
4       DOW                         DOW
5       DVA                 DaVita Inc.
6       IBM                         IBM
7       MCD                         MCD
8       MRK                         MRK
9      MSFT                   Microsoft
10     NFLX               Netflix, Inc.
11      NKE                         NKE
12     SMCI  Super Micro Computer, Inc.
13     TSLA                       Tesla
14      WMT                     Walmart

# Ejecución

In [9]:
#df_activos = df_activos.iloc[1:].reset_index(drop = True) # solo prueba
df_activos

    SIMBOLO                      NOMBRE
0      AAPL                  Apple Inc.
1      AMZN                      Amazon
2     BRK-A         Berkshire Hathaway
3   BTC-USD                     Bitcoin
4       DOW                         DOW
5       DVA                 DaVita Inc.
6       IBM                         IBM
7       MCD                         MCD
8       MRK                         MRK
9      MSFT                   Microsoft
10     NFLX               Netflix, Inc.
11      NKE                         NKE
12     SMCI  Super Micro Computer, Inc.
13     TSLA                       Tesla
14      WMT                     Walmart

In [10]:
#df_activos = df_activos[df_activos['SIMBOLO'] == 'AMZN'].reset_index(drop = True)

#sys.exit('small batch. Eliminar')

In [11]:
agregar_nuevo_dia = True # parámetro, subir

In [12]:
# NUEVO
for i in range(len(df_activos)):
    simbolo, nombre = df_activos.loc[i]
    print(simbolo, nombre)
    valor = Valor(simbolo, nombre, cofre, saving_step, output = output) # Si no existe el objeto, se crea
    
    valor.extraer_data(reextraer_todo = reextraer_todo) # Extrae la data del valor correspondiente, solo si existen días nuevos
    valor.ajustar_data(agregar_nuevo_dia = agregar_nuevo_dia) # interpola en algunos casos (por ahora al menos, interpolar está desactivado), y estandariza la data (0, 1)
    
    valor.guardar()

AAPL Apple Inc.
Rescate en ../Cofre/Valor/ AAPL
../Cofre/Valor/AAPL
<_io.BufferedReader name='../Cofre/Valor/AAPL.pkl'>
Descarga de data

[*********************100%***********************]  1 of 1 completed

         Date     Close      High       Low      Open     Volume
0  1980-12-12  0.098597  0.099025  0.098597  0.098597  469033600
1  1980-12-15  0.093453  0.093881  0.093453  0.093881  175884800
2  1980-12-16  0.086594  0.087022  0.086594  0.087022  105728000
3  1980-12-17  0.088737  0.089166  0.088737  0.088737   86441600
4  1980-12-18  0.091310  0.091738  0.091310  0.091310   73449600

             Date       Close        High         Low        Open    Volume
11224  2025-06-26  201.000000  202.639999  199.460007  201.429993  50799100
11225  2025-06-27  201.080002  203.220001  200.000000  201.889999  73188600
11226  2025-06-30  205.169998  207.389999  199.259995  202.009995  91912800
11227  2025-07-01  207.820007  210.190002  206.139999  206.669998  78788900
11228  2025-07-02  212.440002  213.339996  208.139999  208.910004  67941800

2025-07-03

             Date       Close        High         Low        Open       Volume
0      1980-12-12    0.098597    0.099025    0.098597    0.098597  469033600.0
1      1980-12-15    0.093453    0.093881    0.093453    0.093881  175884800.0
2      1980-12-16    0.086594    0.087022    0.086594    0.087022  105728000.0
3      1980-12-17    0.088737    0.089166    0.088737    0.088737   86441600.0
4      1980-12-18    0.091310    0.091738    0.091310    0.091310   73449600.0
...           ...         ...         ...         ...         ...          ...
11225  2025-06-27  201.080002  203.220001  200.000000  201.889999   73188600.0
11226  2025-06-30  205.169998  207.389999  199.259995  202.009995   91912800.0
11227  2025-07-01  207.820007  210.190002  206.139999  206.669998   78788900.0
11228  2025-07-02  212.440002  213.339996  208.139999  208.910004   67941800.0
11229  2025-07-03    0.000000    0.000000    0.000000    0.000000          0.0

[11230 rows x 6 columns]

,Date,t,Open,High,Low,Close,Volume,rendimiento
0,1980-12-12,-15725,0.000380,0.000382,0.000380,0.000380,0.063198,NaN
1,1980-12-15,-15722,0.000362,0.000362,0.000360,0.000360,0.023699,-0.052171
2,1980-12-16,-15721,0.000335,0.000335,0.000334,0.000334,0.014246,-0.073398
3,1980-12-17,-15720,0.000342,0.000344,0.000342,0.000342,0.011647,0.024752
4,1980-12-18,-15719,0.000352,0.000354,0.000352,0.000352,0.009897,0.028992
...,...,...,...,...,...,...,...,...
11225,2025-06-27,543,0.778074,0.783200,0.770790,0.774952,0.009862,0.000398
11226,2025-06-30,546,0.778536,0.799271,0.767938,0.790715,0.012384,0.020340
11227,2025-07-01,547,0.796496,0.810062,0.794453,0.800928,0.010616,0.012916
11228,2025-07-02,548,0.805129,0.822202,0.802161,0.818733,0.009155,0.022231
11229,2025-07-03,549,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000

AMZN Amazon
Rescate en ../Cofre/Valor/ AMZN
../Cofre/Valor/AMZN
<_io.BufferedReader name='../Cofre/Valor/AMZN.pkl'>
Descarga de data

[*********************100%***********************]  1 of 1 completed

         Date     Close      High       Low      Open      Volume
0  1997-05-15  0.097917  0.125000  0.096354  0.121875  1443120000
1  1997-05-16  0.086458  0.098958  0.085417  0.098438   294000000
2  1997-05-19  0.085417  0.088542  0.081250  0.088021   122136000
3  1997-05-20  0.081771  0.087500  0.081771  0.086458   109344000
4  1997-05-21  0.071354  0.082292  0.068750  0.081771   377064000

            Date       Close        High         Low        Open     Volume
7072  2025-06-26  217.119995  218.039993  212.009995  213.119995   50480800
7073  2025-06-27  223.300003  223.300003  216.740005  219.919998  119217100
7074  2025-06-30  219.389999  223.820007  219.119995  223.520004   58887800
7075  2025-07-01  220.460007  221.880005  217.929993  219.500000   39256800
7076  2025-07-02  219.919998  221.600006  219.059998  219.729996   30894200

2025-07-03

            Date       Close        High         Low        Open        Volume
0     1997-05-15    0.097917    0.125000    0.096354    0.121875  1.443120e+09
1     1997-05-16    0.086458    0.098958    0.085417    0.098438  2.940000e+08
2     1997-05-19    0.085417    0.088542    0.081250    0.088021  1.221360e+08
3     1997-05-20    0.081771    0.087500    0.081771    0.086458  1.093440e+08
4     1997-05-21    0.071354    0.082292    0.068750    0.081771  3.770640e+08
...          ...         ...         ...         ...         ...           ...
7073  2025-06-27  223.300003  223.300003  216.740005  219.919998  1.192171e+08
7074  2025-06-30  219.389999  223.820007  219.119995  223.520004  5.888780e+07
7075  2025-07-01  220.460007  221.880005  217.929993  219.500000  3.925680e+07
7076  2025-07-02  219.919998  221.600006  219.059998  219.729996  3.089420e+07
7077  2025-07-03    0.000000    0.000000    0.000000    0.000000  0.000000e+00

[7078 rows x 6 columns]

,Date,t,Open,High,Low,Close,Volume,rendimiento
0,1997-05-15,-9727,0.000503,0.000515,0.000397,0.000404,0.691618,NaN
1,1997-05-16,-9726,0.000406,0.000408,0.000352,0.000356,0.140900,-0.117028
2,1997-05-19,-9723,0.000363,0.000365,0.000335,0.000352,0.058534,-0.012040
3,1997-05-20,-9722,0.000356,0.000361,0.000337,0.000337,0.052403,-0.042685
4,1997-05-21,-9721,0.000337,0.000339,0.000283,0.000294,0.180709,-0.127392
...,...,...,...,...,...,...,...,...
7073,2025-06-27,543,0.906812,0.920749,0.893699,0.920749,0.057135,0.028464
7074,2025-06-30,546,0.921656,0.922893,0.903513,0.904626,0.028222,-0.017510
7075,2025-07-01,547,0.905080,0.914894,0.898606,0.909038,0.018814,0.004877
7076,2025-07-02,548,0.906028,0.913739,0.903266,0.906812,0.014806,-0.002449
7077,2025-07-03,549,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000

BRK-A Berkshire Hathaway
Rescate en ../Cofre/Valor/ BRK-A
../Cofre/Valor/BRK-A
<_io.BufferedReader name='../Cofre/Valor/BRK-A.pkl'>
Descarga de data

[*********************100%***********************]  1 of 1 completed

         Date  Close   High    Low   Open  Volume
0  1980-03-17  290.0  310.0  290.0  290.0   10000
1  1980-03-18  290.0  290.0  290.0  290.0       0
2  1980-03-19  290.0  310.0  290.0  290.0   20000
3  1980-03-20  290.0  290.0  290.0  290.0       0
4  1980-03-21  290.0  290.0  290.0  290.0       0

             Date     Close      High       Low      Open  Volume
11412  2025-06-26  729808.0  732541.0  726736.0  729200.0     400
11413  2025-06-27  730940.0  735000.0  727296.0  729163.0     400
11414  2025-06-30  728800.0  731999.0  726203.0  730204.0     400
11415  2025-07-01  733150.0  736555.0  726500.0  727546.0     500
11416  2025-07-02  720500.0  735310.0  718034.0  735310.0     500

2025-07-03

             Date     Close      High       Low      Open   Volume
0      1980-03-17     290.0     310.0     290.0     290.0  10000.0
1      1980-03-18     290.0     290.0     290.0     290.0      0.0
2      1980-03-19     290.0     310.0     290.0     290.0  20000.0
3      1980-03-20     290.0     290.0     290.0     290.0      0.0
4      1980-03-21     290.0     290.0     290.0     290.0      0.0
...           ...       ...       ...       ...       ...      ...
11413  2025-06-27  730940.0  735000.0  727296.0  729163.0    400.0
11414  2025-06-30  728800.0  731999.0  726203.0  730204.0    400.0
11415  2025-07-01  733150.0  736555.0  726500.0  727546.0    500.0
11416  2025-07-02  720500.0  735310.0  718034.0  735310.0    500.0
11417  2025-07-03       0.0       0.0       0.0       0.0      0.0

[11418 rows x 6 columns]

,Date,t,Open,High,Low,Close,Volume,rendimiento
0,1980-03-17,-15995,0.000357,0.000381,0.000357,0.000357,0.003649,NaN
1,1980-03-18,-15994,0.000357,0.000357,0.000357,0.000357,0.000000,0.000000
2,1980-03-19,-15993,0.000357,0.000381,0.000357,0.000357,0.007299,0.000000
3,1980-03-20,-15992,0.000357,0.000357,0.000357,0.000357,0.000000,0.000000
4,1980-03-21,-15991,0.000357,0.000357,0.000357,0.000357,0.000000,0.000000
...,...,...,...,...,...,...,...,...
11413,2025-06-27,543,0.897039,0.904220,0.894743,0.899226,0.000146,0.001551
11414,2025-06-30,546,0.898320,0.900528,0.893398,0.896593,0.000146,-0.002928
11415,2025-07-01,547,0.895050,0.906133,0.893763,0.901944,0.000182,0.005969
11416,2025-07-02,548,0.904602,0.904602,0.883348,0.886382,0.000182,-0.017254
11417,2025-07-03,549,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000

BTC-USD Bitcoin
Rescate en ../Cofre/Valor/ BTC-USD
../Cofre/Valor/BTC-USD
<_io.BufferedReader name='../Cofre/Valor/BTC-USD.pkl'>
Descarga de data

[*********************100%***********************]  1 of 1 completed

         Date       Close        High         Low        Open    Volume
0  2014-09-17  457.334015  468.174011  452.421997  465.864014  21056800
1  2014-09-18  424.440002  456.859985  413.104004  456.859985  34483200
2  2014-09-19  394.795990  427.834991  384.532013  424.102997  37919700
3  2014-09-20  408.903992  423.295990  389.882996  394.673004  36863600
4  2014-09-21  398.821014  412.425995  393.181000  408.084991  26580100

,Date,Close,High,Low,Open,Volume
3937,2025-06-28,107327.703125,107567.882812,106883.976562,107090.546875,30037708335
3938,2025-06-29,108385.570312,108526.304688,107230.109375,107327.820312,35534874438
3939,2025-06-30,107135.335938,108798.789062,106759.648438,108383.437500,42064804590
3940,2025-07-01,105698.281250,107550.679688,105270.226562,107144.382812,44110692247
3941,2025-07-02,108859.320312,109763.656250,105157.398438,105703.101562,56248657737

2025-07-03

,Date,Close,High,Low,Open,Volume
0,2014-09-17,457.334015,468.174011,452.421997,465.864014,2.105680e+07
1,2014-09-18,424.440002,456.859985,413.104004,456.859985,3.448320e+07
2,2014-09-19,394.795990,427.834991,384.532013,424.102997,3.791970e+07
3,2014-09-20,408.903992,423.295990,389.882996,394.673004,3.686360e+07
4,2014-09-21,398.821014,412.425995,393.181000,408.084991,2.658010e+07
...,...,...,...,...,...,...
3938,2025-06-29,108385.570312,108526.304688,107230.109375,107327.820312,3.553487e+10
3939,2025-06-30,107135.335938,108798.789062,106759.648438,108383.437500,4.206480e+10
3940,2025-07-01,105698.281250,107550.679688,105270.226562,107144.382812,4.411069e+10
3941,2025-07-02,108859.320312,109763.656250,105157.398438,105703.101562,5.624866e+10
3942,2025-07-03,0.000000,0.000000,0.000000,0.000000,0.000000e+00

,Date,t,Open,High,Low,Close,Volume,rendimiento
0,2014-09-17,-3393,0.004161,0.004181,0.004041,0.004084,0.000060,NaN
1,2014-09-18,-3392,0.004080,0.004080,0.003689,0.003791,0.000098,-0.071926
2,2014-09-19,-3391,0.003788,0.003821,0.003434,0.003526,0.000108,-0.069843
3,2014-09-20,-3390,0.003525,0.003780,0.003482,0.003652,0.000105,0.035735
4,2014-09-21,-3389,0.003645,0.003683,0.003511,0.003562,0.000076,-0.024659
...,...,...,...,...,...,...,...,...
3938,2025-06-29,545,0.958539,0.969243,0.957667,0.967986,0.101248,0.009856
3939,2025-06-30,546,0.967967,0.971677,0.953465,0.956820,0.119854,-0.011535
3940,2025-07-01,547,0.956901,0.960530,0.940163,0.943986,0.125683,-0.013413
3941,2025-07-02,548,0.944029,0.980294,0.939155,0.972217,0.160267,0.029906
3942,2025-07-03,549,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000

DOW DOW
Rescate en ../Cofre/Valor/ DOW
../Cofre/Valor/DOW
<_io.BufferedReader name='../Cofre/Valor/DOW.pkl'>
Descarga de data

[*********************100%***********************]  1 of 1 completed

         Date      Close       High        Low       Open   Volume
0  2019-03-20  36.016281  38.692190  35.799316  38.149776  2350800
1  2019-03-21  35.423237  36.160920  34.859127  36.153689  1764700
2  2019-03-22  35.148422  36.124769  34.830207  35.293067   844700
3  2019-03-25  35.546185  35.726989  34.714482  35.148412   440900
4  2019-03-26  35.329216  35.980114  34.844661  35.437700   504700

            Date  Close       High        Low   Open    Volume
1576  2025-06-26  27.15  27.549999  27.000000  27.10  13857800
1577  2025-06-27  27.00  27.760000  26.740000  27.40  18629400
1578  2025-06-30  26.48  26.920000  26.379999  26.90  11746900
1579  2025-07-01  27.83  28.447001  26.370001  26.43  21426600
1580  2025-07-02  28.73  28.730000  27.600000  28.15  14109800

2025-07-03

            Date      Close       High        Low       Open      Volume
0     2019-03-20  36.016281  38.692190  35.799316  38.149776   2350800.0
1     2019-03-21  35.423237  36.160920  34.859127  36.153689   1764700.0
2     2019-03-22  35.148422  36.124769  34.830207  35.293067    844700.0
3     2019-03-25  35.546185  35.726989  34.714482  35.148412    440900.0
4     2019-03-26  35.329216  35.980114  34.844661  35.437700    504700.0
...          ...        ...        ...        ...        ...         ...
1577  2025-06-27  27.000000  27.760000  26.740000  27.400000  18629400.0
1578  2025-06-30  26.480000  26.920000  26.379999  26.900000  11746900.0
1579  2025-07-01  27.830000  28.447001  26.370001  26.430000  21426600.0
1580  2025-07-02  28.730000  28.730000  27.600000  28.150000  14109800.0
1581  2025-07-03   0.000000   0.000000   0.000000   0.000000         0.0

[1582 rows x 6 columns]

,Date,t,Open,High,Low,Close,Volume,rendimiento
0,2019-03-20,-1748,0.624381,0.633259,0.585912,0.589463,0.104096,NaN
1,2019-03-21,-1747,0.591712,0.591830,0.570524,0.579757,0.078143,-0.016466
2,2019-03-22,-1746,0.577627,0.591239,0.570051,0.575259,0.037404,-0.007758
3,2019-03-25,-1743,0.575259,0.584728,0.568157,0.581769,0.019524,0.011317
4,2019-03-26,-1742,0.579994,0.588871,0.570288,0.578218,0.022349,-0.006104
...,...,...,...,...,...,...,...,...
1577,2025-06-27,543,0.448444,0.454336,0.437642,0.441897,0.824930,-0.005525
1578,2025-06-30,546,0.440261,0.440588,0.431750,0.433387,0.520166,-0.019259
1579,2025-07-01,547,0.432569,0.465580,0.431587,0.455482,0.948793,0.050982
1580,2025-07-02,548,0.460719,0.470212,0.451717,0.470212,0.624797,0.032339
1581,2025-07-03,549,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000

DVA DaVita Inc.
Rescate en ../Cofre/Valor/ DVA
../Cofre/Valor/DVA
<_io.BufferedReader name='../Cofre/Valor/DVA.pkl'>
Descarga de data

[*********************100%***********************]  1 of 1 completed

         Date  Close   High    Low   Open    Volume
0  1995-10-31  4.075  4.200  3.475  3.475  15479500
1  1995-11-01  3.900  3.950  3.875  3.900   3056500
2  1995-11-02  4.175  4.225  3.900  3.950   1185500
3  1995-11-03  4.000  4.225  3.850  4.175   1823500
4  1995-11-06  3.900  4.000  3.875  3.975    339500

            Date       Close        High         Low        Open   Volume
7461  2025-06-26  141.089996  143.009995  139.820007  141.259995   949300
7462  2025-06-27  141.669998  143.639999  140.300003  141.419998  1155000
7463  2025-06-30  142.449997  143.050003  140.710007  141.690002   984600
7464  2025-07-01  146.710007  147.449997  142.320007  142.429993  1234900
7465  2025-07-02  142.559998  145.990005  142.559998  145.660004   831000

2025-07-03

            Date       Close        High         Low        Open      Volume
0     1995-10-31    4.075000    4.200000    3.475000    3.475000  15479500.0
1     1995-11-01    3.900000    3.950000    3.875000    3.900000   3056500.0
2     1995-11-02    4.175000    4.225000    3.900000    3.950000   1185500.0
3     1995-11-03    4.000000    4.225000    3.850000    4.175000   1823500.0
4     1995-11-06    3.900000    4.000000    3.875000    3.975000    339500.0
...          ...         ...         ...         ...         ...         ...
7462  2025-06-27  141.669998  143.639999  140.300003  141.419998   1155000.0
7463  2025-06-30  142.449997  143.050003  140.710007  141.690002    984600.0
7464  2025-07-01  146.710007  147.449997  142.320007  142.429993   1234900.0
7465  2025-07-02  142.559998  145.990005  142.559998  145.660004    831000.0
7466  2025-07-03    0.000000    0.000000    0.000000    0.000000         0.0

[7467 rows x 6 columns]

,Date,t,Open,High,Low,Close,Volume,rendimiento
0,1995-10-31,-10289,0.019349,0.023385,0.019349,0.022689,0.275262,NaN
1,1995-11-01,-10288,0.021715,0.021993,0.021576,0.021715,0.054352,-0.042945
2,1995-11-02,-10287,0.021993,0.023524,0.021715,0.023246,0.021081,0.070513
3,1995-11-03,-10286,0.023246,0.023524,0.021437,0.022272,0.032426,-0.041916
4,1995-11-06,-10283,0.022133,0.022272,0.021576,0.021715,0.006037,-0.025000
...,...,...,...,...,...,...,...,...
7462,2025-06-27,543,0.787416,0.799777,0.781180,0.788808,0.020539,0.004111
7463,2025-06-30,546,0.788920,0.796492,0.783463,0.793151,0.017508,0.005506
7464,2025-07-01,547,0.793040,0.820991,0.792428,0.816871,0.021959,0.029905
7465,2025-07-02,548,0.811024,0.812862,0.793764,0.793764,0.014777,-0.028287
7466,2025-07-03,549,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000

IBM IBM
Rescate en ../Cofre/Valor/ IBM
../Cofre/Valor/IBM
<_io.BufferedReader name='../Cofre/Valor/IBM.pkl'>
Descarga de data

[*********************100%***********************]  1 of 1 completed

         Date     Close      High       Low      Open  Volume
0  1962-01-02  1.481690  1.498527  1.481690  1.498527  407940
1  1962-01-03  1.494642  1.494642  1.481690  1.481690  305955
2  1962-01-04  1.479748  1.494642  1.479100  1.494642  274575
3  1962-01-05  1.450606  1.477805  1.448016  1.477805  384405
4  1962-01-08  1.423408  1.449312  1.411752  1.449312  572685

             Date       Close        High         Low        Open   Volume
15977  2025-06-26  291.929993  292.910004  290.170013  291.799988  3621100
15978  2025-06-27  289.700012  293.119995  288.519989  292.970001  3562500
15979  2025-06-30  294.779999  294.809998  290.000000  290.929993  3495400
15980  2025-07-01  291.200012  295.109985  290.079987  294.549988  3272800
15981  2025-07-02  287.649994  290.190002  286.899994  290.000000  3257500

2025-07-03

             Date       Close        High         Low        Open     Volume
0      1962-01-02    1.481690    1.498527    1.481690    1.498527   407940.0
1      1962-01-03    1.494642    1.494642    1.481690    1.481690   305955.0
2      1962-01-04    1.479748    1.494642    1.479100    1.494642   274575.0
3      1962-01-05    1.450606    1.477805    1.448016    1.477805   384405.0
4      1962-01-08    1.423408    1.449312    1.411752    1.449312   572685.0
...           ...         ...         ...         ...         ...        ...
15978  2025-06-27  289.700012  293.119995  288.519989  292.970001  3562500.0
15979  2025-06-30  294.779999  294.809998  290.000000  290.929993  3495400.0
15980  2025-07-01  291.200012  295.109985  290.079987  294.549988  3272800.0
15981  2025-07-02  287.649994  290.190002  286.899994  290.000000  3257500.0
15982  2025-07-03    0.000000    0.000000    0.000000    0.000000        0.0

[15983 rows x 6 columns]

,Date,t,Open,High,Low,Close,Volume,rendimiento
0,1962-01-02,-22644,0.005060,0.005060,0.005003,0.005003,0.005616,NaN
1,1962-01-03,-22643,0.005003,0.005047,0.005003,0.005047,0.004212,0.008741
2,1962-01-04,-22642,0.005047,0.005047,0.004994,0.004996,0.003780,-0.009965
3,1962-01-05,-22641,0.004990,0.004990,0.004889,0.004898,0.005292,-0.019694
4,1962-01-08,-22638,0.004894,0.004894,0.004767,0.004806,0.007884,-0.018749
...,...,...,...,...,...,...,...,...
15978,2025-06-27,543,0.989229,0.989735,0.974203,0.978187,0.049044,-0.007639
15979,2025-06-30,546,0.982341,0.995442,0.979200,0.995340,0.048120,0.017535
15980,2025-07-01,547,0.994564,0.996455,0.979470,0.983252,0.045056,-0.012145
15981,2025-07-02,548,0.979200,0.979842,0.968733,0.971265,0.044845,-0.012191
15982,2025-07-03,549,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000

MCD MCD
Rescate en ../Cofre/Valor/ MCD
../Cofre/Valor/MCD
<_io.BufferedReader name='../Cofre/Valor/MCD.pkl'>
Descarga de data

[*********************100%***********************]  1 of 1 completed

         Date     Close      High       Low  Open   Volume
0  1966-07-05  0.113989  0.115730  0.113119   0.0   388800
1  1966-07-06  0.120081  0.120081  0.113119   0.0   692550
2  1966-07-07  0.115730  0.123126  0.114860   0.0  1858950
3  1966-07-08  0.117035  0.117035  0.113119   0.0  1239300
4  1966-07-11  0.116600  0.120081  0.115295   0.0   656100

             Date       Close        High         Low        Open   Volume
14842  2025-06-26  285.630005  286.790009  283.470001  285.950012  5354900
14843  2025-06-27  291.549988  292.190002  285.239990  286.010010  7422200
14844  2025-06-30  292.170013  293.579987  290.880005  290.880005  5054800
14845  2025-07-01  297.489990  299.649994  292.350006  292.500000  5121900
14846  2025-07-02  294.630005  298.079987  292.600006  298.079987  4021500

2025-07-03

             Date       Close        High         Low        Open     Volume
0      1966-07-05    0.113989    0.115730    0.113119    0.000000   388800.0
1      1966-07-06    0.120081    0.120081    0.113119    0.000000   692550.0
2      1966-07-07    0.115730    0.123126    0.114860    0.000000  1858950.0
3      1966-07-08    0.117035    0.117035    0.113119    0.000000  1239300.0
4      1966-07-11    0.116600    0.120081    0.115295    0.000000   656100.0
...           ...         ...         ...         ...         ...        ...
14843  2025-06-27  291.549988  292.190002  285.239990  286.010010  7422200.0
14844  2025-06-30  292.170013  293.579987  290.880005  290.880005  5054800.0
14845  2025-07-01  297.489990  299.649994  292.350006  292.500000  5121900.0
14846  2025-07-02  294.630005  298.079987  292.600006  298.079987  4021500.0
14847  2025-07-03    0.000000    0.000000    0.000000    0.000000        0.0

[14848 rows x 6 columns]

,Date,t,Open,High,Low,Close,Volume,rendimiento
0,1966-07-05,-20999,0.000000,0.000357,0.000349,0.000351,0.004470,NaN
1,1966-07-06,-20998,0.000000,0.000370,0.000349,0.000370,0.007962,0.053438
2,1966-07-07,-20997,0.000000,0.000379,0.000354,0.000357,0.021372,-0.036232
3,1966-07-08,-20996,0.000000,0.000361,0.000349,0.000361,0.014248,0.011277
4,1966-07-11,-20993,0.000000,0.000370,0.000355,0.000359,0.007543,-0.003718
...,...,...,...,...,...,...,...,...
14843,2025-06-27,543,0.881442,0.900488,0.879069,0.898515,0.085331,0.020726
14844,2025-06-30,546,0.896451,0.904771,0.896451,0.900426,0.058114,0.002127
14845,2025-07-01,547,0.901443,0.923478,0.900981,0.916822,0.058885,0.018208
14846,2025-07-02,548,0.918640,0.918640,0.901751,0.908008,0.046234,-0.009614
14847,2025-07-03,549,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000

MRK MRK
Rescate en ../Cofre/Valor/ MRK
../Cofre/Valor/MRK
<_io.BufferedReader name='../Cofre/Valor/MRK.pkl'>
Descarga de data

[*********************100%***********************]  1 of 1 completed

         Date     Close      High       Low  Open   Volume
0  1962-01-02  0.065403  0.065677  0.065038   0.0   633830
1  1962-01-03  0.062663  0.065403  0.062115   0.0  6564672
2  1962-01-04  0.062023  0.063211  0.061749   0.0  1199750
3  1962-01-05  0.059922  0.061749  0.059557   0.0   520646
4  1962-01-08  0.060105  0.060470  0.059740   0.0  1380845

             Date      Close       High        Low       Open    Volume
15977  2025-06-26  78.830002  80.250000  78.370003  79.839996  13760100
15978  2025-06-27  79.099998  79.540001  78.139999  79.059998  60202500
15979  2025-06-30  79.160004  79.389999  78.379997  79.250000  13895200
15980  2025-07-01  81.809998  83.070000  78.599998  78.959999  21800800
15981  2025-07-02  82.389999  82.809998  81.889999  82.059998  16052700

2025-07-03

             Date      Close       High        Low       Open      Volume
0      1962-01-02   0.065403   0.065677   0.065038   0.000000    633830.0
1      1962-01-03   0.062663   0.065403   0.062115   0.000000   6564672.0
2      1962-01-04   0.062023   0.063211   0.061749   0.000000   1199750.0
3      1962-01-05   0.059922   0.061749   0.059557   0.000000    520646.0
4      1962-01-08   0.060105   0.060470   0.059740   0.000000   1380845.0
...           ...        ...        ...        ...        ...         ...
15978  2025-06-27  79.099998  79.540001  78.139999  79.059998  60202500.0
15979  2025-06-30  79.160004  79.389999  78.379997  79.250000  13895200.0
15980  2025-07-01  81.809998  83.070000  78.599998  78.959999  21800800.0
15981  2025-07-02  82.389999  82.809998  81.889999  82.059998  16052700.0
15982  2025-07-03   0.000000   0.000000   0.000000   0.000000         0.0

[15983 rows x 6 columns]

,Date,t,Open,High,Low,Close,Volume,rendimiento
0,1962-01-02,-22644,0.000000,0.000504,0.000499,0.000502,0.004171,NaN
1,1962-01-03,-22643,0.000000,0.000502,0.000477,0.000481,0.043195,-0.041900
2,1962-01-04,-22642,0.000000,0.000485,0.000474,0.000476,0.007894,-0.010203
3,1962-01-05,-22641,0.000000,0.000474,0.000457,0.000460,0.003426,-0.033875
4,1962-01-08,-22638,0.000000,0.000464,0.000459,0.000462,0.009086,0.003047
...,...,...,...,...,...,...,...,...
15978,2025-06-27,543,0.607066,0.610752,0.600002,0.607373,0.396131,0.003425
15979,2025-06-30,546,0.608525,0.609600,0.601845,0.607834,0.091430,0.000759
15980,2025-07-01,547,0.606298,0.637857,0.603534,0.628182,0.143449,0.033476
15981,2025-07-02,548,0.630102,0.635861,0.628796,0.632636,0.105626,0.007090
15982,2025-07-03,549,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000

MSFT Microsoft
Rescate en ../Cofre/Valor/ MSFT
../Cofre/Valor/MSFT
<_io.BufferedReader name='../Cofre/Valor/MSFT.pkl'>
Descarga de data

[*********************100%***********************]  1 of 1 completed

         Date     Close      High       Low      Open      Volume
0  1986-03-13  0.059598  0.062259  0.054277  0.054277  1031788800
1  1986-03-14  0.061726  0.062791  0.059598  0.059598   308160000
2  1986-03-17  0.062791  0.063323  0.061726  0.061726   133171200
3  1986-03-18  0.061194  0.063323  0.060662  0.062791    67766400
4  1986-03-19  0.060130  0.061726  0.059598  0.061194    47894400

            Date       Close        High         Low        Open    Volume
9898  2025-06-26  497.450012  498.040009  492.809998  492.980011  21578900
9899  2025-06-27  495.940002  499.299988  493.029999  497.549988  34539200
9900  2025-06-30  497.410004  500.760010  495.329987  497.040009  28369000
9901  2025-07-01  492.049988  498.049988  490.980011  496.470001  19945400
9902  2025-07-02  491.089996  493.500000  488.700012  489.989990  16319600

2025-07-03

            Date       Close        High         Low        Open        Volume
0     1986-03-13    0.059598    0.062259    0.054277    0.054277  1.031789e+09
1     1986-03-14    0.061726    0.062791    0.059598    0.059598  3.081600e+08
2     1986-03-17    0.062791    0.063323    0.061726    0.061726  1.331712e+08
3     1986-03-18    0.061194    0.063323    0.060662    0.062791  6.776640e+07
4     1986-03-19    0.060130    0.061726    0.059598    0.061194  4.789440e+07
...          ...         ...         ...         ...         ...           ...
9899  2025-06-27  495.940002  499.299988  493.029999  497.549988  3.453920e+07
9900  2025-06-30  497.410004  500.760010  495.329987  497.040009  2.836900e+07
9901  2025-07-01  492.049988  498.049988  490.980011  496.470001  1.994540e+07
9902  2025-07-02  491.089996  493.500000  488.700012  489.989990  1.631960e+07
9903  2025-07-03    0.000000    0.000000    0.000000    0.000000  0.000000e+00

[9904 rows x 6 columns]

,Date,t,Open,High,Low,Close,Volume,rendimiento
0,1986-03-13,-13808,0.000108,0.000124,0.000108,0.000119,1.000000,NaN
1,1986-03-14,-13807,0.000119,0.000125,0.000119,0.000123,0.298666,0.035712
2,1986-03-17,-13804,0.000123,0.000126,0.000123,0.000125,0.129068,0.017250
3,1986-03-18,-13803,0.000125,0.000126,0.000121,0.000122,0.065679,-0.025432
4,1986-03-19,-13802,0.000122,0.000123,0.000119,0.000120,0.046419,-0.017390
...,...,...,...,...,...,...,...,...
9899,2025-06-27,543,0.993590,0.997084,0.984563,0.990375,0.033475,-0.003036
9900,2025-06-30,546,0.992571,1.000000,0.989156,0.993310,0.027495,0.002964
9901,2025-07-01,547,0.991433,0.994588,0.980470,0.982606,0.019331,-0.010776
9902,2025-07-02,548,0.978493,0.985502,0.975917,0.980689,0.015817,-0.001951
9903,2025-07-03,549,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000

NFLX Netflix, Inc.
Rescate en ../Cofre/Valor/ NFLX
../Cofre/Valor/NFLX
<_io.BufferedReader name='../Cofre/Valor/NFLX.pkl'>
Descarga de data

[*********************100%***********************]  1 of 1 completed

         Date     Close      High       Low      Open     Volume
0  2002-05-23  1.196429  1.242857  1.145714  1.156429  104790000
1  2002-05-24  1.210000  1.225000  1.197143  1.214286   11104800
2  2002-05-28  1.157143  1.232143  1.157143  1.213571    6609400
3  2002-05-29  1.103571  1.164286  1.085714  1.164286    6757800
4  2002-05-30  1.071429  1.107857  1.071429  1.107857   10154200

            Date        Close         High          Low         Open   Volume
5810  2025-06-26  1306.670044  1307.339966  1280.000000  1280.000000  2605900
5811  2025-06-27  1323.119995  1331.349976  1301.000000  1306.880005  4070900
5812  2025-06-30  1339.130005  1341.150024  1321.209961  1331.000000  3282900
5813  2025-07-01  1293.599976  1338.770020  1282.219971  1338.229980  4993600
5814  2025-07-02  1284.859985  1299.949951  1271.589966  1296.959961  3048800

2025-07-03

,Date,Close,High,Low,Open,Volume
0,2002-05-23,1.196429,1.242857,1.145714,1.156429,104790000.0
1,2002-05-24,1.210000,1.225000,1.197143,1.214286,11104800.0
2,2002-05-28,1.157143,1.232143,1.157143,1.213571,6609400.0
3,2002-05-29,1.103571,1.164286,1.085714,1.164286,6757800.0
4,2002-05-30,1.071429,1.107857,1.071429,1.107857,10154200.0
...,...,...,...,...,...,...
5811,2025-06-27,1323.119995,1331.349976,1301.000000,1306.880005,4070900.0
5812,2025-06-30,1339.130005,1341.150024,1321.209961,1331.000000,3282900.0
5813,2025-07-01,1293.599976,1338.770020,1282.219971,1338.229980,4993600.0
5814,2025-07-02,1284.859985,1299.949951,1271.589966,1296.959961,3048800.0
5815,2025-07-03,0.000000,0.000000,0.000000,0.000000,0.0

,Date,t,Open,High,Low,Close,Volume,rendimiento
0,2002-05-23,-7893,0.000862,0.000927,0.000854,0.000892,0.324012,NaN
1,2002-05-24,-7892,0.000905,0.000913,0.000893,0.000902,0.034336,0.011343
2,2002-05-28,-7888,0.000905,0.000919,0.000863,0.000863,0.020436,-0.043684
3,2002-05-29,-7887,0.000868,0.000868,0.000810,0.000823,0.020895,-0.046297
4,2002-05-30,-7886,0.000826,0.000826,0.000799,0.000799,0.031397,-0.029125
...,...,...,...,...,...,...,...,...
5811,2025-06-27,543,0.974447,0.992693,0.970063,0.986556,0.012587,0.012589
5812,2025-06-30,546,0.992432,1.000000,0.985132,0.998494,0.010151,0.012100
5813,2025-07-01,547,0.997823,0.998225,0.956060,0.964545,0.015440,-0.034000
5814,2025-07-02,548,0.967051,0.969280,0.948134,0.958029,0.009427,-0.006756
5815,2025-07-03,549,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000

NKE NKE
Rescate en ../Cofre/Valor/ NKE
../Cofre/Valor/NKE
<_io.BufferedReader name='../Cofre/Valor/NKE.pkl'>
Descarga de data

[*********************100%***********************]  1 of 1 completed

         Date     Close      High       Low      Open     Volume
0  1980-12-02  0.125007  0.127724  0.125007  0.125007  100710400
1  1980-12-03  0.122289  0.123648  0.122289  0.123648   25177600
2  1980-12-04  0.126366  0.127724  0.126366  0.126366   22694400
3  1980-12-05  0.119572  0.122289  0.119572  0.122289    7590400
4  1980-12-08  0.112778  0.114137  0.112778  0.114137    5414400

             Date      Close       High        Low       Open     Volume
11232  2025-06-26  62.540001  62.730000  60.820000  61.560001   39659800
11233  2025-06-27  72.040001  74.190002  69.690002  69.790001  117530300
11234  2025-06-30  71.040001  71.709999  70.059998  71.449997   31090400
11235  2025-07-01  73.410004  73.940002  71.830002  71.989998   27512900
11236  2025-07-02  76.389999  76.839996  73.000000  73.169998   36882300

2025-07-03

             Date      Close       High        Low       Open       Volume
0      1980-12-02   0.125007   0.127724   0.125007   0.125007  100710400.0
1      1980-12-03   0.122289   0.123648   0.122289   0.123648   25177600.0
2      1980-12-04   0.126366   0.127724   0.126366   0.126366   22694400.0
3      1980-12-05   0.119572   0.122289   0.119572   0.122289    7590400.0
4      1980-12-08   0.112778   0.114137   0.112778   0.114137    5414400.0
...           ...        ...        ...        ...        ...          ...
11233  2025-06-27  72.040001  74.190002  69.690002  69.790001  117530300.0
11234  2025-06-30  71.040001  71.709999  70.059998  71.449997   31090400.0
11235  2025-07-01  73.410004  73.940002  71.830002  71.989998   27512900.0
11236  2025-07-02  76.389999  76.839996  73.000000  73.169998   36882300.0
11237  2025-07-03   0.000000   0.000000   0.000000   0.000000          0.0

[11238 rows x 6 columns]

,Date,t,Open,High,Low,Close,Volume,rendimiento
0,1980-12-02,-15735,0.000737,0.000753,0.000737,0.000737,0.639652,NaN
1,1980-12-03,-15734,0.000729,0.000729,0.000721,0.000721,0.159913,-0.021743
2,1980-12-04,-15733,0.000745,0.000753,0.000745,0.000745,0.144141,0.033337
3,1980-12-05,-15732,0.000721,0.000721,0.000705,0.000705,0.048210,-0.053766
4,1980-12-08,-15729,0.000673,0.000673,0.000665,0.000665,0.034389,-0.056820
...,...,...,...,...,...,...,...,...
11233,2025-06-27,543,0.411294,0.437224,0.410704,0.424554,0.746482,0.151903
11234,2025-06-30,546,0.421077,0.422609,0.412885,0.418660,0.197468,-0.013881
11235,2025-07-01,547,0.424259,0.435751,0.423316,0.432628,0.174745,0.033362
11236,2025-07-02,548,0.431213,0.452842,0.430211,0.450190,0.234254,0.040594
11237,2025-07-03,549,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000

SMCI Super Micro Computer, Inc.
Rescate en ../Cofre/Valor/ SMCI
../Cofre/Valor/SMCI
<_io.BufferedReader name='../Cofre/Valor/SMCI.pkl'>
Descarga de data

[*********************100%***********************]  1 of 1 completed

         Date  Close   High    Low   Open    Volume
0  2007-03-29  0.876  0.931  0.866  0.885  60798000
1  2007-03-30  0.899  0.900  0.855  0.883   4195000
2  2007-04-02  1.038  1.059  0.899  0.900   7491000
3  2007-04-03  1.058  1.166  1.040  1.070   8357000
4  2007-04-04  1.016  1.099  1.003  1.040   3095000

            Date      Close       High        Low       Open    Volume
4590  2025-06-26  49.270000  49.520000  46.070000  47.060001  72397600
4591  2025-06-27  47.580002  49.970001  46.860001  49.480000  53757300
4592  2025-06-30  49.009998  50.549999  48.230000  48.700001  49238000
4593  2025-07-01  47.200001  48.669998  46.369999  48.240002  42243100
4594  2025-07-02  48.740002  48.880001  47.070000  47.189999  27631900

2025-07-03

            Date      Close       High        Low       Open      Volume
0     2007-03-29   0.876000   0.931000   0.866000   0.885000  60798000.0
1     2007-03-30   0.899000   0.900000   0.855000   0.883000   4195000.0
2     2007-04-02   1.038000   1.059000   0.899000   0.900000   7491000.0
3     2007-04-03   1.058000   1.166000   1.040000   1.070000   8357000.0
4     2007-04-04   1.016000   1.099000   1.003000   1.040000   3095000.0
...          ...        ...        ...        ...        ...         ...
4591  2025-06-27  47.580002  49.970001  46.860001  49.480000  53757300.0
4592  2025-06-30  49.009998  50.549999  48.230000  48.700001  49238000.0
4593  2025-07-01  47.200001  48.669998  46.369999  48.240002  42243100.0
4594  2025-07-02  48.740002  48.880001  47.070000  47.189999  27631900.0
4595  2025-07-03   0.000000   0.000000   0.000000   0.000000         0.0

[4596 rows x 6 columns]

,Date,t,Open,High,Low,Close,Volume,rendimiento
0,2007-03-29,-6122,0.007201,0.007575,0.007046,0.007128,0.164437,NaN
1,2007-03-30,-6121,0.007185,0.007323,0.006957,0.007315,0.011346,0.026256
2,2007-04-02,-6118,0.007323,0.008617,0.007315,0.008446,0.020260,0.154616
3,2007-04-03,-6117,0.008706,0.009487,0.008462,0.008609,0.022603,0.019268
4,2007-04-04,-6116,0.008462,0.008942,0.008161,0.008267,0.008371,-0.039697
...,...,...,...,...,...,...,...,...
4591,2025-06-27,543,0.402604,0.406591,0.381286,0.387144,0.145394,-0.034301
4592,2025-06-30,546,0.396257,0.411310,0.392433,0.398779,0.133171,0.030055
4593,2025-07-01,547,0.392514,0.396013,0.377299,0.384052,0.114252,-0.036931
4594,2025-07-02,548,0.383971,0.397722,0.382994,0.396583,0.074734,0.032627
4595,2025-07-03,549,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000

TSLA Tesla
Rescate en ../Cofre/Valor/ TSLA
../Cofre/Valor/TSLA
<_io.BufferedReader name='../Cofre/Valor/TSLA.pkl'>
Descarga de data

[*********************100%***********************]  1 of 1 completed

         Date     Close      High       Low      Open     Volume
0  2010-06-29  1.592667  1.666667  1.169333  1.266667  281494500
1  2010-06-30  1.588667  2.028000  1.553333  1.719333  257806500
2  2010-07-01  1.464000  1.728000  1.351333  1.666667  123282000
3  2010-07-02  1.280000  1.540000  1.247333  1.533333   77097000
4  2010-07-06  1.074000  1.333333  1.055333  1.333333  103003500

            Date       Close        High         Low        Open     Volume
3771  2025-06-26  325.779999  331.049988  323.609985  324.609985   80440900
3772  2025-06-27  323.630005  329.339996  317.500000  324.510010   89067000
3773  2025-06-30  317.660004  325.579987  316.600006  319.899994   76695100
3774  2025-07-01  300.709991  305.890015  293.209991  298.459991  145085700
3775  2025-07-02  315.649994  316.829987  303.820007  312.630005  119191500

2025-07-03

            Date       Close        High         Low        Open       Volume
0     2010-06-29    1.592667    1.666667    1.169333    1.266667  281494500.0
1     2010-06-30    1.588667    2.028000    1.553333    1.719333  257806500.0
2     2010-07-01    1.464000    1.728000    1.351333    1.666667  123282000.0
3     2010-07-02    1.280000    1.540000    1.247333    1.533333   77097000.0
4     2010-07-06    1.074000    1.333333    1.055333    1.333333  103003500.0
...          ...         ...         ...         ...         ...          ...
3772  2025-06-27  323.630005  329.339996  317.500000  324.510010   89067000.0
3773  2025-06-30  317.660004  325.579987  316.600006  319.899994   76695100.0
3774  2025-07-01  300.709991  305.890015  293.209991  298.459991  145085700.0
3775  2025-07-02  315.649994  316.829987  303.820007  312.630005  119191500.0
3776  2025-07-03    0.000000    0.000000    0.000000    0.000000          0.0

[3777 rows x 6 columns]

,Date,t,Open,High,Low,Close,Volume,rendimiento
0,2010-06-29,-4934,0.002593,0.003412,0.002394,0.003260,0.307953,NaN
1,2010-06-30,-4933,0.003519,0.004151,0.003180,0.003252,0.282039,-0.002511
2,2010-07-01,-4932,0.003412,0.003537,0.002766,0.002997,0.134870,-0.078473
3,2010-07-02,-4931,0.003139,0.003152,0.002553,0.002620,0.084344,-0.125683
4,2010-07-06,-4927,0.002729,0.002729,0.002160,0.002198,0.112685,-0.160937
...,...,...,...,...,...,...,...,...
3772,2025-06-27,543,0.664244,0.674131,0.649896,0.662443,0.097439,-0.006600
3773,2025-06-30,546,0.654808,0.666435,0.648053,0.650223,0.083904,-0.018447
3774,2025-07-01,547,0.610922,0.626131,0.600176,0.615528,0.158723,-0.053359
3775,2025-07-02,548,0.639927,0.648524,0.621894,0.646109,0.130395,0.049682
3776,2025-07-03,549,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000

WMT Walmart
Rescate en ../Cofre/Valor/ WMT
../Cofre/Valor/WMT
<_io.BufferedReader name='../Cofre/Valor/WMT.pkl'>
Descarga de data

[*********************100%***********************]  1 of 1 completed

         Date     Close      High       Low      Open   Volume
0  1972-08-25  0.011579  0.011623  0.011404  0.011404  7526400
1  1972-08-28  0.011535  0.011667  0.011535  0.011579  2918400
2  1972-08-29  0.011404  0.011491  0.011404  0.011491  5836800
3  1972-08-30  0.011404  0.011404  0.011316  0.011404  1228800
4  1972-08-31  0.011228  0.011316  0.011228  0.011316  2611200

             Date      Close       High        Low       Open    Volume
13318  2025-06-26  96.019997  97.339996  95.919998  96.900002  19361400
13319  2025-06-27  97.269997  97.760002  96.160004  96.320000  31431900
13320  2025-06-30  97.779999  98.139999  96.309998  97.230003  17803000
13321  2025-07-01  98.239998  99.190002  97.419998  97.599998  15635800
13322  2025-07-02  97.610001  98.379997  97.059998  98.129997  12502000

2025-07-03

             Date      Close       High        Low       Open      Volume
0      1972-08-25   0.011579   0.011623   0.011404   0.011404   7526400.0
1      1972-08-28   0.011535   0.011667   0.011535   0.011579   2918400.0
2      1972-08-29   0.011404   0.011491   0.011404   0.011491   5836800.0
3      1972-08-30   0.011404   0.011404   0.011316   0.011404   1228800.0
4      1972-08-31   0.011228   0.011316   0.011228   0.011316   2611200.0
...           ...        ...        ...        ...        ...         ...
13319  2025-06-27  97.269997  97.760002  96.160004  96.320000  31431900.0
13320  2025-06-30  97.779999  98.139999  96.309998  97.230003  17803000.0
13321  2025-07-01  98.239998  99.190002  97.419998  97.599998  15635800.0
13322  2025-07-02  97.610001  98.379997  97.059998  98.129997  12502000.0
13323  2025-07-03   0.000000   0.000000   0.000000   0.000000         0.0

[13324 rows x 6 columns]

,Date,t,Open,High,Low,Close,Volume,rendimiento
0,1972-08-25,-18756,0.000109,0.000111,0.000109,0.000111,0.019030,NaN
1,1972-08-28,-18753,0.000111,0.000111,0.000110,0.000110,0.007379,-0.003770
2,1972-08-29,-18752,0.000110,0.000110,0.000109,0.000109,0.014758,-0.011400
3,1972-08-30,-18751,0.000109,0.000109,0.000108,0.000109,0.003107,0.000000
4,1972-08-31,-18750,0.000108,0.000108,0.000107,0.000107,0.006602,-0.015408
...,...,...,...,...,...,...,...,...
13319,2025-06-27,543,0.919449,0.933195,0.917922,0.928518,0.079474,0.013018
13320,2025-06-30,546,0.928136,0.936823,0.919354,0.933386,0.045014,0.005243
13321,2025-07-01,547,0.931668,0.946846,0.929950,0.937777,0.039534,0.004704
13322,2025-07-02,548,0.936727,0.939114,0.926513,0.931763,0.031611,-0.006413
13323,2025-07-03,549,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000

# Módulo feed

In [13]:
# input: df (self.adj_data)
#        configuraciones
#        módulo: que genera cada una de las POF (Portion of food)

# output: df_output de la forma: DATE | NAME | X


#df_data = valor.adj_data
#df_data

## Fibonacci

In [14]:
from Clase_Valor_240902 import generate_fibonacci

## FIBONACCI
name = 'Fibonacci'

#iteradores para este POF
lista_n_datos_fibonacci = [20, 50, 80, 100, 150, 200, 300] # periodos hacia atrás
modos_vela = ['cuerpo', 'sombra']

continuar_si_hay_menos = True # Si no hay suficientes datos, se continua con el siguiente y no se considera el registro (ej, si se pide Fibo 50 y solo hay 40 datos, entonces no aparece el registro)
configuraciones = {'diccionario_combinaciones': {'n_datos': lista_n_datos_fibonacci, 'modo_vela': modos_vela}, 'iteradores': ['n_datos', 'modo_vela'], 'incluir_dates_en_iterar': False, 'df_explicito': pd.DataFrame(), 'continuar_si_hay_menos': continuar_si_hay_menos}

modulo = generate_fibonacci
    
for i in range(len(df_activos)):
    simbolo, nombre = df_activos.loc[i]
    print(f'{i + 1} / {len(df_activos)}', simbolo, nombre)
    valor = Valor(simbolo, nombre, cofre, saving_step, output = output) # Si no existe el objeto, se crea
    valor.crear_POF(name, configuraciones, modulo)

1 / 15 AAPL Apple Inc.
Rescate en ../Cofre/Valor/ AAPL
../Cofre/Valor/AAPL
<_io.BufferedReader name='../Cofre/Valor/AAPL.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

        Date    t
0 2025-07-03  549

 14%|█▍        | 2/14 [00:00<00:02,  4.22it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 21%|██▏       | 3/14 [00:00<00:02,  4.19it/s]

        Date    t
0 2025-07-03  549

 36%|███▌      | 5/14 [00:01<00:02,  4.47it/s]

        Date    t
0 2025-07-03  549

 43%|████▎     | 6/14 [00:01<00:01,  4.65it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 50%|█████     | 7/14 [00:01<00:01,  4.44it/s]

        Date    t
0 2025-07-03  549

 57%|█████▋    | 8/14 [00:01<00:01,  4.27it/s]

        Date    t
0 2025-07-03  549

 71%|███████▏  | 10/14 [00:02<00:00,  4.21it/s]

        Date    t
0 2025-07-03  549

 79%|███████▊  | 11/14 [00:02<00:00,  4.31it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 86%|████████▌ | 12/14 [00:02<00:00,  4.21it/s]

        Date    t
0 2025-07-03  549

 93%|█████████▎| 13/14 [00:03<00:00,  3.88it/s]

        Date    t
0 2025-07-03  549

100%|██████████| 14/14 [00:07<00:00,  1.85it/s]

GUARDAR





2 / 15 AMZN Amazon
Rescate en ../Cofre/Valor/ AMZN
../Cofre/Valor/AMZN
<_io.BufferedReader name='../Cofre/Valor/AMZN.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  7%|▋         | 1/14 [00:00<00:02,  4.66it/s]

        Date    t
0 2025-07-03  549

 14%|█▍        | 2/14 [00:00<00:02,  5.01it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 29%|██▊       | 4/14 [00:00<00:01,  5.58it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 43%|████▎     | 6/14 [00:01<00:01,  5.82it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 57%|█████▋    | 8/14 [00:01<00:01,  5.85it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 71%|███████▏  | 10/14 [00:01<00:00,  6.15it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 86%|████████▌ | 12/14 [00:02<00:00,  6.03it/s]

        Date    t
0 2025-07-03  549

 93%|█████████▎| 13/14 [00:02<00:00,  5.72it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

100%|██████████| 14/14 [00:05<00:00,  2.78it/s]

GUARDAR





3 / 15 BRK-A Berkshire Hathaway
Rescate en ../Cofre/Valor/ BRK-A
../Cofre/Valor/BRK-A
<_io.BufferedReader name='../Cofre/Valor/BRK-A.pkl'>

COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

        Date    t
0 2025-07-03  549

  7%|▋         | 1/14 [00:00<00:04,  3.10it/s]

        Date    t
0 2025-07-03  549

 14%|█▍        | 2/14 [00:00<00:03,  3.17it/s]

        Date    t
0 2025-07-03  549

 21%|██▏       | 3/14 [00:00<00:03,  3.20it/s]

        Date    t
0 2025-07-03  549

 29%|██▊       | 4/14 [00:01<00:03,  3.13it/s]

        Date    t
0 2025-07-03  549

 36%|███▌      | 5/14 [00:01<00:02,  3.12it/s]

        Date    t
0 2025-07-03  549

 43%|████▎     | 6/14 [00:01<00:02,  3.15it/s]

        Date    t
0 2025-07-03  549

 50%|█████     | 7/14 [00:02<00:02,  3.25it/s]

        Date    t
0 2025-07-03  549

 57%|█████▋    | 8/14 [00:02<00:01,  3.18it/s]

        Date    t
0 2025-07-03  549

 64%|██████▍   | 9/14 [00:02<00:01,  3.39it/s]

        Date    t
0 2025-07-03  549

 71%|███████▏  | 10/14 [00:03<00:01,  3.45it/s]

        Date    t
0 2025-07-03  549

 79%|███████▊  | 11/14 [00:03<00:00,  3.54it/s]

        Date    t
0 2025-07-03  549

 86%|████████▌ | 12/14 [00:03<00:00,  3.36it/s]

        Date    t
0 2025-07-03  549

 93%|█████████▎| 13/14 [00:03<00:00,  3.24it/s]

        Date    t
0 2025-07-03  549

100%|██████████| 14/14 [00:09<00:00,  1.49it/s]

GUARDAR





4 / 15 BTC-USD Bitcoin
Rescate en ../Cofre/Valor/ BTC-USD
../Cofre/Valor/BTC-USD
<_io.BufferedReader name='../Cofre/Valor/BTC-USD.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

        Date    t
0 2025-07-03  549

  7%|▋         | 1/14 [00:00<00:02,  5.41it/s]

        Date    t
0 2025-07-03  549

 14%|█▍        | 2/14 [00:00<00:02,  5.92it/s]

        Date    t
0 2025-07-03  549

 21%|██▏       | 3/14 [00:00<00:01,  6.71it/s]

        Date    t
0 2025-07-03  549

 29%|██▊       | 4/14 [00:00<00:01,  7.10it/s]

        Date    t
0 2025-07-03  549

 36%|███▌      | 5/14 [00:00<00:01,  7.05it/s]

        Date    t
0 2025-07-03  549

 43%|████▎     | 6/14 [00:00<00:01,  7.64it/s]

        Date    t
0 2025-07-03  549

 50%|█████     | 7/14 [00:00<00:00,  8.14it/s]

        Date    t
0 2025-07-03  549

 57%|█████▋    | 8/14 [00:01<00:00,  7.94it/s]

        Date    t
0 2025-07-03  549

 64%|██████▍   | 9/14 [00:01<00:00,  7.83it/s]

        Date    t
0 2025-07-03  549

 71%|███████▏  | 10/14 [00:01<00:00,  7.98it/s]

        Date    t
0 2025-07-03  549

 79%|███████▊  | 11/14 [00:01<00:00,  8.28it/s]

        Date    t
0 2025-07-03  549

 93%|█████████▎| 13/14 [00:01<00:00,  9.18it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

100%|██████████| 14/14 [00:03<00:00,  4.23it/s]

GUARDAR





5 / 15 DOW DOW
Rescate en ../Cofre/Valor/ DOW
../Cofre/Valor/DOW
<_io.BufferedReader name='../Cofre/Valor/DOW.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

        Date    t
0 2025-07-03  549

 14%|█▍        | 2/14 [00:00<00:00, 16.96it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 29%|██▊       | 4/14 [00:00<00:00, 18.43it/s]

        Date    t
0 2025-07-03  549

 43%|████▎     | 6/14 [00:00<00:00, 16.40it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 57%|█████▋    | 8/14 [00:00<00:00, 16.62it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 71%|███████▏  | 10/14 [00:00<00:00, 16.07it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 86%|████████▌ | 12/14 [00:00<00:00, 15.46it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

100%|██████████| 14/14 [00:01<00:00,  9.72it/s]

GUARDAR





6 / 15 DVA DaVita Inc.
Rescate en ../Cofre/Valor/ DVA
../Cofre/Valor/DVA
<_io.BufferedReader name='../Cofre/Valor/DVA.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  7%|▋         | 1/14 [00:00<00:02,  5.74it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 21%|██▏       | 3/14 [00:00<00:01,  6.11it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 36%|███▌      | 5/14 [00:00<00:01,  5.18it/s]

        Date    t
0 2025-07-03  549

 43%|████▎     | 6/14 [00:01<00:01,  5.33it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 57%|█████▋    | 8/14 [00:01<00:01,  5.04it/s]

        Date    t
0 2025-07-03  549

 64%|██████▍   | 9/14 [00:01<00:01,  4.92it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 79%|███████▊  | 11/14 [00:02<00:00,  4.73it/s]

        Date    t
0 2025-07-03  549

 86%|████████▌ | 12/14 [00:02<00:00,  4.65it/s]

        Date    t
0 2025-07-03  549

 93%|█████████▎| 13/14 [00:02<00:00,  4.78it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

100%|██████████| 14/14 [00:05<00:00,  2.51it/s]

GUARDAR





7 / 15 IBM IBM
Rescate en ../Cofre/Valor/ IBM
../Cofre/Valor/IBM
<_io.BufferedReader name='../Cofre/Valor/IBM.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

        Date    t
0 2025-07-03  549

  7%|▋         | 1/14 [00:00<00:05,  2.23it/s]

        Date    t
0 2025-07-03  549

 14%|█▍        | 2/14 [00:00<00:04,  2.44it/s]

        Date    t
0 2025-07-03  549

 21%|██▏       | 3/14 [00:01<00:04,  2.48it/s]

        Date    t
0 2025-07-03  549

 29%|██▊       | 4/14 [00:01<00:03,  2.72it/s]

        Date    t
0 2025-07-03  549

 36%|███▌      | 5/14 [00:01<00:03,  2.89it/s]

        Date    t
0 2025-07-03  549

 43%|████▎     | 6/14 [00:02<00:02,  2.77it/s]

        Date    t
0 2025-07-03  549

 50%|█████     | 7/14 [00:02<00:02,  2.85it/s]

        Date    t
0 2025-07-03  549

 57%|█████▋    | 8/14 [00:02<00:02,  2.93it/s]

        Date    t
0 2025-07-03  549

 64%|██████▍   | 9/14 [00:03<00:01,  3.01it/s]

        Date    t
0 2025-07-03  549

 71%|███████▏  | 10/14 [00:03<00:01,  3.08it/s]

        Date    t
0 2025-07-03  549

 79%|███████▊  | 11/14 [00:03<00:00,  3.08it/s]

        Date    t
0 2025-07-03  549

 86%|████████▌ | 12/14 [00:04<00:00,  3.02it/s]

        Date    t
0 2025-07-03  549

 93%|█████████▎| 13/14 [00:04<00:00,  3.00it/s]

        Date    t
0 2025-07-03  549

100%|██████████| 14/14 [00:10<00:00,  1.32it/s]

GUARDAR





8 / 15 MCD MCD
Rescate en ../Cofre/Valor/ MCD
../Cofre/Valor/MCD
<_io.BufferedReader name='../Cofre/Valor/MCD.pkl'>

COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

        Date    t
0 2025-07-03  549

  7%|▋         | 1/14 [00:00<00:04,  3.13it/s]

        Date    t
0 2025-07-03  549

 14%|█▍        | 2/14 [00:00<00:03,  3.37it/s]

        Date    t
0 2025-07-03  549

 21%|██▏       | 3/14 [00:00<00:03,  3.04it/s]

        Date    t
0 2025-07-03  549

 29%|██▊       | 4/14 [00:01<00:03,  2.89it/s]

        Date    t
0 2025-07-03  549

 36%|███▌      | 5/14 [00:01<00:02,  3.12it/s]

        Date    t
0 2025-07-03  549

 43%|████▎     | 6/14 [00:01<00:02,  3.15it/s]

        Date    t
0 2025-07-03  549

 50%|█████     | 7/14 [00:02<00:02,  3.15it/s]

        Date    t
0 2025-07-03  549

 57%|█████▋    | 8/14 [00:02<00:01,  3.18it/s]

        Date    t
0 2025-07-03  549

 64%|██████▍   | 9/14 [00:02<00:01,  3.23it/s]

        Date    t
0 2025-07-03  549

 71%|███████▏  | 10/14 [00:03<00:01,  3.25it/s]

        Date    t
0 2025-07-03  549

 79%|███████▊  | 11/14 [00:03<00:00,  3.28it/s]

        Date    t
0 2025-07-03  549

 86%|████████▌ | 12/14 [00:03<00:00,  3.39it/s]

        Date    t
0 2025-07-03  549

 93%|█████████▎| 13/14 [00:04<00:00,  3.29it/s]

        Date    t
0 2025-07-03  549

100%|██████████| 14/14 [00:09<00:00,  1.50it/s]

GUARDAR





9 / 15 MRK MRK
Rescate en ../Cofre/Valor/ MRK
../Cofre/Valor/MRK
<_io.BufferedReader name='../Cofre/Valor/MRK.pkl'>

COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

        Date    t
0 2025-07-03  549

  7%|▋         | 1/14 [00:00<00:04,  3.13it/s]

        Date    t
0 2025-07-03  549

 14%|█▍        | 2/14 [00:00<00:03,  3.28it/s]

        Date    t
0 2025-07-03  549

 21%|██▏       | 3/14 [00:00<00:03,  2.94it/s]

        Date    t
0 2025-07-03  549

 29%|██▊       | 4/14 [00:01<00:03,  2.93it/s]

        Date    t
0 2025-07-03  549

 36%|███▌      | 5/14 [00:01<00:02,  3.06it/s]

        Date    t
0 2025-07-03  549

 43%|████▎     | 6/14 [00:01<00:02,  2.98it/s]

        Date    t
0 2025-07-03  549

 50%|█████     | 7/14 [00:02<00:02,  2.73it/s]

        Date    t
0 2025-07-03  549

 57%|█████▋    | 8/14 [00:02<00:02,  2.61it/s]

        Date    t
0 2025-07-03  549

 64%|██████▍   | 9/14 [00:03<00:01,  2.73it/s]

        Date    t
0 2025-07-03  549

 71%|███████▏  | 10/14 [00:03<00:01,  2.89it/s]

        Date    t
0 2025-07-03  549

 79%|███████▊  | 11/14 [00:03<00:00,  3.09it/s]

        Date    t
0 2025-07-03  549

 86%|████████▌ | 12/14 [00:04<00:00,  3.18it/s]

        Date    t
0 2025-07-03  549

 93%|█████████▎| 13/14 [00:04<00:00,  3.20it/s]

        Date    t
0 2025-07-03  549

100%|██████████| 14/14 [00:10<00:00,  1.40it/s]

GUARDAR





10 / 15 MSFT Microsoft
Rescate en ../Cofre/Valor/ MSFT
../Cofre/Valor/MSFT
<_io.BufferedReader name='../Cofre/Valor/MSFT.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  7%|▋         | 1/14 [00:00<00:02,  4.76it/s]

        Date    t
0 2025-07-03  549

 14%|█▍        | 2/14 [00:00<00:02,  4.84it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 21%|██▏       | 3/14 [00:00<00:02,  4.63it/s]

        Date    t
0 2025-07-03  549

 36%|███▌      | 5/14 [00:01<00:01,  4.56it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 50%|█████     | 7/14 [00:01<00:01,  4.80it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 64%|██████▍   | 9/14 [00:01<00:00,  5.01it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 79%|███████▊  | 11/14 [00:02<00:00,  5.32it/s]

        Date    t
0 2025-07-03  549

 86%|████████▌ | 12/14 [00:02<00:00,  5.36it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 93%|█████████▎| 13/14 [00:02<00:00,  5.36it/s]

        Date    t
0 2025-07-03  549

100%|██████████| 14/14 [00:05<00:00,  2.41it/s]

GUARDAR





11 / 15 NFLX Netflix, Inc.
Rescate en ../Cofre/Valor/ NFLX
../Cofre/Valor/NFLX
<_io.BufferedReader name='../Cofre/Valor/NFLX.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

        Date    t
0 2025-07-03  549

  7%|▋         | 1/14 [00:00<00:01,  8.35it/s]

        Date    t
0 2025-07-03  549

 14%|█▍        | 2/14 [00:00<00:01,  7.94it/s]

        Date    t
0 2025-07-03  549

 21%|██▏       | 3/14 [00:00<00:01,  7.52it/s]

        Date    t
0 2025-07-03  549

 29%|██▊       | 4/14 [00:00<00:01,  7.76it/s]

        Date    t
0 2025-07-03  549

 36%|███▌      | 5/14 [00:00<00:01,  8.05it/s]

        Date    t
0 2025-07-03  549

 50%|█████     | 7/14 [00:00<00:00,  8.93it/s]

        Date    t
0 2025-07-03  549

 57%|█████▋    | 8/14 [00:00<00:00,  8.98it/s]

        Date    t
0 2025-07-03  549

 64%|██████▍   | 9/14 [00:01<00:00,  9.23it/s]

        Date    t
0 2025-07-03  549

 71%|███████▏  | 10/14 [00:01<00:00,  9.29it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 79%|███████▊  | 11/14 [00:01<00:00,  9.13it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 93%|█████████▎| 13/14 [00:01<00:00,  9.33it/s]

        Date    t
0 2025-07-03  549

100%|██████████| 14/14 [00:03<00:00,  3.99it/s]

GUARDAR





12 / 15 NKE NKE
Rescate en ../Cofre/Valor/ NKE
../Cofre/Valor/NKE
<_io.BufferedReader name='../Cofre/Valor/NKE.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  7%|▋         | 1/14 [00:00<00:02,  5.56it/s]

        Date    t
0 2025-07-03  549

 14%|█▍        | 2/14 [00:00<00:02,  5.28it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 29%|██▊       | 4/14 [00:00<00:01,  5.42it/s]

        Date    t
0 2025-07-03  549

 36%|███▌      | 5/14 [00:00<00:01,  5.47it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 43%|████▎     | 6/14 [00:01<00:01,  5.50it/s]

        Date    t
0 2025-07-03  549

 57%|█████▋    | 8/14 [00:01<00:01,  4.94it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 71%|███████▏  | 10/14 [00:01<00:00,  4.65it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 79%|███████▊  | 11/14 [00:02<00:00,  4.43it/s]

        Date    t
0 2025-07-03  549

 86%|████████▌ | 12/14 [00:02<00:00,  4.10it/s]

        Date    t
0 2025-07-03  549

 93%|█████████▎| 13/14 [00:02<00:00,  4.08it/s]

        Date    t
0 2025-07-03  549

100%|██████████| 14/14 [00:06<00:00,  2.11it/s]

GUARDAR





13 / 15 SMCI Super Micro Computer, Inc.
Rescate en ../Cofre/Valor/ SMCI
../Cofre/Valor/SMCI
<_io.BufferedReader name='../Cofre/Valor/SMCI.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  7%|▋         | 1/14 [00:00<00:01,  9.28it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 29%|██▊       | 4/14 [00:00<00:01,  9.45it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 36%|███▌      | 5/14 [00:00<00:00,  9.09it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 57%|█████▋    | 8/14 [00:00<00:00,  9.55it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 64%|██████▍   | 9/14 [00:00<00:00,  9.34it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 93%|█████████▎| 13/14 [00:01<00:00, 10.41it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

100%|██████████| 14/14 [00:02<00:00,  4.75it/s]

GUARDAR





14 / 15 TSLA Tesla
Rescate en ../Cofre/Valor/ TSLA
../Cofre/Valor/TSLA
<_io.BufferedReader name='../Cofre/Valor/TSLA.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

 14%|█▍        | 2/14 [00:00<00:00, 12.54it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 29%|██▊       | 4/14 [00:00<00:00, 12.33it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 57%|█████▋    | 8/14 [00:00<00:00, 11.15it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 71%|███████▏  | 10/14 [00:00<00:00, 10.67it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

 86%|████████▌ | 12/14 [00:01<00:00, 11.01it/s]

        Date    t
0 2025-07-03  549
        Date    t
0 2025-07-03  549

100%|██████████| 14/14 [00:02<00:00,  5.61it/s]

GUARDAR





15 / 15 WMT Walmart
Rescate en ../Cofre/Valor/ WMT
../Cofre/Valor/WMT
<_io.BufferedReader name='../Cofre/Valor/WMT.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

        Date    t
0 2025-07-03  549

  7%|▋         | 1/14 [00:00<00:03,  3.58it/s]

        Date    t
0 2025-07-03  549

 14%|█▍        | 2/14 [00:00<00:03,  3.36it/s]

        Date    t
0 2025-07-03  549

 21%|██▏       | 3/14 [00:00<00:03,  3.51it/s]

        Date    t
0 2025-07-03  549

 29%|██▊       | 4/14 [00:01<00:02,  3.61it/s]

        Date    t
0 2025-07-03  549

 36%|███▌      | 5/14 [00:01<00:02,  3.48it/s]

        Date    t
0 2025-07-03  549

 43%|████▎     | 6/14 [00:01<00:02,  3.65it/s]

        Date    t
0 2025-07-03  549

 50%|█████     | 7/14 [00:01<00:01,  3.68it/s]

        Date    t
0 2025-07-03  549

 57%|█████▋    | 8/14 [00:02<00:01,  3.49it/s]

        Date    t
0 2025-07-03  549

 64%|██████▍   | 9/14 [00:02<00:01,  3.57it/s]

        Date    t
0 2025-07-03  549

 71%|███████▏  | 10/14 [00:02<00:01,  3.63it/s]

        Date    t
0 2025-07-03  549

 79%|███████▊  | 11/14 [00:03<00:00,  3.68it/s]

        Date    t
0 2025-07-03  549

 86%|████████▌ | 12/14 [00:03<00:00,  3.51it/s]

        Date    t
0 2025-07-03  549

 93%|█████████▎| 13/14 [00:03<00:00,  3.51it/s]

        Date    t
0 2025-07-03  549

100%|██████████| 14/14 [00:08<00:00,  1.61it/s]

GUARDAR

## Media Móvil

In [15]:
from Clase_Valor_240902 import generate_media_movil

name = 'Media_Movil'

#iteradores para este POF
lista_n_datos_media_movil = [3, 4, 5, 10, 20, 30, 50, 80, 100, 120, 150, 200, 250, 300] # periodos hacia atrás
campos_media_movil = ['Close', 'rendimiento']

continuar_si_hay_menos = True

#configuraciones = {'diccionario_combinaciones': {'n_datos': lista_n_datos_fibonacci, 'modo_vela': modos_vela}, 'iteradores': ['n_datos', 'modo_vela'], 'incluir_dates_en_iterar': False, 'df_explicito': pd.DataFrame(), 'continuar_si_hay_menos': continuar_si_hay_menos}
configuraciones = {'diccionario_combinaciones': {'n_datos': lista_n_datos_media_movil, 'campo': campos_media_movil}, 'iteradores': ['n_datos', 'campo'], 'incluir_dates_en_iterar': False, 'df_explicito': pd.DataFrame(), 'continuar_si_hay_menos': continuar_si_hay_menos}

modulo = generate_media_movil

for i in range(len(df_activos)):
    simbolo, nombre = df_activos.loc[i]
    print(f'{i + 1} / {len(df_activos)}', simbolo, nombre)
    valor = Valor(simbolo, nombre, cofre, saving_step, output = output) # Si no existe el objeto, se crea
    
    #display(valor.adj_data)
    valor.crear_POF(name, configuraciones, modulo)

1 / 15 AAPL Apple Inc.
Rescate en ../Cofre/Valor/ AAPL
../Cofre/Valor/AAPL
<_io.BufferedReader name='../Cofre/Valor/AAPL.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

100%|██████████| 28/28 [00:11<00:00,  2.51it/s]

GUARDAR





2 / 15 AMZN Amazon
Rescate en ../Cofre/Valor/ AMZN
../Cofre/Valor/AMZN
<_io.BufferedReader name='../Cofre/Valor/AMZN.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 28/28 [00:07<00:00,  3.62it/s]

GUARDAR





3 / 15 BRK-A Berkshire Hathaway
Rescate en ../Cofre/Valor/ BRK-A
../Cofre/Valor/BRK-A
<_io.BufferedReader name='../Cofre/Valor/BRK-A.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 28/28 [00:10<00:00,  2.62it/s]

GUARDAR





4 / 15 BTC-USD Bitcoin
Rescate en ../Cofre/Valor/ BTC-USD
../Cofre/Valor/BTC-USD
<_io.BufferedReader name='../Cofre/Valor/BTC-USD.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 28/28 [00:03<00:00,  7.53it/s]

GUARDAR





5 / 15 DOW DOW
Rescate en ../Cofre/Valor/ DOW
../Cofre/Valor/DOW
<_io.BufferedReader name='../Cofre/Valor/DOW.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

100%|██████████| 28/28 [00:01<00:00, 17.72it/s]

GUARDAR





6 / 15 DVA DaVita Inc.
Rescate en ../Cofre/Valor/ DVA
../Cofre/Valor/DVA
<_io.BufferedReader name='../Cofre/Valor/DVA.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 28/28 [00:06<00:00,  4.35it/s]

GUARDAR





7 / 15 IBM IBM
Rescate en ../Cofre/Valor/ IBM
../Cofre/Valor/IBM
<_io.BufferedReader name='../Cofre/Valor/IBM.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 28/28 [00:12<00:00,  2.16it/s]

GUARDAR





8 / 15 MCD MCD
Rescate en ../Cofre/Valor/ MCD
../Cofre/Valor/MCD
<_io.BufferedReader name='../Cofre/Valor/MCD.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 28/28 [00:12<00:00,  2.28it/s]

GUARDAR





9 / 15 MRK MRK
Rescate en ../Cofre/Valor/ MRK
../Cofre/Valor/MRK
<_io.BufferedReader name='../Cofre/Valor/MRK.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 28/28 [00:12<00:00,  2.16it/s]

GUARDAR





10 / 15 MSFT Microsoft
Rescate en ../Cofre/Valor/ MSFT
../Cofre/Valor/MSFT
<_io.BufferedReader name='../Cofre/Valor/MSFT.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 28/28 [00:08<00:00,  3.29it/s]

GUARDAR





11 / 15 NFLX Netflix, Inc.
Rescate en ../Cofre/Valor/ NFLX
../Cofre/Valor/NFLX
<_io.BufferedReader name='../Cofre/Valor/NFLX.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 28/28 [00:04<00:00,  5.68it/s]

GUARDAR





12 / 15 NKE NKE
Rescate en ../Cofre/Valor/ NKE
../Cofre/Valor/NKE
<_io.BufferedReader name='../Cofre/Valor/NKE.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 28/28 [00:08<00:00,  3.23it/s]

GUARDAR





13 / 15 SMCI Super Micro Computer, Inc.
Rescate en ../Cofre/Valor/ SMCI
../Cofre/Valor/SMCI
<_io.BufferedReader name='../Cofre/Valor/SMCI.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 28/28 [00:03<00:00,  7.10it/s]

GUARDAR





14 / 15 TSLA Tesla
Rescate en ../Cofre/Valor/ TSLA
../Cofre/Valor/TSLA
<_io.BufferedReader name='../Cofre/Valor/TSLA.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

100%|██████████| 28/28 [00:03<00:00,  8.02it/s]

GUARDAR





15 / 15 WMT Walmart
Rescate en ../Cofre/Valor/ WMT
../Cofre/Valor/WMT
<_io.BufferedReader name='../Cofre/Valor/WMT.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 28/28 [00:11<00:00,  2.43it/s]

GUARDAR

## Suavizamiento Exponencial

In [16]:
from Clase_Valor_240902 import generate_suavexp

name = 'Suavizamiento_Exponencial'

#iteradores para este POF
lista_alpha = [0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7] # Para suavizamiento exponencial
campos_suavexp = ['Close', 'rendimiento']

continuar_si_hay_menos = True

configuraciones = {'diccionario_combinaciones': {'alpha': lista_alpha, 'campo': campos_suavexp}, 'iteradores': ['alpha', 'campo'], 'incluir_dates_en_iterar': False, 'df_explicito': pd.DataFrame(), 'continuar_si_hay_menos': continuar_si_hay_menos}

modulo = generate_suavexp

for i in range(len(df_activos)):
    simbolo, nombre = df_activos.loc[i]
    print(f'{i + 1} / {len(df_activos)}', simbolo, nombre)
    valor = Valor(simbolo, nombre, cofre, saving_step, output = output) # Si no existe el objeto, se crea
    
    #display(valor.adj_data)
    valor.crear_POF(name, configuraciones, modulo)

1 / 15 AAPL Apple Inc.
Rescate en ../Cofre/Valor/ AAPL
../Cofre/Valor/AAPL
<_io.BufferedReader name='../Cofre/Valor/AAPL.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

100%|██████████| 16/16 [00:07<00:00,  2.28it/s]

GUARDAR





2 / 15 AMZN Amazon
Rescate en ../Cofre/Valor/ AMZN
../Cofre/Valor/AMZN
<_io.BufferedReader name='../Cofre/Valor/AMZN.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 16/16 [00:04<00:00,  3.44it/s]

GUARDAR





3 / 15 BRK-A Berkshire Hathaway
Rescate en ../Cofre/Valor/ BRK-A
../Cofre/Valor/BRK-A
<_io.BufferedReader name='../Cofre/Valor/BRK-A.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 16/16 [00:07<00:00,  2.25it/s]

GUARDAR





4 / 15 BTC-USD Bitcoin
Rescate en ../Cofre/Valor/ BTC-USD
../Cofre/Valor/BTC-USD
<_io.BufferedReader name='../Cofre/Valor/BTC-USD.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 16/16 [00:02<00:00,  6.23it/s]

GUARDAR





5 / 15 DOW DOW
Rescate en ../Cofre/Valor/ DOW
../Cofre/Valor/DOW
<_io.BufferedReader name='../Cofre/Valor/DOW.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

100%|██████████| 16/16 [00:01<00:00, 14.05it/s]

GUARDAR





6 / 15 DVA DaVita Inc.
Rescate en ../Cofre/Valor/ DVA
../Cofre/Valor/DVA
<_io.BufferedReader name='../Cofre/Valor/DVA.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 16/16 [00:05<00:00,  3.14it/s]

GUARDAR





7 / 15 IBM IBM
Rescate en ../Cofre/Valor/ IBM
../Cofre/Valor/IBM
<_io.BufferedReader name='../Cofre/Valor/IBM.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 16/16 [00:10<00:00,  1.55it/s]

GUARDAR





8 / 15 MCD MCD
Rescate en ../Cofre/Valor/ MCD
../Cofre/Valor/MCD
<_io.BufferedReader name='../Cofre/Valor/MCD.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 16/16 [00:08<00:00,  1.80it/s]

GUARDAR





9 / 15 MRK MRK
Rescate en ../Cofre/Valor/ MRK
../Cofre/Valor/MRK
<_io.BufferedReader name='../Cofre/Valor/MRK.pkl'>
COMENTAR FUNCION!!!!

generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

100%|██████████| 16/16 [00:09<00:00,  1.69it/s]

GUARDAR





10 / 15 MSFT Microsoft
Rescate en ../Cofre/Valor/ MSFT
../Cofre/Valor/MSFT
<_io.BufferedReader name='../Cofre/Valor/MSFT.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 16/16 [00:06<00:00,  2.55it/s]

GUARDAR





11 / 15 NFLX Netflix, Inc.
Rescate en ../Cofre/Valor/ NFLX
../Cofre/Valor/NFLX
<_io.BufferedReader name='../Cofre/Valor/NFLX.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 16/16 [00:03<00:00,  4.43it/s]

GUARDAR





12 / 15 NKE NKE
Rescate en ../Cofre/Valor/ NKE
../Cofre/Valor/NKE
<_io.BufferedReader name='../Cofre/Valor/NKE.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 16/16 [00:06<00:00,  2.34it/s]

GUARDAR





13 / 15 SMCI Super Micro Computer, Inc.
Rescate en ../Cofre/Valor/ SMCI
../Cofre/Valor/SMCI
<_io.BufferedReader name='../Cofre/Valor/SMCI.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 16/16 [00:02<00:00,  5.51it/s]

GUARDAR





14 / 15 TSLA Tesla
Rescate en ../Cofre/Valor/ TSLA
../Cofre/Valor/TSLA
<_io.BufferedReader name='../Cofre/Valor/TSLA.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

100%|██████████| 16/16 [00:02<00:00,  6.61it/s]

GUARDAR





15 / 15 WMT Walmart
Rescate en ../Cofre/Valor/ WMT
../Cofre/Valor/WMT
<_io.BufferedReader name='../Cofre/Valor/WMT.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

100%|██████████| 16/16 [00:08<00:00,  1.84it/s]

GUARDAR

## Áreas (ver módulo areas)

In [17]:
sys.exit('Antes de seguir (con módulo Áreas), limpiar código FFNN_y_BusqInt_240610')

SystemExit: Antes de seguir (con módulo Áreas), limpiar código FFNN_y_BusqInt_240610

# Otros

In [ ]:
sys.exit('OK')

In [ ]:
# ANTIGUO
for i in range(len(df_activos)):
    simbolo, nombre = df_activos.loc[i]
    print(simbolo, nombre)
    
    valor = Valor(simbolo, nombre, cofre, output = True) # Si no existe el objeto, se crea
    
    valor.extraer_data()
    valor.ajustar_data()

    display(valor.adj_data.tail())

    #print('A')
    #valor.generar_figuras_all(lista_k, lista_figuras, saving_step = saving_step)
    print('B')
    valor.generar_fibonacci_all(lista_k, saving_step = saving_step)

    print('C')
    valor.generar_media_movil_all(lista_n, lista_campos, saving_step = saving_step)
    print('D')
    valor.generar_media_movil_multiplicativa_all(lista_n, lista_campos, saving_step = saving_step)
    print('E')
    valor.generar_suavizamiento_exponencial_all(lista_alpha, lista_campos, saving_step = saving_step)
    
    #print('C1: Buscar "Continuar aqui 240506"...clase red neuronal (método construir_matrices)')
    print('C2 Construir casos como: Calidad de una figura (páginas 10 & 11), dada la info obtenida en generar_figuras_all...agregar a raw_x')
    
    #print('F')
    #df_pl = valor.generar_polinomicas_all(lista_grados, lista_R, saving_step = saving_step)

    valor.generar_output_all(lista_R)
    
    valor.guardar()
    #sys.exit('Fin')
    
print('Proceso OK')

In [ ]:
sys.exit()

# Data

In [ ]:
df = valor.adj_data
df.tail()

In [ ]:
from finta import TA
TA?

In [ ]:
TA.BBANDS(df)

# TO DO

In [ ]:
#Convex Hull, algorítmo?. Partir de un punto convexo (P0), elegir el punto que tenga menor angulo entre el vector que comienza en el P0 y apunta hacia arriba y el vector que comienza en el P0 y apunta hacia el punto. Se elige el punto que tenga el menor ángulo. Se repite el proceso hasta que se llegue al punto de inicio. Se obtiene el convex hull. 
# Se puede hacer con scipy.spatial.ConvexHull