# Librerías y Módulos

In [ ]:
import sys

# Obtener la lista de kernels
kernels = !jupyter kernelspec list

# Mostrar la lista de kernels para referencia
print(kernels)

# Buscar si 'mi_entorno' está en la lista de kernels
kernel_name = "mi_entorno"
kernel_found = False

for line in kernels:
    if kernel_name in line:
        kernel_found = True
        break

# Comprueba si el kernel de ejecución es mi_entorno
if not kernel_found:
    print(f'Kernel debe ser: {kernel_name}')
    #sys.exit()

print(f'Kernel correcto: {kernel_name}')

## Librerías

In [ ]:
import pandas as pd
import sys

import warnings
warnings.filterwarnings("ignore")

In [ ]:
sys.path.insert(0, '')
from Clase_Valor_240902 import Valor
from Transversal import leer_activos, leer_parametros

In [ ]:
# Prueba de funcionamiento

import yfinance as yf
df = yf.download('AAPL')

df = df.reset_index()
df['Date'] = pd.to_datetime(df['Date'], format = '%Y-%m-%d').dt.date



#self.raw_data = self.raw_data_new.reset_index() # Se resetea el índice
#self.raw_data['Date'] = pd.to_datetime(self.raw_data['Date'], format = '%Y-%m-%d').dt.date # Traspaso a formato día
#self.ultima_fecha_data = self.raw_data['Date'].max() # Último día para el que existen los datos


df.columns = ['Date', 'Close', 'High', 'Low', 'Open', 'Volume']
df

# Parámetros

In [ ]:
reextraer_todo = True # Parámetro: SI es True, se vuelven a extraer todos los datos. Si es False, se extraen solo los valores que no estén actualizados hasta ayer
output = True

In [ ]:
carpeta_input, cofre, seguimiento, saving_step = leer_parametros()

# Lectura de activos

In [ ]:
df_activos = leer_activos(carpeta_input)
df_activos

# Ejecución

In [ ]:
#df_activos = df_activos.iloc[1:].reset_index(drop = True) # solo prueba
df_activos

In [ ]:
#df_activos = df_activos[df_activos['SIMBOLO'] == 'AMZN'].reset_index(drop = True)

#sys.exit('small batch. Eliminar')

In [ ]:
agregar_nuevo_dia = True # parámetro, subir

In [ ]:
# NUEVO
for i in range(len(df_activos)):
    simbolo, nombre = df_activos.loc[i]
    print(simbolo, nombre)
    valor = Valor(simbolo, nombre, cofre, saving_step, output = output) # Si no existe el objeto, se crea
    
    valor.extraer_data(reextraer_todo = reextraer_todo) # Extrae la data del valor correspondiente, solo si existen días nuevos
    valor.ajustar_data(agregar_nuevo_dia = agregar_nuevo_dia) # interpola en algunos casos (por ahora al menos, interpolar está desactivado), y estandariza la data (0, 1)
    
    valor.guardar()

# Módulo feed

In [ ]:
# input: df (self.adj_data)
#        configuraciones
#        módulo: que genera cada una de las POF (Portion of food)

# output: df_output de la forma: DATE | NAME | X


#df_data = valor.adj_data
#df_data

## Fibonacci

In [121]:
from Clase_Valor_240902 import generate_fibonacci

## FIBONACCI
name = 'Fibonacci'

#iteradores para este POF
lista_n_datos_fibonacci = [20, 50, 80, 100, 150, 200, 300] # periodos hacia atrás
modos_vela = ['cuerpo', 'sombra']

continuar_si_hay_menos = True # Si no hay suficientes datos, se continua con el siguiente y no se considera el registro (ej, si se pide Fibo 50 y solo hay 40 datos, entonces no aparece el registro)
configuraciones = {'diccionario_combinaciones': {'n_datos': lista_n_datos_fibonacci, 'modo_vela': modos_vela}, 'iteradores': ['n_datos', 'modo_vela'], 'incluir_dates_en_iterar': False, 'df_explicito': pd.DataFrame(), 'continuar_si_hay_menos': continuar_si_hay_menos}

modulo = generate_fibonacci
    
for i in range(len(df_activos)):
    simbolo, nombre = df_activos.loc[i]
    print(simbolo, nombre)
    valor = Valor(simbolo, nombre, cofre, saving_step, output = output) # Si no existe el objeto, se crea
    valor.crear_POF(name, configuraciones, modulo)

100%|██████████| 14/14 [00:08<00:00,  1.68it/s]

GUARDAR





TSLA Tesla
Rescate en ../Cofre/Valor/ TSLA
../Cofre/Valor/TSLA
<_io.BufferedReader name='../Cofre/Valor/TSLA.pkl'>
COMENTAR FUNCION!!!!
Lista date en crear POF
<DatetimeArray>
['2025-03-20 00:00:00', '2025-03-21 00:00:00', '2025-03-24 00:00:00',
 '2025-03-25 00:00:00', '2025-03-26 00:00:00', '2025-03-27 00:00:00',
 '2025-03-28 00:00:00', '2025-03-31 00:00:00', '2025-04-01 00:00:00',
 '2025-04-02 00:00:00']
Length: 10, dtype: datetime64[ns]
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

   n_datos modo_vela
0       20    cuerpo

  7%|▋         | 1/14 [00:00<00:01,  7.31it/s]

        Date    t
0 2025-04-02  457

   n_datos modo_vela
0       20    sombra

        Date    t
0 2025-04-02  457

 14%|█▍        | 2/14 [00:00<00:01,  8.03it/s]

   n_datos modo_vela
0       50    cuerpo

        Date    t
0 2025-04-02  457

   n_datos modo_vela
0       50    sombra

 29%|██▊       | 4/14 [00:00<00:01,  9.97it/s]

        Date    t
0 2025-04-02  457

   n_datos modo_vela
0       80    cuerpo

        Date    t
0 2025-04-02  457

   n_datos modo_vela
0       80    sombra

        Date    t
0 2025-04-02  457

 43%|████▎     | 6/14 [00:00<00:00, 10.80it/s]

   n_datos modo_vela
0      100    cuerpo

        Date    t
0 2025-04-02  457

   n_datos modo_vela
0      100    sombra

        Date    t
0 2025-04-02  457

 57%|█████▋    | 8/14 [00:00<00:00, 11.51it/s]

   n_datos modo_vela
0      150    cuerpo

        Date    t
0 2025-04-02  457

   n_datos modo_vela
0      150    sombra

        Date    t
0 2025-04-02  457

 71%|███████▏  | 10/14 [00:00<00:00, 11.11it/s]

   n_datos modo_vela
0      200    cuerpo

        Date    t
0 2025-04-02  457

   n_datos modo_vela
0      200    sombra

        Date    t
0 2025-04-02  457

 86%|████████▌ | 12/14 [00:01<00:00, 10.88it/s]

   n_datos modo_vela
0      300    cuerpo

        Date    t
0 2025-04-02  457

   n_datos modo_vela
0      300    sombra

        Date    t
0 2025-04-02  457

100%|██████████| 14/14 [00:02<00:00,  6.19it/s]

GUARDAR





AMZN Amazon
Rescate en ../Cofre/Valor/ AMZN
../Cofre/Valor/AMZN
<_io.BufferedReader name='../Cofre/Valor/AMZN.pkl'>
COMENTAR FUNCION!!!!
Lista date en crear POF
<DatetimeArray>
['2025-03-20 00:00:00', '2025-03-21 00:00:00', '2025-03-24 00:00:00',
 '2025-03-25 00:00:00', '2025-03-26 00:00:00', '2025-03-27 00:00:00',
 '2025-03-28 00:00:00', '2025-03-31 00:00:00', '2025-04-01 00:00:00',
 '2025-04-02 00:00:00']
Length: 10, dtype: datetime64[ns]
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

   n_datos modo_vela
0       20    cuerpo

  7%|▋         | 1/14 [00:00<00:01,  8.21it/s]

        Date    t
0 2025-04-02  457

   n_datos modo_vela
0       20    sombra

        Date    t
0 2025-04-02  457

 14%|█▍        | 2/14 [00:00<00:01,  8.40it/s]

   n_datos modo_vela
0       50    cuerpo

        Date    t
0 2025-04-02  457

 21%|██▏       | 3/14 [00:00<00:01,  8.25it/s]

   n_datos modo_vela
0       50    sombra

        Date    t
0 2025-04-02  457

 29%|██▊       | 4/14 [00:00<00:01,  8.03it/s]

   n_datos modo_vela
0       80    cuerpo

        Date    t
0 2025-04-02  457

 36%|███▌      | 5/14 [00:00<00:01,  8.57it/s]

   n_datos modo_vela
0       80    sombra

 43%|████▎     | 6/14 [00:00<00:00,  8.85it/s]

        Date    t
0 2025-04-02  457

   n_datos modo_vela
0      100    cuerpo

        Date    t
0 2025-04-02  457

 50%|█████     | 7/14 [00:00<00:00,  8.91it/s]

   n_datos modo_vela
0      100    sombra

 57%|█████▋    | 8/14 [00:00<00:00,  9.00it/s]

        Date    t
0 2025-04-02  457

   n_datos modo_vela
0      150    cuerpo

        Date    t
0 2025-04-02  457

 64%|██████▍   | 9/14 [00:01<00:00,  8.67it/s]

   n_datos modo_vela
0      150    sombra

        Date    t
0 2025-04-02  457

 71%|███████▏  | 10/14 [00:01<00:00,  8.26it/s]

   n_datos modo_vela
0      200    cuerpo

        Date    t
0 2025-04-02  457

 79%|███████▊  | 11/14 [00:01<00:00,  8.34it/s]

   n_datos modo_vela
0      200    sombra

        Date    t
0 2025-04-02  457

 86%|████████▌ | 12/14 [00:01<00:00,  8.00it/s]

   n_datos modo_vela
0      300    cuerpo

        Date    t
0 2025-04-02  457

 93%|█████████▎| 13/14 [00:01<00:00,  7.43it/s]

   n_datos modo_vela
0      300    sombra

        Date    t
0 2025-04-02  457

100%|██████████| 14/14 [00:03<00:00,  3.87it/s]

GUARDAR





BRK-A Berkshire Hathaway
Rescate en ../Cofre/Valor/ BRK-A
../Cofre/Valor/BRK-A
<_io.BufferedReader name='../Cofre/Valor/BRK-A.pkl'>
COMENTAR FUNCION!!!!
Lista date en crear POF
<DatetimeArray>
['2025-03-20 00:00:00', '2025-03-21 00:00:00', '2025-03-24 00:00:00',
 '2025-03-25 00:00:00', '2025-03-26 00:00:00', '2025-03-27 00:00:00',
 '2025-03-28 00:00:00', '2025-03-31 00:00:00', '2025-04-01 00:00:00',
 '2025-04-02 00:00:00']
Length: 10, dtype: datetime64[ns]
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

   n_datos modo_vela
0       20    cuerpo

  7%|▋         | 1/14 [00:00<00:02,  4.90it/s]

        Date    t
0 2025-04-02  457

   n_datos modo_vela
0       20    sombra

 14%|█▍        | 2/14 [00:00<00:02,  5.17it/s]

        Date    t
0 2025-04-02  457

   n_datos modo_vela
0       50    cuerpo

        Date    t
0 2025-04-02  457

 21%|██▏       | 3/14 [00:00<00:01,  5.52it/s]

   n_datos modo_vela
0       50    sombra

        Date    t
0 2025-04-02  457

 29%|██▊       | 4/14 [00:00<00:01,  5.63it/s]

   n_datos modo_vela
0       80    cuerpo

        Date    t
0 2025-04-02  457

 36%|███▌      | 5/14 [00:00<00:01,  5.91it/s]

   n_datos modo_vela
0       80    sombra

        Date    t
0 2025-04-02  457

 43%|████▎     | 6/14 [00:01<00:01,  5.99it/s]

   n_datos modo_vela
0      100    cuerpo

        Date    t
0 2025-04-02  457

 50%|█████     | 7/14 [00:01<00:01,  5.98it/s]

   n_datos modo_vela
0      100    sombra

        Date    t
0 2025-04-02  457

 57%|█████▋    | 8/14 [00:01<00:00,  6.01it/s]

   n_datos modo_vela
0      150    cuerpo

        Date    t
0 2025-04-02  457

 64%|██████▍   | 9/14 [00:01<00:00,  6.05it/s]

   n_datos modo_vela
0      150    sombra

        Date    t
0 2025-04-02  457

 71%|███████▏  | 10/14 [00:01<00:00,  6.11it/s]

   n_datos modo_vela
0      200    cuerpo

        Date    t
0 2025-04-02  457

 79%|███████▊  | 11/14 [00:01<00:00,  6.14it/s]

   n_datos modo_vela
0      200    sombra

        Date    t
0 2025-04-02  457

 86%|████████▌ | 12/14 [00:02<00:00,  6.20it/s]

   n_datos modo_vela
0      300    cuerpo

        Date    t
0 2025-04-02  457

 93%|█████████▎| 13/14 [00:02<00:00,  6.23it/s]

   n_datos modo_vela
0      300    sombra

        Date    t
0 2025-04-02  457

100%|██████████| 14/14 [00:04<00:00,  2.81it/s]

GUARDAR

## Media Móvil

In [122]:
from Clase_Valor_240902 import generate_media_movil

name = 'Media_Movil'

#iteradores para este POF
lista_n_datos_media_movil = [3, 4, 5, 10, 20, 30, 50, 80, 100, 120, 150, 200, 250, 300] # periodos hacia atrás
campos_media_movil = ['Close', 'rendimiento']

continuar_si_hay_menos = True

#configuraciones = {'diccionario_combinaciones': {'n_datos': lista_n_datos_fibonacci, 'modo_vela': modos_vela}, 'iteradores': ['n_datos', 'modo_vela'], 'incluir_dates_en_iterar': False, 'df_explicito': pd.DataFrame(), 'continuar_si_hay_menos': continuar_si_hay_menos}
configuraciones = {'diccionario_combinaciones': {'n_datos': lista_n_datos_media_movil, 'campo': campos_media_movil}, 'iteradores': ['n_datos', 'campo'], 'incluir_dates_en_iterar': False, 'df_explicito': pd.DataFrame(), 'continuar_si_hay_menos': continuar_si_hay_menos}

modulo = generate_media_movil

for i in range(len(df_activos)):
    simbolo, nombre = df_activos.loc[i]
    print(simbolo, nombre)
    valor = Valor(simbolo, nombre, cofre, saving_step, output = output) # Si no existe el objeto, se crea
    
    #display(valor.adj_data)
    valor.crear_POF(name, configuraciones, modulo)

BTC-USD Bitcoin
Rescate en ../Cofre/Valor/ BTC-USD
../Cofre/Valor/BTC-USD
<_io.BufferedReader name='../Cofre/Valor/BTC-USD.pkl'>
COMENTAR FUNCION!!!!
Lista date en crear POF
<DatetimeArray>
['2025-03-24 00:00:00', '2025-03-25 00:00:00', '2025-03-26 00:00:00',
 '2025-03-27 00:00:00', '2025-03-28 00:00:00', '2025-03-29 00:00:00',
 '2025-03-30 00:00:00', '2025-03-31 00:00:00', '2025-04-01 00:00:00',
 '2025-04-02 00:00:00']
Length: 10, dtype: datetime64[ns]
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/28 [00:00<?, ?it/s]

   n_datos  campo
0        3  Close

   n_datos        campo
0        3  rendimiento

  7%|▋         | 2/28 [00:00<00:01, 13.90it/s]

   n_datos  campo
0        4  Close

   n_datos        campo
0        4  rendimiento

 14%|█▍        | 4/28 [00:00<00:02, 11.23it/s]

   n_datos  campo
0        5  Close

   n_datos        campo
0        5  rendimiento

 21%|██▏       | 6/28 [00:00<00:02,  8.20it/s]

   n_datos  campo
0       10  Close

 25%|██▌       | 7/28 [00:00<00:02,  7.88it/s]

   n_datos        campo
0       10  rendimiento

 29%|██▊       | 8/28 [00:00<00:02,  7.56it/s]

   n_datos  campo
0       20  Close

 32%|███▏      | 9/28 [00:01<00:02,  7.59it/s]

   n_datos        campo
0       20  rendimiento

   n_datos  campo
0       30  Close

 39%|███▉      | 11/28 [00:01<00:01,  8.79it/s]

   n_datos        campo
0       30  rendimiento

 43%|████▎     | 12/28 [00:01<00:01,  8.65it/s]

   n_datos  campo
0       50  Close

 46%|████▋     | 13/28 [00:01<00:01,  8.72it/s]

   n_datos        campo
0       50  rendimiento

 50%|█████     | 14/28 [00:01<00:01,  8.92it/s]

   n_datos  campo
0       80  Close

 54%|█████▎    | 15/28 [00:01<00:01,  9.13it/s]

   n_datos        campo
0       80  rendimiento

 57%|█████▋    | 16/28 [00:01<00:01,  9.05it/s]

   n_datos  campo
0      100  Close

 61%|██████    | 17/28 [00:01<00:01,  9.28it/s]

   n_datos        campo
0      100  rendimiento

 64%|██████▍   | 18/28 [00:02<00:01,  9.38it/s]

   n_datos  campo
0      120  Close

   n_datos        campo
0      120  rendimiento

 71%|███████▏  | 20/28 [00:02<00:00,  9.94it/s]

   n_datos  campo
0      150  Close

   n_datos        campo
0      150  rendimiento

 79%|███████▊  | 22/28 [00:02<00:00, 10.16it/s]

   n_datos  campo
0      200  Close

   n_datos        campo
0      200  rendimiento

 86%|████████▌ | 24/28 [00:02<00:00,  8.86it/s]

   n_datos  campo
0      250  Close

 89%|████████▉ | 25/28 [00:02<00:00,  8.41it/s]

   n_datos        campo
0      250  rendimiento

 93%|█████████▎| 26/28 [00:02<00:00,  7.77it/s]

   n_datos  campo
0      300  Close

 96%|█████████▋| 27/28 [00:03<00:00,  8.15it/s]

   n_datos        campo
0      300  rendimiento

100%|██████████| 28/28 [00:04<00:00,  6.50it/s]

GUARDAR





NFLX Netflix, Inc.
Rescate en ../Cofre/Valor/ NFLX
../Cofre/Valor/NFLX
<_io.BufferedReader name='../Cofre/Valor/NFLX.pkl'>
COMENTAR FUNCION!!!!
Lista date en crear POF
<DatetimeArray>
['2025-03-20 00:00:00', '2025-03-21 00:00:00', '2025-03-24 00:00:00',
 '2025-03-25 00:00:00', '2025-03-26 00:00:00', '2025-03-27 00:00:00',
 '2025-03-28 00:00:00', '2025-03-31 00:00:00', '2025-04-01 00:00:00',
 '2025-04-02 00:00:00']
Length: 10, dtype: datetime64[ns]
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/28 [00:00<?, ?it/s]

   n_datos  campo
0        3  Close

  4%|▎         | 1/28 [00:00<00:03,  7.27it/s]

   n_datos        campo
0        3  rendimiento

  7%|▋         | 2/28 [00:00<00:03,  8.03it/s]

   n_datos  campo
0        4  Close

 11%|█         | 3/28 [00:00<00:02,  8.39it/s]

   n_datos        campo
0        4  rendimiento

 14%|█▍        | 4/28 [00:00<00:02,  8.53it/s]

   n_datos  campo
0        5  Close

 18%|█▊        | 5/28 [00:00<00:02,  8.93it/s]

   n_datos        campo
0        5  rendimiento

 21%|██▏       | 6/28 [00:00<00:02,  9.11it/s]

   n_datos  campo
0       10  Close

 25%|██▌       | 7/28 [00:00<00:02,  8.20it/s]

   n_datos        campo
0       10  rendimiento

 29%|██▊       | 8/28 [00:00<00:02,  7.97it/s]

   n_datos  campo
0       20  Close

 32%|███▏      | 9/28 [00:01<00:02,  7.28it/s]

   n_datos        campo
0       20  rendimiento

 36%|███▌      | 10/28 [00:01<00:02,  7.25it/s]

   n_datos  campo
0       30  Close

 39%|███▉      | 11/28 [00:01<00:02,  7.38it/s]

   n_datos        campo
0       30  rendimiento

 43%|████▎     | 12/28 [00:01<00:02,  7.38it/s]

   n_datos  campo
0       50  Close

 46%|████▋     | 13/28 [00:01<00:01,  7.90it/s]

   n_datos        campo
0       50  rendimiento

 50%|█████     | 14/28 [00:01<00:01,  8.31it/s]

   n_datos  campo
0       80  Close

 54%|█████▎    | 15/28 [00:01<00:01,  8.67it/s]

   n_datos        campo
0       80  rendimiento

 57%|█████▋    | 16/28 [00:01<00:01,  8.82it/s]

   n_datos  campo
0      100  Close

 61%|██████    | 17/28 [00:02<00:01,  8.86it/s]

   n_datos        campo
0      100  rendimiento

 64%|██████▍   | 18/28 [00:02<00:01,  8.40it/s]

   n_datos  campo
0      120  Close

 68%|██████▊   | 19/28 [00:02<00:01,  7.21it/s]

   n_datos        campo
0      120  rendimiento

   n_datos  campo
0      150  Close

 75%|███████▌  | 21/28 [00:02<00:00,  8.17it/s]

   n_datos        campo
0      150  rendimiento

 79%|███████▊  | 22/28 [00:02<00:00,  8.53it/s]

   n_datos  campo
0      200  Close

 82%|████████▏ | 23/28 [00:02<00:00,  8.85it/s]

   n_datos        campo
0      200  rendimiento

 86%|████████▌ | 24/28 [00:02<00:00,  8.98it/s]

   n_datos  campo
0      250  Close

 89%|████████▉ | 25/28 [00:03<00:00,  9.18it/s]

   n_datos        campo
0      250  rendimiento

 93%|█████████▎| 26/28 [00:03<00:00,  9.13it/s]

   n_datos  campo
0      300  Close

 96%|█████████▋| 27/28 [00:03<00:00,  9.31it/s]

   n_datos        campo
0      300  rendimiento

100%|██████████| 28/28 [00:04<00:00,  5.86it/s]

GUARDAR





AAPL Apple Inc.
Rescate en ../Cofre/Valor/ AAPL
../Cofre/Valor/AAPL
<_io.BufferedReader name='../Cofre/Valor/AAPL.pkl'>
COMENTAR FUNCION!!!!
Lista date en crear POF
<DatetimeArray>
['2025-03-20 00:00:00', '2025-03-21 00:00:00', '2025-03-24 00:00:00',
 '2025-03-25 00:00:00', '2025-03-26 00:00:00', '2025-03-27 00:00:00',
 '2025-03-28 00:00:00', '2025-03-31 00:00:00', '2025-04-01 00:00:00',
 '2025-04-02 00:00:00']
Length: 10, dtype: datetime64[ns]
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/28 [00:00<?, ?it/s]

   n_datos  campo
0        3  Close

  4%|▎         | 1/28 [00:00<00:06,  4.32it/s]

   n_datos        campo
0        3  rendimiento

  7%|▋         | 2/28 [00:00<00:05,  4.67it/s]

   n_datos  campo
0        4  Close

 11%|█         | 3/28 [00:00<00:06,  4.14it/s]

   n_datos        campo
0        4  rendimiento

 14%|█▍        | 4/28 [00:01<00:06,  3.75it/s]

   n_datos  campo
0        5  Close

 18%|█▊        | 5/28 [00:01<00:06,  3.44it/s]

   n_datos        campo
0        5  rendimiento

 21%|██▏       | 6/28 [00:01<00:06,  3.26it/s]

   n_datos  campo
0       10  Close

 25%|██▌       | 7/28 [00:02<00:06,  3.18it/s]

   n_datos        campo
0       10  rendimiento

 29%|██▊       | 8/28 [00:02<00:06,  2.96it/s]

   n_datos  campo
0       20  Close

 32%|███▏      | 9/28 [00:02<00:06,  2.94it/s]

   n_datos        campo
0       20  rendimiento

 36%|███▌      | 10/28 [00:03<00:06,  2.99it/s]

   n_datos  campo
0       30  Close

 39%|███▉      | 11/28 [00:03<00:05,  3.01it/s]

   n_datos        campo
0       30  rendimiento

 43%|████▎     | 12/28 [00:03<00:05,  3.02it/s]

   n_datos  campo
0       50  Close

 46%|████▋     | 13/28 [00:04<00:05,  2.85it/s]

   n_datos        campo
0       50  rendimiento

 50%|█████     | 14/28 [00:04<00:04,  2.94it/s]

   n_datos  campo
0       80  Close

 54%|█████▎    | 15/28 [00:04<00:04,  2.82it/s]

   n_datos        campo
0       80  rendimiento

 57%|█████▋    | 16/28 [00:05<00:04,  2.93it/s]

   n_datos  campo
0      100  Close

 61%|██████    | 17/28 [00:05<00:03,  3.00it/s]

   n_datos        campo
0      100  rendimiento

 64%|██████▍   | 18/28 [00:05<00:03,  3.33it/s]

   n_datos  campo
0      120  Close

 68%|██████▊   | 19/28 [00:05<00:02,  3.57it/s]

   n_datos        campo
0      120  rendimiento

 71%|███████▏  | 20/28 [00:06<00:02,  3.55it/s]

   n_datos  campo
0      150  Close

 75%|███████▌  | 21/28 [00:06<00:02,  3.38it/s]

   n_datos        campo
0      150  rendimiento

 79%|███████▊  | 22/28 [00:06<00:01,  3.36it/s]

   n_datos  campo
0      200  Close

 82%|████████▏ | 23/28 [00:07<00:01,  3.70it/s]

   n_datos        campo
0      200  rendimiento

 86%|████████▌ | 24/28 [00:07<00:00,  4.07it/s]

   n_datos  campo
0      250  Close

 89%|████████▉ | 25/28 [00:07<00:00,  4.29it/s]

   n_datos        campo
0      250  rendimiento

 93%|█████████▎| 26/28 [00:07<00:00,  4.48it/s]

   n_datos  campo
0      300  Close

 96%|█████████▋| 27/28 [00:07<00:00,  4.40it/s]

   n_datos        campo
0      300  rendimiento

100%|██████████| 28/28 [00:11<00:00,  2.45it/s]

GUARDAR





WMT Walmart
Rescate en ../Cofre/Valor/ WMT
../Cofre/Valor/WMT
<_io.BufferedReader name='../Cofre/Valor/WMT.pkl'>

COMENTAR FUNCION!!!!
Lista date en crear POF
<DatetimeArray>
['2025-03-20 00:00:00', '2025-03-21 00:00:00', '2025-03-24 00:00:00',
 '2025-03-25 00:00:00', '2025-03-26 00:00:00', '2025-03-27 00:00:00',
 '2025-03-28 00:00:00', '2025-03-31 00:00:00', '2025-04-01 00:00:00',
 '2025-04-02 00:00:00']
Length: 10, dtype: datetime64[ns]
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/28 [00:00<?, ?it/s]

   n_datos  campo
0        3  Close

  4%|▎         | 1/28 [00:00<00:06,  4.02it/s]

   n_datos        campo
0        3  rendimiento

  7%|▋         | 2/28 [00:00<00:06,  4.09it/s]

   n_datos  campo
0        4  Close

 11%|█         | 3/28 [00:00<00:06,  3.95it/s]

   n_datos        campo
0        4  rendimiento

 14%|█▍        | 4/28 [00:00<00:05,  4.04it/s]

   n_datos  campo
0        5  Close

 18%|█▊        | 5/28 [00:01<00:05,  4.09it/s]

   n_datos        campo
0        5  rendimiento

 21%|██▏       | 6/28 [00:01<00:05,  3.97it/s]

   n_datos  campo
0       10  Close

 25%|██▌       | 7/28 [00:01<00:05,  4.08it/s]

   n_datos        campo
0       10  rendimiento

 29%|██▊       | 8/28 [00:01<00:04,  4.12it/s]

   n_datos  campo
0       20  Close

 32%|███▏      | 9/28 [00:02<00:04,  4.14it/s]

   n_datos        campo
0       20  rendimiento

 36%|███▌      | 10/28 [00:02<00:04,  4.08it/s]

   n_datos  campo
0       30  Close

 39%|███▉      | 11/28 [00:02<00:04,  3.85it/s]

   n_datos        campo
0       30  rendimiento

 43%|████▎     | 12/28 [00:03<00:04,  3.83it/s]

   n_datos  campo
0       50  Close

 46%|████▋     | 13/28 [00:03<00:05,  2.94it/s]

   n_datos        campo
0       50  rendimiento

 50%|█████     | 14/28 [00:03<00:04,  2.86it/s]

   n_datos  campo
0       80  Close

 54%|█████▎    | 15/28 [00:04<00:04,  2.84it/s]

   n_datos        campo
0       80  rendimiento

 57%|█████▋    | 16/28 [00:04<00:04,  2.75it/s]

   n_datos  campo
0      100  Close

 61%|██████    | 17/28 [00:04<00:03,  2.92it/s]

   n_datos        campo
0      100  rendimiento

 64%|██████▍   | 18/28 [00:05<00:03,  2.87it/s]

   n_datos  campo
0      120  Close

 68%|██████▊   | 19/28 [00:05<00:03,  2.81it/s]

   n_datos        campo
0      120  rendimiento

 71%|███████▏  | 20/28 [00:06<00:03,  2.30it/s]

   n_datos  campo
0      150  Close

 75%|███████▌  | 21/28 [00:06<00:03,  2.32it/s]

   n_datos        campo
0      150  rendimiento

 79%|███████▊  | 22/28 [00:07<00:02,  2.41it/s]

   n_datos  campo
0      200  Close

 82%|████████▏ | 23/28 [00:07<00:01,  2.58it/s]

   n_datos        campo
0      200  rendimiento

 86%|████████▌ | 24/28 [00:07<00:01,  2.47it/s]

   n_datos  campo
0      250  Close

 89%|████████▉ | 25/28 [00:08<00:01,  2.57it/s]

   n_datos        campo
0      250  rendimiento

 93%|█████████▎| 26/28 [00:08<00:00,  2.58it/s]

   n_datos  campo
0      300  Close

 96%|█████████▋| 27/28 [00:08<00:00,  2.59it/s]

   n_datos        campo
0      300  rendimiento

100%|██████████| 28/28 [00:14<00:00,  1.97it/s]

GUARDAR





TSLA Tesla
Rescate en ../Cofre/Valor/ TSLA
../Cofre/Valor/TSLA
<_io.BufferedReader name='../Cofre/Valor/TSLA.pkl'>
COMENTAR FUNCION!!!!
Lista date en crear POF
<DatetimeArray>
['2025-03-20 00:00:00', '2025-03-21 00:00:00', '2025-03-24 00:00:00',
 '2025-03-25 00:00:00', '2025-03-26 00:00:00', '2025-03-27 00:00:00',
 '2025-03-28 00:00:00', '2025-03-31 00:00:00', '2025-04-01 00:00:00',
 '2025-04-02 00:00:00']
Length: 10, dtype: datetime64[ns]
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/28 [00:00<?, ?it/s]

   n_datos  campo
0        3  Close

  4%|▎         | 1/28 [00:00<00:03,  8.55it/s]

   n_datos        campo
0        3  rendimiento

  7%|▋         | 2/28 [00:00<00:02,  8.80it/s]

   n_datos  campo
0        4  Close

 11%|█         | 3/28 [00:00<00:02,  8.96it/s]

   n_datos        campo
0        4  rendimiento

 14%|█▍        | 4/28 [00:00<00:02,  8.33it/s]

   n_datos  campo
0        5  Close

 18%|█▊        | 5/28 [00:00<00:02,  8.19it/s]

   n_datos        campo
0        5  rendimiento

 21%|██▏       | 6/28 [00:00<00:02,  8.41it/s]

   n_datos  campo
0       10  Close

 25%|██▌       | 7/28 [00:00<00:02,  8.37it/s]

   n_datos        campo
0       10  rendimiento

 29%|██▊       | 8/28 [00:00<00:02,  8.03it/s]

   n_datos  campo
0       20  Close

 32%|███▏      | 9/28 [00:01<00:02,  7.46it/s]

   n_datos        campo
0       20  rendimiento

 36%|███▌      | 10/28 [00:01<00:02,  7.48it/s]

   n_datos  campo
0       30  Close

 39%|███▉      | 11/28 [00:01<00:02,  7.28it/s]

   n_datos        campo
0       30  rendimiento

 43%|████▎     | 12/28 [00:01<00:02,  6.54it/s]

   n_datos  campo
0       50  Close

 46%|████▋     | 13/28 [00:01<00:02,  6.67it/s]

   n_datos        campo
0       50  rendimiento

 50%|█████     | 14/28 [00:01<00:02,  6.50it/s]

   n_datos  campo
0       80  Close

 54%|█████▎    | 15/28 [00:02<00:02,  6.47it/s]

   n_datos        campo
0       80  rendimiento

 57%|█████▋    | 16/28 [00:02<00:01,  6.36it/s]

   n_datos  campo
0      100  Close

 61%|██████    | 17/28 [00:02<00:01,  5.81it/s]

   n_datos        campo
0      100  rendimiento

 64%|██████▍   | 18/28 [00:02<00:01,  6.00it/s]

   n_datos  campo
0      120  Close

 68%|██████▊   | 19/28 [00:02<00:01,  6.33it/s]

   n_datos        campo
0      120  rendimiento

 71%|███████▏  | 20/28 [00:02<00:01,  6.75it/s]

   n_datos  campo
0      150  Close

 75%|███████▌  | 21/28 [00:02<00:01,  6.87it/s]

   n_datos        campo
0      150  rendimiento

 79%|███████▊  | 22/28 [00:03<00:00,  7.11it/s]

   n_datos  campo
0      200  Close

 82%|████████▏ | 23/28 [00:03<00:00,  7.21it/s]

   n_datos        campo
0      200  rendimiento

 86%|████████▌ | 24/28 [00:03<00:00,  7.17it/s]

   n_datos  campo
0      250  Close

 89%|████████▉ | 25/28 [00:03<00:00,  7.23it/s]

   n_datos        campo
0      250  rendimiento

 93%|█████████▎| 26/28 [00:03<00:00,  7.35it/s]

   n_datos  campo
0      300  Close

 96%|█████████▋| 27/28 [00:03<00:00,  7.18it/s]

   n_datos        campo
0      300  rendimiento

100%|██████████| 28/28 [00:05<00:00,  5.29it/s]

GUARDAR





AMZN Amazon
Rescate en ../Cofre/Valor/ AMZN
../Cofre/Valor/AMZN
<_io.BufferedReader name='../Cofre/Valor/AMZN.pkl'>
COMENTAR FUNCION!!!!
Lista date en crear POF
<DatetimeArray>
['2025-03-20 00:00:00', '2025-03-21 00:00:00', '2025-03-24 00:00:00',
 '2025-03-25 00:00:00', '2025-03-26 00:00:00', '2025-03-27 00:00:00',
 '2025-03-28 00:00:00', '2025-03-31 00:00:00', '2025-04-01 00:00:00',
 '2025-04-02 00:00:00']
Length: 10, dtype: datetime64[ns]
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/28 [00:00<?, ?it/s]

   n_datos  campo
0        3  Close

  4%|▎         | 1/28 [00:00<00:06,  3.93it/s]

   n_datos        campo
0        3  rendimiento

  7%|▋         | 2/28 [00:00<00:06,  4.15it/s]

   n_datos  campo
0        4  Close

 11%|█         | 3/28 [00:00<00:05,  4.53it/s]

   n_datos        campo
0        4  rendimiento

 14%|█▍        | 4/28 [00:00<00:04,  5.01it/s]

   n_datos  campo
0        5  Close

 18%|█▊        | 5/28 [00:01<00:04,  5.44it/s]

   n_datos        campo
0        5  rendimiento

 21%|██▏       | 6/28 [00:01<00:04,  5.42it/s]

   n_datos  campo
0       10  Close

 25%|██▌       | 7/28 [00:01<00:03,  5.45it/s]

   n_datos        campo
0       10  rendimiento

 29%|██▊       | 8/28 [00:01<00:03,  5.47it/s]

   n_datos  campo
0       20  Close

 32%|███▏      | 9/28 [00:01<00:03,  5.32it/s]

   n_datos        campo
0       20  rendimiento

 36%|███▌      | 10/28 [00:01<00:03,  5.47it/s]

   n_datos  campo
0       30  Close

 39%|███▉      | 11/28 [00:02<00:02,  5.91it/s]

   n_datos        campo
0       30  rendimiento

 43%|████▎     | 12/28 [00:02<00:02,  5.83it/s]

   n_datos  campo
0       50  Close

 46%|████▋     | 13/28 [00:02<00:02,  6.01it/s]

   n_datos        campo
0       50  rendimiento

 50%|█████     | 14/28 [00:02<00:02,  6.22it/s]

   n_datos  campo
0       80  Close

 54%|█████▎    | 15/28 [00:02<00:02,  6.31it/s]

   n_datos        campo
0       80  rendimiento

 57%|█████▋    | 16/28 [00:02<00:01,  6.36it/s]

   n_datos  campo
0      100  Close

 61%|██████    | 17/28 [00:02<00:01,  6.54it/s]

   n_datos        campo
0      100  rendimiento

 64%|██████▍   | 18/28 [00:03<00:01,  6.63it/s]

   n_datos  campo
0      120  Close

 68%|██████▊   | 19/28 [00:03<00:01,  6.80it/s]

   n_datos        campo
0      120  rendimiento

 71%|███████▏  | 20/28 [00:03<00:01,  6.60it/s]

   n_datos  campo
0      150  Close

 75%|███████▌  | 21/28 [00:03<00:01,  6.50it/s]

   n_datos        campo
0      150  rendimiento

 79%|███████▊  | 22/28 [00:03<00:01,  5.83it/s]

   n_datos  campo
0      200  Close

 82%|████████▏ | 23/28 [00:04<00:00,  5.45it/s]

   n_datos        campo
0      200  rendimiento

 86%|████████▌ | 24/28 [00:04<00:00,  5.32it/s]

   n_datos  campo
0      250  Close

 89%|████████▉ | 25/28 [00:04<00:00,  5.26it/s]

   n_datos        campo
0      250  rendimiento

 93%|█████████▎| 26/28 [00:04<00:00,  5.21it/s]

   n_datos  campo
0      300  Close

 96%|█████████▋| 27/28 [00:04<00:00,  5.11it/s]

   n_datos        campo
0      300  rendimiento

100%|██████████| 28/28 [00:06<00:00,  4.03it/s]

GUARDAR





BRK-A Berkshire Hathaway
Rescate en ../Cofre/Valor/ BRK-A
../Cofre/Valor/BRK-A
<_io.BufferedReader name='../Cofre/Valor/BRK-A.pkl'>
COMENTAR FUNCION!!!!
Lista date en crear POF
<DatetimeArray>
['2025-03-20 00:00:00', '2025-03-21 00:00:00', '2025-03-24 00:00:00',
 '2025-03-25 00:00:00', '2025-03-26 00:00:00', '2025-03-27 00:00:00',
 '2025-03-28 00:00:00', '2025-03-31 00:00:00', '2025-04-01 00:00:00',
 '2025-04-02 00:00:00']
Length: 10, dtype: datetime64[ns]
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/28 [00:00<?, ?it/s]

   n_datos  campo
0        3  Close

  4%|▎         | 1/28 [00:00<00:05,  4.83it/s]

   n_datos        campo
0        3  rendimiento

  7%|▋         | 2/28 [00:00<00:05,  4.84it/s]

   n_datos  campo
0        4  Close

 11%|█         | 3/28 [00:00<00:05,  4.72it/s]

   n_datos        campo
0        4  rendimiento

 14%|█▍        | 4/28 [00:00<00:05,  4.52it/s]

   n_datos  campo
0        5  Close

 18%|█▊        | 5/28 [00:01<00:05,  4.21it/s]

   n_datos        campo
0        5  rendimiento

 21%|██▏       | 6/28 [00:01<00:05,  4.04it/s]

   n_datos  campo
0       10  Close

 25%|██▌       | 7/28 [00:01<00:05,  3.63it/s]

   n_datos        campo
0       10  rendimiento

 29%|██▊       | 8/28 [00:02<00:06,  3.13it/s]

   n_datos  campo
0       20  Close

 32%|███▏      | 9/28 [00:02<00:05,  3.28it/s]

   n_datos        campo
0       20  rendimiento

 36%|███▌      | 10/28 [00:02<00:05,  3.55it/s]

   n_datos  campo
0       30  Close

 39%|███▉      | 11/28 [00:02<00:04,  3.74it/s]

   n_datos        campo
0       30  rendimiento

 43%|████▎     | 12/28 [00:03<00:04,  3.51it/s]

   n_datos  campo
0       50  Close

 46%|████▋     | 13/28 [00:03<00:04,  3.39it/s]

   n_datos        campo
0       50  rendimiento

 50%|█████     | 14/28 [00:03<00:03,  3.64it/s]

   n_datos  campo
0       80  Close

 54%|█████▎    | 15/28 [00:03<00:03,  3.85it/s]

   n_datos        campo
0       80  rendimiento

 57%|█████▋    | 16/28 [00:04<00:03,  3.80it/s]

   n_datos  campo
0      100  Close

 61%|██████    | 17/28 [00:04<00:02,  3.85it/s]

   n_datos        campo
0      100  rendimiento

 64%|██████▍   | 18/28 [00:04<00:02,  3.88it/s]

   n_datos  campo
0      120  Close

 68%|██████▊   | 19/28 [00:04<00:02,  4.03it/s]

   n_datos        campo
0      120  rendimiento

 71%|███████▏  | 20/28 [00:05<00:01,  4.15it/s]

   n_datos  campo
0      150  Close

 75%|███████▌  | 21/28 [00:05<00:01,  4.31it/s]

   n_datos        campo
0      150  rendimiento

 79%|███████▊  | 22/28 [00:05<00:01,  4.21it/s]

   n_datos  campo
0      200  Close

 82%|████████▏ | 23/28 [00:05<00:01,  4.20it/s]

   n_datos        campo
0      200  rendimiento

 86%|████████▌ | 24/28 [00:06<00:01,  3.52it/s]

   n_datos  campo
0      250  Close

 89%|████████▉ | 25/28 [00:06<00:00,  3.23it/s]

   n_datos        campo
0      250  rendimiento

 93%|█████████▎| 26/28 [00:06<00:00,  3.32it/s]

   n_datos  campo
0      300  Close

 96%|█████████▋| 27/28 [00:07<00:00,  3.36it/s]

   n_datos        campo
0      300  rendimiento

100%|██████████| 28/28 [00:10<00:00,  2.67it/s]

GUARDAR

## Suavizamiento Exponencial

In [123]:
from Clase_Valor_240902 import generate_suavexp

name = 'Suavizamiento_Exponencial'

#iteradores para este POF
lista_alpha = [0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7] # Para suavizamiento exponencial
campos_suavexp = ['Close', 'rendimiento']

continuar_si_hay_menos = True

configuraciones = {'diccionario_combinaciones': {'alpha': lista_alpha, 'campo': campos_suavexp}, 'iteradores': ['alpha', 'campo'], 'incluir_dates_en_iterar': False, 'df_explicito': pd.DataFrame(), 'continuar_si_hay_menos': continuar_si_hay_menos}

modulo = generate_suavexp

for i in range(len(df_activos)):
    simbolo, nombre = df_activos.loc[i]
    print(simbolo, nombre)
    valor = Valor(simbolo, nombre, cofre, saving_step, output = output) # Si no existe el objeto, se crea
    
    #display(valor.adj_data)
    valor.crear_POF(name, configuraciones, modulo)

BTC-USD Bitcoin
Rescate en ../Cofre/Valor/ BTC-USD
../Cofre/Valor/BTC-USD
<_io.BufferedReader name='../Cofre/Valor/BTC-USD.pkl'>
COMENTAR FUNCION!!!!
Lista date en crear POF
<DatetimeArray>
['2025-03-24 00:00:00', '2025-03-25 00:00:00', '2025-03-26 00:00:00',
 '2025-03-27 00:00:00', '2025-03-28 00:00:00', '2025-03-29 00:00:00',
 '2025-03-30 00:00:00', '2025-03-31 00:00:00', '2025-04-01 00:00:00',
 '2025-04-02 00:00:00']
Length: 10, dtype: datetime64[ns]
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/16 [00:00<?, ?it/s]

   alpha  campo
0   0.05  Close

   alpha        campo
0   0.05  rendimiento

 12%|█▎        | 2/16 [00:00<00:01, 10.53it/s]

   alpha  campo
0    0.1  Close

   alpha        campo
0    0.1  rendimiento

 25%|██▌       | 4/16 [00:00<00:00, 12.19it/s]

   alpha  campo
0    0.2  Close

   alpha        campo
0    0.2  rendimiento

 38%|███▊      | 6/16 [00:00<00:00, 12.82it/s]

   alpha  campo
0    0.3  Close

   alpha        campo
0    0.3  rendimiento

 50%|█████     | 8/16 [00:00<00:00, 13.61it/s]

   alpha  campo
0    0.4  Close

   alpha        campo
0    0.4  rendimiento

 62%|██████▎   | 10/16 [00:00<00:00, 13.52it/s]

   alpha  campo
0    0.5  Close

   alpha        campo
0    0.5  rendimiento

 75%|███████▌  | 12/16 [00:00<00:00, 13.52it/s]

   alpha  campo
0    0.6  Close

   alpha        campo
0    0.6  rendimiento

 88%|████████▊ | 14/16 [00:01<00:00, 12.96it/s]

   alpha  campo
0    0.7  Close

   alpha        campo
0    0.7  rendimiento

100%|██████████| 16/16 [00:02<00:00,  7.34it/s]

GUARDAR





NFLX Netflix, Inc.
Rescate en ../Cofre/Valor/ NFLX
../Cofre/Valor/NFLX
<_io.BufferedReader name='../Cofre/Valor/NFLX.pkl'>
COMENTAR FUNCION!!!!
Lista date en crear POF
<DatetimeArray>
['2025-03-20 00:00:00', '2025-03-21 00:00:00', '2025-03-24 00:00:00',
 '2025-03-25 00:00:00', '2025-03-26 00:00:00', '2025-03-27 00:00:00',
 '2025-03-28 00:00:00', '2025-03-31 00:00:00', '2025-04-01 00:00:00',
 '2025-04-02 00:00:00']
Length: 10, dtype: datetime64[ns]
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/16 [00:00<?, ?it/s]

   alpha  campo
0   0.05  Close

   alpha        campo
0   0.05  rendimiento

 12%|█▎        | 2/16 [00:00<00:01,  9.79it/s]

   alpha  campo
0    0.1  Close

 19%|█▉        | 3/16 [00:00<00:01,  9.87it/s]

   alpha        campo
0    0.1  rendimiento

 25%|██▌       | 4/16 [00:00<00:01,  9.89it/s]

   alpha  campo
0    0.2  Close

 31%|███▏      | 5/16 [00:00<00:01,  9.90it/s]

   alpha        campo
0    0.2  rendimiento

   alpha  campo
0    0.3  Close

 44%|████▍     | 7/16 [00:00<00:00, 10.06it/s]

   alpha        campo
0    0.3  rendimiento

   alpha  campo
0    0.4  Close

 56%|█████▋    | 9/16 [00:00<00:00, 10.06it/s]

   alpha        campo
0    0.4  rendimiento

   alpha  campo
0    0.5  Close

 69%|██████▉   | 11/16 [00:01<00:00,  9.14it/s]

   alpha        campo
0    0.5  rendimiento

 75%|███████▌  | 12/16 [00:01<00:00,  9.24it/s]

   alpha  campo
0    0.6  Close

 81%|████████▏ | 13/16 [00:01<00:00,  9.27it/s]

   alpha        campo
0    0.6  rendimiento

 88%|████████▊ | 14/16 [00:01<00:00,  9.11it/s]

   alpha  campo
0    0.7  Close

   alpha        campo
0    0.7  rendimiento

100%|██████████| 16/16 [00:02<00:00,  5.39it/s]

GUARDAR





AAPL Apple Inc.
Rescate en ../Cofre/Valor/ AAPL
../Cofre/Valor/AAPL
<_io.BufferedReader name='../Cofre/Valor/AAPL.pkl'>
COMENTAR FUNCION!!!!
Lista date en crear POF
<DatetimeArray>
['2025-03-20 00:00:00', '2025-03-21 00:00:00', '2025-03-24 00:00:00',
 '2025-03-25 00:00:00', '2025-03-26 00:00:00', '2025-03-27 00:00:00',
 '2025-03-28 00:00:00', '2025-03-31 00:00:00', '2025-04-01 00:00:00',
 '2025-04-02 00:00:00']
Length: 10, dtype: datetime64[ns]
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/16 [00:00<?, ?it/s]

   alpha  campo
0   0.05  Close

  6%|▋         | 1/16 [00:00<00:02,  5.14it/s]

   alpha        campo
0   0.05  rendimiento

 12%|█▎        | 2/16 [00:00<00:02,  5.40it/s]

   alpha  campo
0    0.1  Close

 19%|█▉        | 3/16 [00:00<00:02,  5.25it/s]

   alpha        campo
0    0.1  rendimiento

 25%|██▌       | 4/16 [00:00<00:02,  5.01it/s]

   alpha  campo
0    0.2  Close

 31%|███▏      | 5/16 [00:00<00:02,  5.21it/s]

   alpha        campo
0    0.2  rendimiento

 38%|███▊      | 6/16 [00:01<00:02,  4.93it/s]

   alpha  campo
0    0.3  Close

 44%|████▍     | 7/16 [00:01<00:01,  4.73it/s]

   alpha        campo
0    0.3  rendimiento

 50%|█████     | 8/16 [00:01<00:01,  4.16it/s]

   alpha  campo
0    0.4  Close

 56%|█████▋    | 9/16 [00:01<00:01,  4.23it/s]

   alpha        campo
0    0.4  rendimiento

 62%|██████▎   | 10/16 [00:02<00:01,  4.64it/s]

   alpha  campo
0    0.5  Close

 69%|██████▉   | 11/16 [00:02<00:01,  4.91it/s]

   alpha        campo
0    0.5  rendimiento

 75%|███████▌  | 12/16 [00:02<00:00,  5.05it/s]

   alpha  campo
0    0.6  Close

 81%|████████▏ | 13/16 [00:02<00:00,  5.22it/s]

   alpha        campo
0    0.6  rendimiento

 88%|████████▊ | 14/16 [00:02<00:00,  5.38it/s]

   alpha  campo
0    0.7  Close

 94%|█████████▍| 15/16 [00:03<00:00,  5.45it/s]

   alpha        campo
0    0.7  rendimiento

100%|██████████| 16/16 [00:05<00:00,  2.75it/s]

GUARDAR





WMT Walmart
Rescate en ../Cofre/Valor/ WMT
../Cofre/Valor/WMT
<_io.BufferedReader name='../Cofre/Valor/WMT.pkl'>
COMENTAR FUNCION!!!!
Lista date en crear POF
<DatetimeArray>
['2025-03-20 00:00:00', '2025-03-21 00:00:00', '2025-03-24 00:00:00',
 '2025-03-25 00:00:00', '2025-03-26 00:00:00', '2025-03-27 00:00:00',
 '2025-03-28 00:00:00', '2025-03-31 00:00:00', '2025-04-01 00:00:00',
 '2025-04-02 00:00:00']
Length: 10, dtype: datetime64[ns]
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/16 [00:00<?, ?it/s]

   alpha  campo
0   0.05  Close

  6%|▋         | 1/16 [00:00<00:03,  4.53it/s]

   alpha        campo
0   0.05  rendimiento

 12%|█▎        | 2/16 [00:00<00:03,  4.42it/s]

   alpha  campo
0    0.1  Close

 19%|█▉        | 3/16 [00:00<00:02,  4.56it/s]

   alpha        campo
0    0.1  rendimiento

 25%|██▌       | 4/16 [00:00<00:02,  4.64it/s]

   alpha  campo
0    0.2  Close

 31%|███▏      | 5/16 [00:01<00:02,  4.60it/s]

   alpha        campo
0    0.2  rendimiento

 38%|███▊      | 6/16 [00:01<00:02,  4.47it/s]

   alpha  campo
0    0.3  Close

 44%|████▍     | 7/16 [00:01<00:01,  4.51it/s]

   alpha        campo
0    0.3  rendimiento

 50%|█████     | 8/16 [00:01<00:01,  4.68it/s]

   alpha  campo
0    0.4  Close

 56%|█████▋    | 9/16 [00:01<00:01,  4.68it/s]

   alpha        campo
0    0.4  rendimiento

 62%|██████▎   | 10/16 [00:02<00:01,  4.66it/s]

   alpha  campo
0    0.5  Close

 69%|██████▉   | 11/16 [00:02<00:01,  4.64it/s]

   alpha        campo
0    0.5  rendimiento

 75%|███████▌  | 12/16 [00:02<00:00,  4.53it/s]

   alpha  campo
0    0.6  Close

 81%|████████▏ | 13/16 [00:02<00:00,  4.60it/s]

   alpha        campo
0    0.6  rendimiento

 88%|████████▊ | 14/16 [00:03<00:00,  4.56it/s]

   alpha  campo
0    0.7  Close

 94%|█████████▍| 15/16 [00:03<00:00,  4.50it/s]

   alpha        campo
0    0.7  rendimiento

100%|██████████| 16/16 [00:06<00:00,  2.45it/s]

GUARDAR





TSLA Tesla
Rescate en ../Cofre/Valor/ TSLA
../Cofre/Valor/TSLA
<_io.BufferedReader name='../Cofre/Valor/TSLA.pkl'>
COMENTAR FUNCION!!!!
Lista date en crear POF
<DatetimeArray>
['2025-03-20 00:00:00', '2025-03-21 00:00:00', '2025-03-24 00:00:00',
 '2025-03-25 00:00:00', '2025-03-26 00:00:00', '2025-03-27 00:00:00',
 '2025-03-28 00:00:00', '2025-03-31 00:00:00', '2025-04-01 00:00:00',
 '2025-04-02 00:00:00']
Length: 10, dtype: datetime64[ns]
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/16 [00:00<?, ?it/s]

   alpha  campo
0   0.05  Close

   alpha        campo
0   0.05  rendimiento

 12%|█▎        | 2/16 [00:00<00:00, 15.64it/s]

   alpha  campo
0    0.1  Close

   alpha        campo
0    0.1  rendimiento

 25%|██▌       | 4/16 [00:00<00:00, 15.59it/s]

   alpha  campo
0    0.2  Close

   alpha        campo
0    0.2  rendimiento

 38%|███▊      | 6/16 [00:00<00:00, 15.45it/s]

   alpha  campo
0    0.3  Close

   alpha        campo
0    0.3  rendimiento

 50%|█████     | 8/16 [00:00<00:00, 14.42it/s]

   alpha  campo
0    0.4  Close

   alpha        campo
0    0.4  rendimiento

 62%|██████▎   | 10/16 [00:00<00:00, 14.02it/s]

   alpha  campo
0    0.5  Close

   alpha        campo
0    0.5  rendimiento

 75%|███████▌  | 12/16 [00:00<00:00, 14.36it/s]

   alpha  campo
0    0.6  Close

   alpha        campo
0    0.6  rendimiento

 88%|████████▊ | 14/16 [00:00<00:00, 14.66it/s]

   alpha  campo
0    0.7  Close

   alpha        campo
0    0.7  rendimiento

100%|██████████| 16/16 [00:01<00:00,  8.24it/s]

GUARDAR





AMZN Amazon
Rescate en ../Cofre/Valor/ AMZN
../Cofre/Valor/AMZN
<_io.BufferedReader name='../Cofre/Valor/AMZN.pkl'>
COMENTAR FUNCION!!!!
Lista date en crear POF
<DatetimeArray>
['2025-03-20 00:00:00', '2025-03-21 00:00:00', '2025-03-24 00:00:00',
 '2025-03-25 00:00:00', '2025-03-26 00:00:00', '2025-03-27 00:00:00',
 '2025-03-28 00:00:00', '2025-03-31 00:00:00', '2025-04-01 00:00:00',
 '2025-04-02 00:00:00']
Length: 10, dtype: datetime64[ns]
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/16 [00:00<?, ?it/s]

   alpha  campo
0   0.05  Close

  6%|▋         | 1/16 [00:00<00:01,  8.40it/s]

   alpha        campo
0   0.05  rendimiento

 12%|█▎        | 2/16 [00:00<00:01,  8.76it/s]

   alpha  campo
0    0.1  Close

 19%|█▉        | 3/16 [00:00<00:01,  8.66it/s]

   alpha        campo
0    0.1  rendimiento

 25%|██▌       | 4/16 [00:00<00:01,  8.70it/s]

   alpha  campo
0    0.2  Close

 31%|███▏      | 5/16 [00:00<00:01,  8.14it/s]

   alpha        campo
0    0.2  rendimiento

 38%|███▊      | 6/16 [00:00<00:01,  7.99it/s]

   alpha  campo
0    0.3  Close

 44%|████▍     | 7/16 [00:00<00:01,  8.39it/s]

   alpha        campo
0    0.3  rendimiento

 50%|█████     | 8/16 [00:00<00:00,  8.47it/s]

   alpha  campo
0    0.4  Close

 56%|█████▋    | 9/16 [00:01<00:00,  8.59it/s]

   alpha        campo
0    0.4  rendimiento

 62%|██████▎   | 10/16 [00:01<00:00,  8.60it/s]

   alpha  campo
0    0.5  Close

 69%|██████▉   | 11/16 [00:01<00:00,  8.70it/s]

   alpha        campo
0    0.5  rendimiento

 75%|███████▌  | 12/16 [00:01<00:00,  8.56it/s]

   alpha  campo
0    0.6  Close

 81%|████████▏ | 13/16 [00:01<00:00,  8.34it/s]

   alpha        campo
0    0.6  rendimiento

 88%|████████▊ | 14/16 [00:01<00:00,  7.88it/s]

   alpha  campo
0    0.7  Close

 94%|█████████▍| 15/16 [00:01<00:00,  7.63it/s]

   alpha        campo
0    0.7  rendimiento

100%|██████████| 16/16 [00:03<00:00,  4.23it/s]

GUARDAR





BRK-A Berkshire Hathaway
Rescate en ../Cofre/Valor/ BRK-A
../Cofre/Valor/BRK-A
<_io.BufferedReader name='../Cofre/Valor/BRK-A.pkl'>
COMENTAR FUNCION!!!!
Lista date en crear POF
<DatetimeArray>
['2025-03-20 00:00:00', '2025-03-21 00:00:00', '2025-03-24 00:00:00',
 '2025-03-25 00:00:00', '2025-03-26 00:00:00', '2025-03-27 00:00:00',
 '2025-03-28 00:00:00', '2025-03-31 00:00:00', '2025-04-01 00:00:00',
 '2025-04-02 00:00:00']
Length: 10, dtype: datetime64[ns]
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/16 [00:00<?, ?it/s]

   alpha  campo
0   0.05  Close

  6%|▋         | 1/16 [00:00<00:05,  2.93it/s]

   alpha        campo
0   0.05  rendimiento

 12%|█▎        | 2/16 [00:00<00:05,  2.70it/s]

   alpha  campo
0    0.1  Close

 19%|█▉        | 3/16 [00:01<00:04,  3.05it/s]

   alpha        campo
0    0.1  rendimiento

 25%|██▌       | 4/16 [00:01<00:03,  3.48it/s]

   alpha  campo
0    0.2  Close

 31%|███▏      | 5/16 [00:01<00:03,  3.51it/s]

   alpha        campo
0    0.2  rendimiento

 38%|███▊      | 6/16 [00:01<00:02,  3.45it/s]

   alpha  campo
0    0.3  Close

 44%|████▍     | 7/16 [00:02<00:02,  3.51it/s]

   alpha        campo
0    0.3  rendimiento

 50%|█████     | 8/16 [00:02<00:02,  3.73it/s]

   alpha  campo
0    0.4  Close

 56%|█████▋    | 9/16 [00:02<00:01,  3.67it/s]

   alpha        campo
0    0.4  rendimiento

 62%|██████▎   | 10/16 [00:02<00:01,  3.83it/s]

   alpha  campo
0    0.5  Close

 69%|██████▉   | 11/16 [00:03<00:01,  3.83it/s]

   alpha        campo
0    0.5  rendimiento

 75%|███████▌  | 12/16 [00:03<00:01,  3.56it/s]

   alpha  campo
0    0.6  Close

 81%|████████▏ | 13/16 [00:03<00:00,  3.63it/s]

   alpha        campo
0    0.6  rendimiento

 88%|████████▊ | 14/16 [00:03<00:00,  3.52it/s]

   alpha  campo
0    0.7  Close

 94%|█████████▍| 15/16 [00:04<00:00,  3.62it/s]

   alpha        campo
0    0.7  rendimiento

100%|██████████| 16/16 [00:07<00:00,  2.14it/s]

GUARDAR

## Áreas (ver módulo areas)

In [124]:
sys.exit('Antes de seguir (con módulo Áreas), limpiar código FFNN_y_BusqInt_240610')

SystemExit: Antes de seguir (con módulo Áreas), limpiar código FFNN_y_BusqInt_240610

# Otros

In [ ]:
sys.exit('OK')

In [ ]:
# ANTIGUO
for i in range(len(df_activos)):
    simbolo, nombre = df_activos.loc[i]
    print(simbolo, nombre)
    
    valor = Valor(simbolo, nombre, cofre, output = True) # Si no existe el objeto, se crea
    
    valor.extraer_data()
    valor.ajustar_data()

    display(valor.adj_data.tail())

    #print('A')
    #valor.generar_figuras_all(lista_k, lista_figuras, saving_step = saving_step)
    print('B')
    valor.generar_fibonacci_all(lista_k, saving_step = saving_step)

    print('C')
    valor.generar_media_movil_all(lista_n, lista_campos, saving_step = saving_step)
    print('D')
    valor.generar_media_movil_multiplicativa_all(lista_n, lista_campos, saving_step = saving_step)
    print('E')
    valor.generar_suavizamiento_exponencial_all(lista_alpha, lista_campos, saving_step = saving_step)
    
    #print('C1: Buscar "Continuar aqui 240506"...clase red neuronal (método construir_matrices)')
    print('C2 Construir casos como: Calidad de una figura (páginas 10 & 11), dada la info obtenida en generar_figuras_all...agregar a raw_x')
    
    #print('F')
    #df_pl = valor.generar_polinomicas_all(lista_grados, lista_R, saving_step = saving_step)

    valor.generar_output_all(lista_R)
    
    valor.guardar()
    #sys.exit('Fin')
    
print('Proceso OK')

In [ ]:
sys.exit()

# Data

In [ ]:
df = valor.adj_data
df.tail()

In [ ]:
from finta import TA
TA?

In [ ]:
TA.BBANDS(df)

# TO DO

In [ ]:
#Convex Hull, algorítmo?. Partir de un punto convexo (P0), elegir el punto que tenga menor angulo entre el vector que comienza en el P0 y apunta hacia arriba y el vector que comienza en el P0 y apunta hacia el punto. Se elige el punto que tenga el menor ángulo. Se repite el proceso hasta que se llegue al punto de inicio. Se obtiene el convex hull. 
# Se puede hacer con scipy.spatial.ConvexHull