# Librerías y Módulos

In [ ]:
import sys

# Obtener la lista de kernels
kernels = !jupyter kernelspec list

# Mostrar la lista de kernels para referencia
print(kernels)

# Buscar si 'mi_entorno' está en la lista de kernels
kernel_name = "mi_entorno"
kernel_found = False

for line in kernels:
    if kernel_name in line:
        kernel_found = True
        break

# Comprueba si el kernel de ejecución es mi_entorno
if not kernel_found:
    print(f'Kernel debe ser: {kernel_name}')
    #sys.exit()

print(f'Kernel correcto: {kernel_name}')

## Librerías

In [29]:
import pandas as pd
import sys

import warnings
warnings.filterwarnings("ignore")

In [30]:
sys.path.insert(0, '')
from Clase_Valor_240902 import Valor
from Transversal import leer_activos, leer_parametros

# Parámetros

In [31]:
reextraer_todo = True # Parámetro: SI es True, se vuelven a extraer todos los datos. Si es False, se extraen solo los valores que no estén actualizados hasta ayer
output = True

In [32]:
carpeta_input, cofre, seguimiento, saving_step = leer_parametros()

# Lectura de activos

In [ ]:
df_activos = leer_activos(carpeta_input)
df_activos

# Ejecución

In [ ]:
#df_activos = df_activos.iloc[1:].reset_index(drop = True) # solo prueba
df_activos

In [35]:
# NUEVO
for i in range(len(df_activos)):
    simbolo, nombre = df_activos.loc[i]
    print(simbolo, nombre)
    valor = Valor(simbolo, nombre, cofre, saving_step, output = output) # Si no existe el objeto, se crea
    
    valor.extraer_data(reextraer_todo = reextraer_todo) # Extrae la data del valor correspondiente, solo si existen días nuevos
    valor.ajustar_data() # interpola en algunos casos (por ahora al menos, interpolar está desactivado), y estandariza la data (0, 1)
    
    valor.guardar()

[*********************100%***********************]  1 of 1 completed

         Date      Open      High       Low     Close  Adj Close     Volume
0  2002-05-23  1.156429  1.242857  1.145714  1.196429   1.196429  104790000
1  2002-05-24  1.214286  1.225000  1.197143  1.210000   1.210000   11104800
2  2002-05-28  1.213571  1.232143  1.157143  1.157143   1.157143    6609400
3  2002-05-29  1.164286  1.164286  1.085714  1.103571   1.103571    6757800
4  2002-05-30  1.107857  1.107857  1.071429  1.071429   1.071429   10154200

,Date,Open,High,Low,Close,Adj Close,Volume
5699,2025-01-15,836.440002,850.840027,830.409973,848.260010,848.260010,3181400
5700,2025-01-16,860.960022,868.979980,842.020020,842.369995,842.369995,4028500
5701,2025-01-17,859.789978,865.000000,852.130005,858.099976,858.099976,3617600
5702,2025-01-21,863.530029,916.400024,854.750000,869.679993,869.679993,9851400
5703,2025-01-22,998.030029,999.000000,950.760010,953.989990,953.989990,14273200

FCEL FuelCell Energy, Inc.
Rescate en ../Cofre/Valor/ FCEL
../Cofre/Valor/FCEL
<_io.BufferedReader name='../Cofre/Valor/FCEL.pkl'>
[*********************100%***********************]  1 of 1 completed

         Date    Open    High     Low   Close    Adj Close  Volume
0  1992-06-25  6570.0  6660.0  6480.0  6570.0  6564.136719     259
1  1992-06-26  6570.0  6570.0  6480.0  6480.0  6474.216797     184
2  1992-06-29  6480.0  6570.0  6480.0  6570.0  6564.136719      43
3  1992-06-30  6570.0  6570.0  6480.0  6480.0  6474.216797      72
4  1992-07-01  6480.0  6570.0  6480.0  6570.0  6564.136719      49

            Date   Open   High   Low  Close  Adj Close   Volume
8197  2025-01-15  10.17  10.25  9.70   9.79       9.79  1030500
8198  2025-01-16   9.75   9.89  9.42   9.68       9.68   752000
8199  2025-01-17   9.79   9.88  9.33   9.59       9.59   934700
8200  2025-01-21   9.56   9.62  8.55   8.98       8.98  1600300
8201  2025-01-22   9.50   9.50  8.81   8.95       8.95  2035300

DVA DaVita Inc.
Rescate en ../Cofre/Valor/ DVA
../Cofre/Valor/DVA
<_io.BufferedReader name='../Cofre/Valor/DVA.pkl'>
[*********************100%***********************]  1 of 1 completed

         Date   Open   High    Low  Close  Adj Close    Volume
0  1995-10-31  3.475  4.200  3.475  4.075      4.075  15479500
1  1995-11-01  3.900  3.950  3.875  3.900      3.900   3056500
2  1995-11-02  3.950  4.225  3.900  4.175      4.175   1185500
3  1995-11-03  4.175  4.225  3.850  4.000      4.000   1823500
4  1995-11-06  3.975  4.000  3.875  3.900      3.900    339500

,Date,Open,High,Low,Close,Adj Close,Volume
7350,2025-01-15,163.300003,163.300003,160.839996,162.360001,162.360001,478600
7351,2025-01-16,163.000000,165.429993,161.759995,164.850006,164.850006,381000
7352,2025-01-17,164.899994,166.500000,164.020004,166.240005,166.240005,429800
7353,2025-01-21,167.330002,170.289993,167.000000,169.970001,169.970001,495000
7354,2025-01-22,170.470001,170.800003,167.990005,168.449997,168.449997,462400

AAPL AAPL
Rescate en ../Cofre/Valor/ AAPL
../Cofre/Valor/AAPL
<_io.BufferedReader name='../Cofre/Valor/AAPL.pkl'>
[*********************100%***********************]  1 of 1 completed

         Date      Open      High       Low     Close  Adj Close     Volume
0  1980-12-12  0.128348  0.128906  0.128348  0.128348   0.098834  469033600
1  1980-12-15  0.122210  0.122210  0.121652  0.121652   0.093678  175884800
2  1980-12-16  0.113281  0.113281  0.112723  0.112723   0.086802  105728000
3  1980-12-17  0.115513  0.116071  0.115513  0.115513   0.088951   86441600
4  1980-12-18  0.118862  0.119420  0.118862  0.118862   0.091530   73449600

,Date,Open,High,Low,Close,Adj Close,Volume
11113,2025-01-15,234.639999,238.960007,234.429993,237.869995,237.869995,39832000
11114,2025-01-16,237.350006,238.009995,228.029999,228.259995,228.259995,71759100
11115,2025-01-17,232.119995,232.289993,228.479996,229.979996,229.979996,68488300
11116,2025-01-21,224.000000,224.419998,219.380005,222.639999,222.639999,98070400
11117,2025-01-22,219.789993,224.119995,219.789993,223.830002,223.830002,64126500

DOW DOW
Rescate en ../Cofre/Valor/ DOW
../Cofre/Valor/DOW
<_io.BufferedReader name='../Cofre/Valor/DOW.pkl'>
[*********************100%***********************]  1 of 1 completed

         Date       Open       High        Low      Close  Adj Close   Volume
0  2019-03-20  52.750000  53.500000  49.500000  49.799999  36.684483  2350800
1  2019-03-21  49.990002  50.000000  48.200001  48.980000  36.080444  1764700
2  2019-03-22  48.799999  49.950001  48.160000  48.599998  35.800518   844700
3  2019-03-25  48.599998  49.400002  48.000000  49.150002  36.205677   440900
4  2019-03-26  49.000000  49.750000  48.180000  48.849998  35.984673   504700

,Date,Open,High,Low,Close,Adj Close,Volume
1465,2025-01-15,40.480000,40.770000,40.139999,40.400002,40.400002,5446400
1466,2025-01-16,40.330002,41.049999,40.099998,40.869999,40.869999,5812300
1467,2025-01-17,41.110001,41.380001,40.985001,41.040001,41.040001,6194800
1468,2025-01-21,41.320000,41.759998,41.150002,41.580002,41.580002,5583600
1469,2025-01-22,41.400002,41.465000,40.810001,40.820000,40.820000,5607300

WMT Walmart
Rescate en ../Cofre/Valor/ WMT
../Cofre/Valor/WMT
<_io.BufferedReader name='../Cofre/Valor/WMT.pkl'>
[*********************100%***********************]  1 of 1 completed

         Date      Open      High       Low     Close  Adj Close   Volume
0  1972-08-25  0.021159  0.021566  0.021159  0.021484   0.011639  7526400
1  1972-08-28  0.021484  0.021647  0.021403  0.021403   0.011595  2918400
2  1972-08-29  0.021322  0.021322  0.021159  0.021159   0.011463  5836800
3  1972-08-30  0.021159  0.021159  0.020996  0.021159   0.011463  1228800
4  1972-08-31  0.020996  0.020996  0.020833  0.020833   0.011286  2611200

,Date,Open,High,Low,Close,Adj Close,Volume
13207,2025-01-15,91.070000,91.730003,90.809998,91.339996,91.339996,17348200
13208,2025-01-16,91.500000,91.720001,90.120003,91.300003,91.300003,13267700
13209,2025-01-17,92.070000,92.260002,91.050003,91.940002,91.940002,15868200
13210,2025-01-21,92.480003,94.239998,92.309998,93.080002,93.080002,23247500
13211,2025-01-22,93.769997,94.000000,92.519997,93.230003,93.230003,15567100

TSLA Tesla
Rescate en ../Cofre/Valor/ TSLA
../Cofre/Valor/TSLA
<_io.BufferedReader name='../Cofre/Valor/TSLA.pkl'>
[*********************100%***********************]  1 of 1 completed

         Date      Open      High       Low     Close  Adj Close     Volume
0  2010-06-29  1.266667  1.666667  1.169333  1.592667   1.592667  281494500
1  2010-06-30  1.719333  2.028000  1.553333  1.588667   1.588667  257806500
2  2010-07-01  1.666667  1.728000  1.351333  1.464000   1.464000  123282000
3  2010-07-02  1.533333  1.540000  1.247333  1.280000   1.280000   77097000
4  2010-07-06  1.333333  1.333333  1.055333  1.074000   1.074000  103003500

,Date,Open,High,Low,Close,Adj Close,Volume
3660,2025-01-15,409.899994,429.799988,405.660004,428.220001,428.220001,81375500
3661,2025-01-16,423.489990,424.000000,409.130005,413.820007,413.820007,68335200
3662,2025-01-17,421.500000,439.739990,419.750000,426.500000,426.500000,94991400
3663,2025-01-21,432.640015,433.200012,406.309998,424.070007,424.070007,87320900
3664,2025-01-22,416.809998,428.000000,414.589996,415.109985,415.109985,60963300

AMZN Amazon
Rescate en ../Cofre/Valor/ AMZN
../Cofre/Valor/AMZN
<_io.BufferedReader name='../Cofre/Valor/AMZN.pkl'>
[*********************100%***********************]  1 of 1 completed

         Date      Open      High       Low     Close  Adj Close      Volume
0  1997-05-15  0.121875  0.125000  0.096354  0.097917   0.097917  1443120000
1  1997-05-16  0.098438  0.098958  0.085417  0.086458   0.086458   294000000
2  1997-05-19  0.088021  0.088542  0.081250  0.085417   0.085417   122136000
3  1997-05-20  0.086458  0.087500  0.081771  0.081771   0.081771   109344000
4  1997-05-21  0.081771  0.082292  0.068750  0.071354   0.071354   377064000

,Date,Open,High,Low,Close,Adj Close,Volume
6961,2025-01-15,222.830002,223.570007,220.750000,223.350006,223.350006,31291300
6962,2025-01-16,224.419998,224.649994,220.309998,220.660004,220.660004,24757300
6963,2025-01-17,225.839996,226.509995,223.080002,225.940002,225.940002,42370100
6964,2025-01-21,228.899994,231.779999,226.940002,230.710007,230.710007,39951500
6965,2025-01-22,232.020004,235.440002,231.190002,235.009995,235.009995,41448200

BRK-A Berkshire Hathaway
Rescate en ../Cofre/Valor/ BRK-A
../Cofre/Valor/BRK-A
<_io.BufferedReader name='../Cofre/Valor/BRK-A.pkl'>
[*********************100%***********************]  1 of 1 completed

         Date   Open   High    Low  Close  Adj Close  Volume
0  1980-03-17  290.0  310.0  290.0  290.0      290.0   10000
1  1980-03-18  290.0  290.0  290.0  290.0      290.0       0
2  1980-03-19  290.0  310.0  290.0  290.0      290.0   20000
3  1980-03-20  290.0  290.0  290.0  290.0      290.0       0
4  1980-03-21  290.0  290.0  290.0  290.0      290.0       0

             Date      Open      High       Low     Close  Adj Close  Volume
11301  2025-01-15  683047.0  688507.0  680500.0  688500.0   688500.0    1200
11302  2025-01-16  687763.0  694487.0  685626.0  692904.0   692904.0    1100
11303  2025-01-17  697790.0  705000.0  693770.0  702760.0   702760.0    1600
11304  2025-01-21  706486.0  709487.0  701569.0  702553.0   702553.0    2600
11305  2025-01-22  702701.0  703052.0  682640.0  691500.0   691500.0    1900

# Módulo feed

In [36]:
# input: df (self.adj_data)
#        configuraciones
#        módulo: que genera cada una de las POF (Portion of food)

# output: df_output de la forma: DATE | NAME | X


#df_data = valor.adj_data
#df_data

## Fibonacci

In [37]:
from Clase_Valor_240902 import generate_fibonacci

## FIBONACCI
name = 'Fibonacci'

#iteradores para este POF
lista_n_datos_fibonacci = [20, 50, 80, 100, 150, 200, 300] # periodos hacia atrás
modos_vela = ['cuerpo', 'sombra']

continuar_si_hay_menos = True # Si no hay suficientes datos, se continua con el siguiente y no se considera el registro (ej, si se pide Fibo 50 y solo hay 40 datos, entonces no aparece el registro)
configuraciones = {'diccionario_combinaciones': {'n_datos': lista_n_datos_fibonacci, 'modo_vela': modos_vela}, 'iteradores': ['n_datos', 'modo_vela'], 'incluir_dates_en_iterar': False, 'df_explicito': pd.DataFrame(), 'continuar_si_hay_menos': continuar_si_hay_menos}

modulo = generate_fibonacci
    
for i in range(len(df_activos)):
    simbolo, nombre = df_activos.loc[i]
    print(simbolo, nombre)
    valor = Valor(simbolo, nombre, cofre, saving_step, output = output) # Si no existe el objeto, se crea
    valor.crear_POF(name, configuraciones, modulo)

BTC-USD Bitcoin
Rescate en ../Cofre/Valor/ BTC-USD
../Cofre/Valor/BTC-USD
<_io.BufferedReader name='../Cofre/Valor/BTC-USD.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

   n_datos modo_vela
0       20    cuerpo

  7%|▋         | 1/14 [00:00<00:01,  7.43it/s]

   n_datos modo_vela
0       20    sombra

 14%|█▍        | 2/14 [00:00<00:01,  8.55it/s]

   n_datos modo_vela
0       50    cuerpo

   n_datos modo_vela
0       50    sombra

 29%|██▊       | 4/14 [00:00<00:00, 10.06it/s]

   n_datos modo_vela
0       80    cuerpo

 36%|███▌      | 5/14 [00:00<00:00,  9.96it/s]

   n_datos modo_vela
0       80    sombra

 43%|████▎     | 6/14 [00:00<00:00,  9.83it/s]

   n_datos modo_vela
0      100    cuerpo

 50%|█████     | 7/14 [00:00<00:00,  8.55it/s]

   n_datos modo_vela
0      100    sombra

 57%|█████▋    | 8/14 [00:00<00:00,  7.40it/s]

   n_datos modo_vela
0      150    cuerpo

 64%|██████▍   | 9/14 [00:01<00:00,  7.94it/s]

   n_datos modo_vela
0      150    sombra

 71%|███████▏  | 10/14 [00:01<00:00,  8.41it/s]

   n_datos modo_vela
0      200    cuerpo

   n_datos modo_vela
0      200    sombra

 86%|████████▌ | 12/14 [00:01<00:00,  9.46it/s]

   n_datos modo_vela
0      300    cuerpo

   n_datos modo_vela
0      300    sombra

100%|██████████| 14/14 [00:02<00:00,  5.40it/s]

GUARDAR





NFLX Netflix, Inc.
Rescate en ../Cofre/Valor/ NFLX
../Cofre/Valor/NFLX
<_io.BufferedReader name='../Cofre/Valor/NFLX.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

   n_datos modo_vela
0       20    cuerpo

  7%|▋         | 1/14 [00:00<00:01,  6.78it/s]

   n_datos modo_vela
0       20    sombra

 14%|█▍        | 2/14 [00:00<00:01,  6.93it/s]

   n_datos modo_vela
0       50    cuerpo

 21%|██▏       | 3/14 [00:00<00:01,  7.05it/s]

   n_datos modo_vela
0       50    sombra

 29%|██▊       | 4/14 [00:00<00:01,  6.03it/s]

   n_datos modo_vela
0       80    cuerpo

 36%|███▌      | 5/14 [00:00<00:01,  6.40it/s]

   n_datos modo_vela
0       80    sombra

 43%|████▎     | 6/14 [00:00<00:01,  6.70it/s]

   n_datos modo_vela
0      100    cuerpo

 50%|█████     | 7/14 [00:01<00:01,  6.73it/s]

   n_datos modo_vela
0      100    sombra

 57%|█████▋    | 8/14 [00:01<00:00,  6.89it/s]

   n_datos modo_vela
0      150    cuerpo

 64%|██████▍   | 9/14 [00:01<00:00,  6.94it/s]

   n_datos modo_vela
0      150    sombra

 71%|███████▏  | 10/14 [00:01<00:00,  7.15it/s]

   n_datos modo_vela
0      200    cuerpo

 79%|███████▊  | 11/14 [00:01<00:00,  7.48it/s]

   n_datos modo_vela
0      200    sombra

 86%|████████▌ | 12/14 [00:01<00:00,  7.62it/s]

   n_datos modo_vela
0      300    cuerpo

 93%|█████████▎| 13/14 [00:01<00:00,  7.91it/s]

   n_datos modo_vela
0      300    sombra

100%|██████████| 14/14 [00:03<00:00,  3.79it/s]

GUARDAR





FCEL FuelCell Energy, Inc.
Rescate en ../Cofre/Valor/ FCEL
../Cofre/Valor/FCEL
<_io.BufferedReader name='../Cofre/Valor/FCEL.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

   n_datos modo_vela
0       20    cuerpo

  7%|▋         | 1/14 [00:00<00:02,  5.67it/s]

   n_datos modo_vela
0       20    sombra

 14%|█▍        | 2/14 [00:00<00:02,  5.45it/s]

   n_datos modo_vela
0       50    cuerpo

 21%|██▏       | 3/14 [00:00<00:02,  4.79it/s]

   n_datos modo_vela
0       50    sombra

 29%|██▊       | 4/14 [00:00<00:02,  4.94it/s]

   n_datos modo_vela
0       80    cuerpo

 36%|███▌      | 5/14 [00:01<00:01,  4.88it/s]

   n_datos modo_vela
0       80    sombra

 43%|████▎     | 6/14 [00:01<00:01,  5.19it/s]

   n_datos modo_vela
0      100    cuerpo

 50%|█████     | 7/14 [00:01<00:01,  5.42it/s]

   n_datos modo_vela
0      100    sombra

 57%|█████▋    | 8/14 [00:01<00:01,  5.69it/s]

   n_datos modo_vela
0      150    cuerpo

 64%|██████▍   | 9/14 [00:01<00:00,  5.66it/s]

   n_datos modo_vela
0      150    sombra

 71%|███████▏  | 10/14 [00:01<00:00,  5.74it/s]

   n_datos modo_vela
0      200    cuerpo

 79%|███████▊  | 11/14 [00:02<00:00,  5.67it/s]

   n_datos modo_vela
0      200    sombra

 86%|████████▌ | 12/14 [00:02<00:00,  5.62it/s]

   n_datos modo_vela
0      300    cuerpo

 93%|█████████▎| 13/14 [00:02<00:00,  5.68it/s]

   n_datos modo_vela
0      300    sombra

100%|██████████| 14/14 [00:04<00:00,  2.92it/s]

GUARDAR





DVA DaVita Inc.
Rescate en ../Cofre/Valor/ DVA
../Cofre/Valor/DVA
<_io.BufferedReader name='../Cofre/Valor/DVA.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

   n_datos modo_vela
0       20    cuerpo

  7%|▋         | 1/14 [00:00<00:01,  6.56it/s]

   n_datos modo_vela
0       20    sombra

 14%|█▍        | 2/14 [00:00<00:01,  6.71it/s]

   n_datos modo_vela
0       50    cuerpo

 21%|██▏       | 3/14 [00:00<00:01,  6.61it/s]

   n_datos modo_vela
0       50    sombra

 29%|██▊       | 4/14 [00:00<00:01,  6.33it/s]

   n_datos modo_vela
0       80    cuerpo

 36%|███▌      | 5/14 [00:00<00:01,  6.11it/s]

   n_datos modo_vela
0       80    sombra

 43%|████▎     | 6/14 [00:00<00:01,  5.97it/s]

   n_datos modo_vela
0      100    cuerpo

 50%|█████     | 7/14 [00:01<00:01,  6.15it/s]

   n_datos modo_vela
0      100    sombra

 57%|█████▋    | 8/14 [00:01<00:00,  6.17it/s]

   n_datos modo_vela
0      150    cuerpo

 64%|██████▍   | 9/14 [00:01<00:00,  6.23it/s]

   n_datos modo_vela
0      150    sombra

 71%|███████▏  | 10/14 [00:01<00:00,  6.25it/s]

   n_datos modo_vela
0      200    cuerpo

 79%|███████▊  | 11/14 [00:01<00:00,  6.49it/s]

   n_datos modo_vela
0      200    sombra

 86%|████████▌ | 12/14 [00:01<00:00,  6.51it/s]

   n_datos modo_vela
0      300    cuerpo

 93%|█████████▎| 13/14 [00:02<00:00,  6.71it/s]

   n_datos modo_vela
0      300    sombra

100%|██████████| 14/14 [00:04<00:00,  3.35it/s]

GUARDAR





AAPL AAPL
Rescate en ../Cofre/Valor/ AAPL
../Cofre/Valor/AAPL
<_io.BufferedReader name='../Cofre/Valor/AAPL.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

   n_datos modo_vela
0       20    cuerpo

  7%|▋         | 1/14 [00:00<00:02,  4.44it/s]

   n_datos modo_vela
0       20    sombra

 14%|█▍        | 2/14 [00:00<00:02,  4.73it/s]

   n_datos modo_vela
0       50    cuerpo

 21%|██▏       | 3/14 [00:00<00:02,  4.59it/s]

   n_datos modo_vela
0       50    sombra

 29%|██▊       | 4/14 [00:00<00:02,  4.69it/s]

   n_datos modo_vela
0       80    cuerpo

 36%|███▌      | 5/14 [00:01<00:01,  4.86it/s]

   n_datos modo_vela
0       80    sombra

 43%|████▎     | 6/14 [00:01<00:01,  4.95it/s]

   n_datos modo_vela
0      100    cuerpo

 50%|█████     | 7/14 [00:01<00:01,  5.00it/s]

   n_datos modo_vela
0      100    sombra

 57%|█████▋    | 8/14 [00:01<00:01,  4.86it/s]

   n_datos modo_vela
0      150    cuerpo

 64%|██████▍   | 9/14 [00:01<00:01,  4.71it/s]

   n_datos modo_vela
0      150    sombra

 71%|███████▏  | 10/14 [00:02<00:00,  4.82it/s]

   n_datos modo_vela
0      200    cuerpo

 79%|███████▊  | 11/14 [00:02<00:00,  4.93it/s]

   n_datos modo_vela
0      200    sombra

 86%|████████▌ | 12/14 [00:02<00:00,  4.85it/s]

   n_datos modo_vela
0      300    cuerpo

 93%|█████████▎| 13/14 [00:02<00:00,  4.85it/s]

   n_datos modo_vela
0      300    sombra

100%|██████████| 14/14 [00:05<00:00,  2.43it/s]

GUARDAR





DOW DOW
Rescate en ../Cofre/Valor/ DOW
../Cofre/Valor/DOW
<_io.BufferedReader name='../Cofre/Valor/DOW.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

   n_datos modo_vela
0       20    cuerpo

   n_datos modo_vela
0       20    sombra

   n_datos modo_vela
0       50    cuerpo

 21%|██▏       | 3/14 [00:00<00:00, 23.68it/s]

   n_datos modo_vela
0       50    sombra

   n_datos modo_vela
0       80    cuerpo

   n_datos modo_vela
0       80    sombra

 43%|████▎     | 6/14 [00:00<00:00, 24.60it/s]

   n_datos modo_vela
0      100    cuerpo

   n_datos modo_vela
0      100    sombra

   n_datos modo_vela
0      150    cuerpo

 64%|██████▍   | 9/14 [00:00<00:00, 23.57it/s]

   n_datos modo_vela
0      150    sombra

   n_datos modo_vela
0      200    cuerpo

   n_datos modo_vela
0      200    sombra

 86%|████████▌ | 12/14 [00:00<00:00, 24.00it/s]

   n_datos modo_vela
0      300    cuerpo

   n_datos modo_vela
0      300    sombra

100%|██████████| 14/14 [00:01<00:00, 13.89it/s]

GUARDAR





WMT Walmart
Rescate en ../Cofre/Valor/ WMT
../Cofre/Valor/WMT
<_io.BufferedReader name='../Cofre/Valor/WMT.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

   n_datos modo_vela
0       20    cuerpo

  7%|▋         | 1/14 [00:00<00:05,  2.47it/s]

   n_datos modo_vela
0       20    sombra

 14%|█▍        | 2/14 [00:00<00:03,  3.10it/s]

   n_datos modo_vela
0       50    cuerpo

 21%|██▏       | 3/14 [00:00<00:03,  3.51it/s]

   n_datos modo_vela
0       50    sombra

 29%|██▊       | 4/14 [00:01<00:02,  3.80it/s]

   n_datos modo_vela
0       80    cuerpo

 36%|███▌      | 5/14 [00:01<00:02,  3.87it/s]

   n_datos modo_vela
0       80    sombra

 43%|████▎     | 6/14 [00:01<00:02,  3.84it/s]

   n_datos modo_vela
0      100    cuerpo

 50%|█████     | 7/14 [00:01<00:01,  3.87it/s]

   n_datos modo_vela
0      100    sombra

 57%|█████▋    | 8/14 [00:02<00:01,  3.76it/s]

   n_datos modo_vela
0      150    cuerpo

 64%|██████▍   | 9/14 [00:02<00:01,  3.84it/s]

   n_datos modo_vela
0      150    sombra

 71%|███████▏  | 10/14 [00:02<00:00,  4.02it/s]

   n_datos modo_vela
0      200    cuerpo

 79%|███████▊  | 11/14 [00:02<00:00,  4.11it/s]

   n_datos modo_vela
0      200    sombra

 86%|████████▌ | 12/14 [00:03<00:00,  4.22it/s]

   n_datos modo_vela
0      300    cuerpo

 93%|█████████▎| 13/14 [00:03<00:00,  4.11it/s]

   n_datos modo_vela
0      300    sombra

100%|██████████| 14/14 [00:07<00:00,  1.96it/s]

GUARDAR





TSLA Tesla
Rescate en ../Cofre/Valor/ TSLA
../Cofre/Valor/TSLA
<_io.BufferedReader name='../Cofre/Valor/TSLA.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

   n_datos modo_vela
0       20    cuerpo

   n_datos modo_vela
0       20    sombra

 14%|█▍        | 2/14 [00:00<00:00, 14.49it/s]

   n_datos modo_vela
0       50    cuerpo

   n_datos modo_vela
0       50    sombra

 29%|██▊       | 4/14 [00:00<00:00, 11.93it/s]

   n_datos modo_vela
0       80    cuerpo

   n_datos modo_vela
0       80    sombra

 43%|████▎     | 6/14 [00:00<00:00, 11.24it/s]

   n_datos modo_vela
0      100    cuerpo

   n_datos modo_vela
0      100    sombra

 57%|█████▋    | 8/14 [00:00<00:00, 11.43it/s]

   n_datos modo_vela
0      150    cuerpo

   n_datos modo_vela
0      150    sombra

 71%|███████▏  | 10/14 [00:00<00:00, 11.50it/s]

   n_datos modo_vela
0      200    cuerpo

   n_datos modo_vela
0      200    sombra

 86%|████████▌ | 12/14 [00:01<00:00, 11.46it/s]

   n_datos modo_vela
0      300    cuerpo

   n_datos modo_vela
0      300    sombra

100%|██████████| 14/14 [00:02<00:00,  6.15it/s]

GUARDAR





AMZN Amazon
Rescate en ../Cofre/Valor/ AMZN
../Cofre/Valor/AMZN
<_io.BufferedReader name='../Cofre/Valor/AMZN.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

   n_datos modo_vela
0       20    cuerpo

  7%|▋         | 1/14 [00:00<00:01,  7.89it/s]

   n_datos modo_vela
0       20    sombra

 14%|█▍        | 2/14 [00:00<00:01,  7.51it/s]

   n_datos modo_vela
0       50    cuerpo

 21%|██▏       | 3/14 [00:00<00:01,  7.13it/s]

   n_datos modo_vela
0       50    sombra

 29%|██▊       | 4/14 [00:00<00:01,  7.25it/s]

   n_datos modo_vela
0       80    cuerpo

 36%|███▌      | 5/14 [00:00<00:01,  7.23it/s]

   n_datos modo_vela
0       80    sombra

 43%|████▎     | 6/14 [00:00<00:01,  7.23it/s]

   n_datos modo_vela
0      100    cuerpo

 50%|█████     | 7/14 [00:00<00:00,  7.13it/s]

   n_datos modo_vela
0      100    sombra

 57%|█████▋    | 8/14 [00:01<00:00,  7.31it/s]

   n_datos modo_vela
0      150    cuerpo

 64%|██████▍   | 9/14 [00:01<00:00,  7.38it/s]

   n_datos modo_vela
0      150    sombra

 71%|███████▏  | 10/14 [00:01<00:00,  7.59it/s]

   n_datos modo_vela
0      200    cuerpo

 79%|███████▊  | 11/14 [00:01<00:00,  7.94it/s]

   n_datos modo_vela
0      200    sombra

 86%|████████▌ | 12/14 [00:01<00:00,  7.96it/s]

   n_datos modo_vela
0      300    cuerpo

 93%|█████████▎| 13/14 [00:01<00:00,  7.81it/s]

   n_datos modo_vela
0      300    sombra

100%|██████████| 14/14 [00:03<00:00,  3.80it/s]

GUARDAR





BRK-A Berkshire Hathaway
Rescate en ../Cofre/Valor/ BRK-A
../Cofre/Valor/BRK-A
<_io.BufferedReader name='../Cofre/Valor/BRK-A.pkl'>
COMENTAR FUNCION!!!!

generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/14 [00:00<?, ?it/s]

   n_datos modo_vela
0       20    cuerpo

  7%|▋         | 1/14 [00:00<00:03,  3.46it/s]

   n_datos modo_vela
0       20    sombra

 14%|█▍        | 2/14 [00:00<00:03,  3.78it/s]

   n_datos modo_vela
0       50    cuerpo

 21%|██▏       | 3/14 [00:00<00:02,  3.93it/s]

   n_datos modo_vela
0       50    sombra

 29%|██▊       | 4/14 [00:00<00:02,  4.18it/s]

   n_datos modo_vela
0       80    cuerpo

 36%|███▌      | 5/14 [00:01<00:02,  4.32it/s]

   n_datos modo_vela
0       80    sombra

 43%|████▎     | 6/14 [00:01<00:01,  4.30it/s]

   n_datos modo_vela
0      100    cuerpo

 50%|█████     | 7/14 [00:01<00:01,  4.40it/s]

   n_datos modo_vela
0      100    sombra

 57%|█████▋    | 8/14 [00:01<00:01,  4.31it/s]

   n_datos modo_vela
0      150    cuerpo

 64%|██████▍   | 9/14 [00:02<00:01,  4.34it/s]

   n_datos modo_vela
0      150    sombra

 71%|███████▏  | 10/14 [00:02<00:00,  4.61it/s]

   n_datos modo_vela
0      200    cuerpo

 79%|███████▊  | 11/14 [00:02<00:00,  4.70it/s]

   n_datos modo_vela
0      200    sombra

 86%|████████▌ | 12/14 [00:02<00:00,  4.80it/s]

   n_datos modo_vela
0      300    cuerpo

 93%|█████████▎| 13/14 [00:02<00:00,  4.81it/s]

   n_datos modo_vela
0      300    sombra

100%|██████████| 14/14 [00:06<00:00,  2.27it/s]

GUARDAR

## Media Móvil

In [38]:
from Clase_Valor_240902 import generate_media_movil

name = 'Media_Movil'

#iteradores para este POF
lista_n_datos_media_movil = [3, 4, 5, 10, 20, 30, 50, 80, 100, 120, 150, 200, 250, 300] # periodos hacia atrás
campos_media_movil = ['Close', 'rendimiento']

continuar_si_hay_menos = True

#configuraciones = {'diccionario_combinaciones': {'n_datos': lista_n_datos_fibonacci, 'modo_vela': modos_vela}, 'iteradores': ['n_datos', 'modo_vela'], 'incluir_dates_en_iterar': False, 'df_explicito': pd.DataFrame(), 'continuar_si_hay_menos': continuar_si_hay_menos}
configuraciones = {'diccionario_combinaciones': {'n_datos': lista_n_datos_media_movil, 'campo': campos_media_movil}, 'iteradores': ['n_datos', 'campo'], 'incluir_dates_en_iterar': False, 'df_explicito': pd.DataFrame(), 'continuar_si_hay_menos': continuar_si_hay_menos}

modulo = generate_media_movil

for i in range(len(df_activos)):
    simbolo, nombre = df_activos.loc[i]
    print(simbolo, nombre)
    valor = Valor(simbolo, nombre, cofre, saving_step, output = output) # Si no existe el objeto, se crea
    
    #display(valor.adj_data)
    valor.crear_POF(name, configuraciones, modulo)

BTC-USD Bitcoin
Rescate en ../Cofre/Valor/ BTC-USD
../Cofre/Valor/BTC-USD
<_io.BufferedReader name='../Cofre/Valor/BTC-USD.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/28 [00:00<?, ?it/s]

   n_datos  campo
0        3  Close

  4%|▎         | 1/28 [00:00<00:03,  8.72it/s]

   n_datos        campo
0        3  rendimiento

  7%|▋         | 2/28 [00:00<00:02,  9.09it/s]

   n_datos  campo
0        4  Close

 11%|█         | 3/28 [00:00<00:02,  9.10it/s]

   n_datos        campo
0        4  rendimiento

   n_datos  campo
0        5  Close

 18%|█▊        | 5/28 [00:00<00:02, 10.21it/s]

   n_datos        campo
0        5  rendimiento

 21%|██▏       | 6/28 [00:00<00:02,  9.74it/s]

   n_datos  campo
0       10  Close

 25%|██▌       | 7/28 [00:00<00:02,  9.50it/s]

   n_datos        campo
0       10  rendimiento

 29%|██▊       | 8/28 [00:00<00:02,  9.31it/s]

   n_datos  campo
0       20  Close

   n_datos        campo
0       20  rendimiento

 36%|███▌      | 10/28 [00:01<00:01,  9.75it/s]

   n_datos  campo
0       30  Close

   n_datos        campo
0       30  rendimiento

 43%|████▎     | 12/28 [00:01<00:01,  9.67it/s]

   n_datos  campo
0       50  Close

   n_datos        campo
0       50  rendimiento

 50%|█████     | 14/28 [00:01<00:01, 10.12it/s]

   n_datos  campo
0       80  Close

   n_datos        campo
0       80  rendimiento

 57%|█████▋    | 16/28 [00:01<00:01, 10.48it/s]

   n_datos  campo
0      100  Close

   n_datos        campo
0      100  rendimiento

 64%|██████▍   | 18/28 [00:01<00:00, 10.70it/s]

   n_datos  campo
0      120  Close

   n_datos        campo
0      120  rendimiento

 71%|███████▏  | 20/28 [00:01<00:00, 10.37it/s]

   n_datos  campo
0      150  Close

   n_datos        campo
0      150  rendimiento

 79%|███████▊  | 22/28 [00:02<00:00, 10.51it/s]

   n_datos  campo
0      200  Close

   n_datos        campo
0      200  rendimiento

 86%|████████▌ | 24/28 [00:02<00:00, 10.10it/s]

   n_datos  campo
0      250  Close

   n_datos        campo
0      250  rendimiento

 93%|█████████▎| 26/28 [00:02<00:00,  9.62it/s]

   n_datos  campo
0      300  Close

   n_datos        campo
0      300  rendimiento

100%|██████████| 28/28 [00:03<00:00,  7.25it/s]

GUARDAR





NFLX Netflix, Inc.
Rescate en ../Cofre/Valor/ NFLX
../Cofre/Valor/NFLX
<_io.BufferedReader name='../Cofre/Valor/NFLX.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/28 [00:00<?, ?it/s]

   n_datos  campo
0        3  Close

  4%|▎         | 1/28 [00:00<00:03,  8.88it/s]

   n_datos        campo
0        3  rendimiento

  7%|▋         | 2/28 [00:00<00:03,  7.78it/s]

   n_datos  campo
0        4  Close

 11%|█         | 3/28 [00:00<00:03,  7.27it/s]

   n_datos        campo
0        4  rendimiento

 14%|█▍        | 4/28 [00:00<00:03,  7.19it/s]

   n_datos  campo
0        5  Close

 18%|█▊        | 5/28 [00:00<00:03,  7.14it/s]

   n_datos        campo
0        5  rendimiento

 21%|██▏       | 6/28 [00:00<00:03,  7.27it/s]

   n_datos  campo
0       10  Close

 25%|██▌       | 7/28 [00:00<00:02,  7.36it/s]

   n_datos        campo
0       10  rendimiento

 29%|██▊       | 8/28 [00:01<00:02,  7.35it/s]

   n_datos  campo
0       20  Close

 32%|███▏      | 9/28 [00:01<00:02,  7.39it/s]

   n_datos        campo
0       20  rendimiento

 36%|███▌      | 10/28 [00:01<00:02,  7.22it/s]

   n_datos  campo
0       30  Close

 39%|███▉      | 11/28 [00:01<00:02,  6.66it/s]

   n_datos        campo
0       30  rendimiento

 43%|████▎     | 12/28 [00:01<00:02,  6.75it/s]

   n_datos  campo
0       50  Close

 46%|████▋     | 13/28 [00:01<00:02,  6.87it/s]

   n_datos        campo
0       50  rendimiento

 50%|█████     | 14/28 [00:01<00:01,  7.17it/s]

   n_datos  campo
0       80  Close

 54%|█████▎    | 15/28 [00:02<00:01,  7.29it/s]

   n_datos        campo
0       80  rendimiento

 57%|█████▋    | 16/28 [00:02<00:01,  7.19it/s]

   n_datos  campo
0      100  Close

 61%|██████    | 17/28 [00:02<00:01,  7.24it/s]

   n_datos        campo
0      100  rendimiento

 64%|██████▍   | 18/28 [00:02<00:01,  6.91it/s]

   n_datos  campo
0      120  Close

 68%|██████▊   | 19/28 [00:02<00:01,  6.93it/s]

   n_datos        campo
0      120  rendimiento

 71%|███████▏  | 20/28 [00:02<00:01,  6.92it/s]

   n_datos  campo
0      150  Close

 75%|███████▌  | 21/28 [00:02<00:01,  6.99it/s]

   n_datos        campo
0      150  rendimiento

 79%|███████▊  | 22/28 [00:03<00:00,  7.09it/s]

   n_datos  campo
0      200  Close

 82%|████████▏ | 23/28 [00:03<00:00,  7.30it/s]

   n_datos        campo
0      200  rendimiento

 86%|████████▌ | 24/28 [00:03<00:00,  7.47it/s]

   n_datos  campo
0      250  Close

 89%|████████▉ | 25/28 [00:03<00:00,  7.37it/s]

   n_datos        campo
0      250  rendimiento

 93%|█████████▎| 26/28 [00:03<00:00,  7.52it/s]

   n_datos  campo
0      300  Close

 96%|█████████▋| 27/28 [00:03<00:00,  7.25it/s]

   n_datos        campo
0      300  rendimiento

100%|██████████| 28/28 [00:05<00:00,  5.14it/s]

GUARDAR





FCEL FuelCell Energy, Inc.
Rescate en ../Cofre/Valor/ FCEL
../Cofre/Valor/FCEL
<_io.BufferedReader name='../Cofre/Valor/FCEL.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/28 [00:00<?, ?it/s]

   n_datos  campo
0        3  Close

  4%|▎         | 1/28 [00:00<00:04,  6.04it/s]

   n_datos        campo
0        3  rendimiento

  7%|▋         | 2/28 [00:00<00:04,  5.98it/s]

   n_datos  campo
0        4  Close

 11%|█         | 3/28 [00:00<00:04,  5.99it/s]

   n_datos        campo
0        4  rendimiento

 14%|█▍        | 4/28 [00:00<00:04,  5.87it/s]

   n_datos  campo
0        5  Close

 18%|█▊        | 5/28 [00:00<00:04,  5.62it/s]

   n_datos        campo
0        5  rendimiento

 21%|██▏       | 6/28 [00:01<00:04,  4.74it/s]

   n_datos  campo
0       10  Close

 25%|██▌       | 7/28 [00:01<00:04,  5.03it/s]

   n_datos        campo
0       10  rendimiento

 29%|██▊       | 8/28 [00:01<00:03,  5.19it/s]

   n_datos  campo
0       20  Close

 32%|███▏      | 9/28 [00:01<00:03,  5.36it/s]

   n_datos        campo
0       20  rendimiento

 36%|███▌      | 10/28 [00:01<00:03,  4.99it/s]

   n_datos  campo
0       30  Close

 39%|███▉      | 11/28 [00:02<00:03,  4.91it/s]

   n_datos        campo
0       30  rendimiento

 43%|████▎     | 12/28 [00:02<00:03,  5.09it/s]

   n_datos  campo
0       50  Close

 46%|████▋     | 13/28 [00:02<00:02,  5.33it/s]

   n_datos        campo
0       50  rendimiento

 50%|█████     | 14/28 [00:02<00:02,  5.42it/s]

   n_datos  campo
0       80  Close

 54%|█████▎    | 15/28 [00:02<00:02,  5.17it/s]

   n_datos        campo
0       80  rendimiento

 57%|█████▋    | 16/28 [00:03<00:02,  5.21it/s]

   n_datos  campo
0      100  Close

 61%|██████    | 17/28 [00:03<00:02,  5.39it/s]

   n_datos        campo
0      100  rendimiento

 64%|██████▍   | 18/28 [00:03<00:01,  5.46it/s]

   n_datos  campo
0      120  Close

 68%|██████▊   | 19/28 [00:03<00:01,  5.38it/s]

   n_datos        campo
0      120  rendimiento

 71%|███████▏  | 20/28 [00:03<00:01,  5.38it/s]

   n_datos  campo
0      150  Close

 75%|███████▌  | 21/28 [00:03<00:01,  5.11it/s]

   n_datos        campo
0      150  rendimiento

 79%|███████▊  | 22/28 [00:04<00:01,  4.31it/s]

   n_datos  campo
0      200  Close

 82%|████████▏ | 23/28 [00:04<00:01,  4.64it/s]

   n_datos        campo
0      200  rendimiento

 86%|████████▌ | 24/28 [00:04<00:00,  4.86it/s]

   n_datos  campo
0      250  Close

 89%|████████▉ | 25/28 [00:04<00:00,  4.99it/s]

   n_datos        campo
0      250  rendimiento

 93%|█████████▎| 26/28 [00:05<00:00,  5.01it/s]

   n_datos  campo
0      300  Close

 96%|█████████▋| 27/28 [00:05<00:00,  4.76it/s]

   n_datos        campo
0      300  rendimiento

100%|██████████| 28/28 [00:07<00:00,  3.67it/s]

GUARDAR





DVA DaVita Inc.
Rescate en ../Cofre/Valor/ DVA
../Cofre/Valor/DVA
<_io.BufferedReader name='../Cofre/Valor/DVA.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/28 [00:00<?, ?it/s]

   n_datos  campo
0        3  Close

  4%|▎         | 1/28 [00:00<00:04,  5.93it/s]

   n_datos        campo
0        3  rendimiento

  7%|▋         | 2/28 [00:00<00:04,  6.22it/s]

   n_datos  campo
0        4  Close

 11%|█         | 3/28 [00:00<00:03,  6.26it/s]

   n_datos        campo
0        4  rendimiento

 14%|█▍        | 4/28 [00:00<00:03,  6.07it/s]

   n_datos  campo
0        5  Close

 18%|█▊        | 5/28 [00:00<00:03,  6.15it/s]

   n_datos        campo
0        5  rendimiento

 21%|██▏       | 6/28 [00:01<00:03,  5.60it/s]

   n_datos  campo
0       10  Close

 25%|██▌       | 7/28 [00:01<00:03,  5.74it/s]

   n_datos        campo
0       10  rendimiento

 29%|██▊       | 8/28 [00:01<00:03,  5.52it/s]

   n_datos  campo
0       20  Close

 32%|███▏      | 9/28 [00:01<00:03,  5.28it/s]

   n_datos        campo
0       20  rendimiento

 36%|███▌      | 10/28 [00:01<00:03,  5.32it/s]

   n_datos  campo
0       30  Close

 39%|███▉      | 11/28 [00:01<00:03,  5.54it/s]

   n_datos        campo
0       30  rendimiento

 43%|████▎     | 12/28 [00:02<00:02,  5.76it/s]

   n_datos  campo
0       50  Close

 46%|████▋     | 13/28 [00:02<00:02,  5.83it/s]

   n_datos        campo
0       50  rendimiento

 50%|█████     | 14/28 [00:02<00:02,  5.89it/s]

   n_datos  campo
0       80  Close

 54%|█████▎    | 15/28 [00:02<00:02,  5.88it/s]

   n_datos        campo
0       80  rendimiento

 57%|█████▋    | 16/28 [00:02<00:02,  5.78it/s]

   n_datos  campo
0      100  Close

 61%|██████    | 17/28 [00:02<00:01,  5.81it/s]

   n_datos        campo
0      100  rendimiento

 64%|██████▍   | 18/28 [00:03<00:01,  5.74it/s]

   n_datos  campo
0      120  Close

 68%|██████▊   | 19/28 [00:03<00:01,  5.75it/s]

   n_datos        campo
0      120  rendimiento

 71%|███████▏  | 20/28 [00:03<00:01,  5.84it/s]

   n_datos  campo
0      150  Close

 75%|███████▌  | 21/28 [00:03<00:01,  5.69it/s]

   n_datos        campo
0      150  rendimiento

 79%|███████▊  | 22/28 [00:03<00:01,  5.28it/s]

   n_datos  campo
0      200  Close

 82%|████████▏ | 23/28 [00:04<00:00,  5.53it/s]

   n_datos        campo
0      200  rendimiento

 86%|████████▌ | 24/28 [00:04<00:00,  5.41it/s]

   n_datos  campo
0      250  Close

 89%|████████▉ | 25/28 [00:04<00:00,  5.51it/s]

   n_datos        campo
0      250  rendimiento

 93%|█████████▎| 26/28 [00:04<00:00,  5.63it/s]

   n_datos  campo
0      300  Close

 96%|█████████▋| 27/28 [00:04<00:00,  5.73it/s]

   n_datos        campo
0      300  rendimiento

100%|██████████| 28/28 [00:06<00:00,  4.04it/s]

GUARDAR





AAPL AAPL
Rescate en ../Cofre/Valor/ AAPL
../Cofre/Valor/AAPL
<_io.BufferedReader name='../Cofre/Valor/AAPL.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/28 [00:00<?, ?it/s]

   n_datos  campo
0        3  Close

  4%|▎         | 1/28 [00:00<00:06,  4.41it/s]

   n_datos        campo
0        3  rendimiento

  7%|▋         | 2/28 [00:00<00:05,  4.72it/s]

   n_datos  campo
0        4  Close

 11%|█         | 3/28 [00:00<00:05,  4.26it/s]

   n_datos        campo
0        4  rendimiento

 14%|█▍        | 4/28 [00:00<00:05,  4.16it/s]

   n_datos  campo
0        5  Close

 18%|█▊        | 5/28 [00:01<00:05,  4.01it/s]

   n_datos        campo
0        5  rendimiento

 21%|██▏       | 6/28 [00:01<00:05,  4.21it/s]

   n_datos  campo
0       10  Close

 25%|██▌       | 7/28 [00:01<00:04,  4.28it/s]

   n_datos        campo
0       10  rendimiento

 29%|██▊       | 8/28 [00:01<00:04,  4.30it/s]

   n_datos  campo
0       20  Close

 32%|███▏      | 9/28 [00:02<00:04,  4.32it/s]

   n_datos        campo
0       20  rendimiento

 36%|███▌      | 10/28 [00:02<00:04,  4.34it/s]

   n_datos  campo
0       30  Close

 39%|███▉      | 11/28 [00:02<00:03,  4.37it/s]

   n_datos        campo
0       30  rendimiento

 43%|████▎     | 12/28 [00:02<00:03,  4.28it/s]

   n_datos  campo
0       50  Close

 46%|████▋     | 13/28 [00:03<00:03,  4.34it/s]

   n_datos        campo
0       50  rendimiento

 50%|█████     | 14/28 [00:03<00:03,  4.41it/s]

   n_datos  campo
0       80  Close

 54%|█████▎    | 15/28 [00:03<00:02,  4.42it/s]

   n_datos        campo
0       80  rendimiento

 57%|█████▋    | 16/28 [00:03<00:02,  4.27it/s]

   n_datos  campo
0      100  Close

 61%|██████    | 17/28 [00:03<00:02,  4.36it/s]

   n_datos        campo
0      100  rendimiento

 64%|██████▍   | 18/28 [00:04<00:02,  4.29it/s]

   n_datos  campo
0      120  Close

 68%|██████▊   | 19/28 [00:04<00:02,  4.27it/s]

   n_datos        campo
0      120  rendimiento

 71%|███████▏  | 20/28 [00:04<00:02,  3.56it/s]

   n_datos  campo
0      150  Close

 75%|███████▌  | 21/28 [00:05<00:01,  3.79it/s]

   n_datos        campo
0      150  rendimiento

 79%|███████▊  | 22/28 [00:05<00:01,  3.93it/s]

   n_datos  campo
0      200  Close

 82%|████████▏ | 23/28 [00:05<00:01,  4.06it/s]

   n_datos        campo
0      200  rendimiento

 86%|████████▌ | 24/28 [00:05<00:00,  4.19it/s]

   n_datos  campo
0      250  Close

 89%|████████▉ | 25/28 [00:05<00:00,  4.12it/s]

   n_datos        campo
0      250  rendimiento

 93%|█████████▎| 26/28 [00:06<00:00,  4.17it/s]

   n_datos  campo
0      300  Close

 96%|█████████▋| 27/28 [00:06<00:00,  4.26it/s]

   n_datos        campo
0      300  rendimiento

100%|██████████| 28/28 [00:09<00:00,  2.92it/s]

GUARDAR





DOW DOW
Rescate en ../Cofre/Valor/ DOW
../Cofre/Valor/DOW
<_io.BufferedReader name='../Cofre/Valor/DOW.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/28 [00:00<?, ?it/s]

   n_datos  campo
0        3  Close

   n_datos        campo
0        3  rendimiento

  7%|▋         | 2/28 [00:00<00:01, 18.22it/s]

   n_datos  campo
0        4  Close

   n_datos        campo
0        4  rendimiento

 14%|█▍        | 4/28 [00:00<00:01, 13.75it/s]

   n_datos  campo
0        5  Close

   n_datos        campo
0        5  rendimiento

 21%|██▏       | 6/28 [00:00<00:01, 13.75it/s]

   n_datos  campo
0       10  Close

   n_datos        campo
0       10  rendimiento

 29%|██▊       | 8/28 [00:00<00:01, 14.62it/s]

   n_datos  campo
0       20  Close

   n_datos        campo
0       20  rendimiento

 36%|███▌      | 10/28 [00:00<00:01, 15.97it/s]

   n_datos  campo
0       30  Close

   n_datos        campo
0       30  rendimiento

 43%|████▎     | 12/28 [00:00<00:00, 16.26it/s]

   n_datos  campo
0       50  Close

   n_datos        campo
0       50  rendimiento

 50%|█████     | 14/28 [00:00<00:00, 17.10it/s]

   n_datos  campo
0       80  Close

   n_datos        campo
0       80  rendimiento

 57%|█████▋    | 16/28 [00:00<00:00, 17.69it/s]

   n_datos  campo
0      100  Close

   n_datos        campo
0      100  rendimiento

 64%|██████▍   | 18/28 [00:01<00:00, 18.11it/s]

   n_datos  campo
0      120  Close

   n_datos        campo
0      120  rendimiento

 71%|███████▏  | 20/28 [00:01<00:00, 18.25it/s]

   n_datos  campo
0      150  Close

   n_datos        campo
0      150  rendimiento

 79%|███████▊  | 22/28 [00:01<00:00, 17.43it/s]

   n_datos  campo
0      200  Close

   n_datos        campo
0      200  rendimiento

 86%|████████▌ | 24/28 [00:01<00:00, 17.30it/s]

   n_datos  campo
0      250  Close

   n_datos        campo
0      250  rendimiento

 93%|█████████▎| 26/28 [00:01<00:00, 17.62it/s]

   n_datos  campo
0      300  Close

   n_datos        campo
0      300  rendimiento

100%|██████████| 28/28 [00:02<00:00, 13.69it/s]

GUARDAR





WMT Walmart
Rescate en ../Cofre/Valor/ WMT
../Cofre/Valor/WMT
<_io.BufferedReader name='../Cofre/Valor/WMT.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/28 [00:00<?, ?it/s]

   n_datos  campo
0        3  Close

  4%|▎         | 1/28 [00:00<00:08,  3.21it/s]

   n_datos        campo
0        3  rendimiento

  7%|▋         | 2/28 [00:00<00:07,  3.42it/s]

   n_datos  campo
0        4  Close

 11%|█         | 3/28 [00:00<00:07,  3.38it/s]

   n_datos        campo
0        4  rendimiento

 14%|█▍        | 4/28 [00:01<00:07,  3.39it/s]

   n_datos  campo
0        5  Close

 18%|█▊        | 5/28 [00:01<00:06,  3.44it/s]

   n_datos        campo
0        5  rendimiento

 21%|██▏       | 6/28 [00:01<00:06,  3.37it/s]

   n_datos  campo
0       10  Close

 25%|██▌       | 7/28 [00:02<00:06,  3.46it/s]

   n_datos        campo
0       10  rendimiento

 29%|██▊       | 8/28 [00:02<00:05,  3.37it/s]

   n_datos  campo
0       20  Close

 32%|███▏      | 9/28 [00:02<00:05,  3.25it/s]

   n_datos        campo
0       20  rendimiento

 36%|███▌      | 10/28 [00:02<00:05,  3.30it/s]

   n_datos  campo
0       30  Close

 39%|███▉      | 11/28 [00:03<00:05,  3.19it/s]

   n_datos        campo
0       30  rendimiento

 43%|████▎     | 12/28 [00:03<00:04,  3.29it/s]

   n_datos  campo
0       50  Close

 46%|████▋     | 13/28 [00:03<00:04,  3.30it/s]

   n_datos        campo
0       50  rendimiento

 50%|█████     | 14/28 [00:04<00:04,  3.45it/s]

   n_datos  campo
0       80  Close

 54%|█████▎    | 15/28 [00:04<00:03,  3.62it/s]

   n_datos        campo
0       80  rendimiento

 57%|█████▋    | 16/28 [00:04<00:03,  3.63it/s]

   n_datos  campo
0      100  Close

 61%|██████    | 17/28 [00:04<00:03,  3.50it/s]

   n_datos        campo
0      100  rendimiento

 64%|██████▍   | 18/28 [00:05<00:02,  3.47it/s]

   n_datos  campo
0      120  Close

 68%|██████▊   | 19/28 [00:05<00:02,  3.55it/s]

   n_datos        campo
0      120  rendimiento

 71%|███████▏  | 20/28 [00:05<00:02,  3.54it/s]

   n_datos  campo
0      150  Close

 75%|███████▌  | 21/28 [00:06<00:02,  3.39it/s]

   n_datos        campo
0      150  rendimiento

 79%|███████▊  | 22/28 [00:06<00:01,  3.41it/s]

   n_datos  campo
0      200  Close

 82%|████████▏ | 23/28 [00:06<00:01,  3.44it/s]

   n_datos        campo
0      200  rendimiento

 86%|████████▌ | 24/28 [00:07<00:01,  3.46it/s]

   n_datos  campo
0      250  Close

 89%|████████▉ | 25/28 [00:07<00:00,  3.49it/s]

   n_datos        campo
0      250  rendimiento

 93%|█████████▎| 26/28 [00:07<00:00,  3.56it/s]

   n_datos  campo
0      300  Close

 96%|█████████▋| 27/28 [00:07<00:00,  3.63it/s]

   n_datos        campo
0      300  rendimiento

100%|██████████| 28/28 [00:11<00:00,  2.43it/s]

GUARDAR





TSLA Tesla
Rescate en ../Cofre/Valor/ TSLA
../Cofre/Valor/TSLA
<_io.BufferedReader name='../Cofre/Valor/TSLA.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/28 [00:00<?, ?it/s]

   n_datos  campo
0        3  Close

  4%|▎         | 1/28 [00:00<00:02,  9.84it/s]

   n_datos        campo
0        3  rendimiento

  7%|▋         | 2/28 [00:00<00:02,  8.73it/s]

   n_datos  campo
0        4  Close

 11%|█         | 3/28 [00:00<00:03,  8.33it/s]

   n_datos        campo
0        4  rendimiento

   n_datos  campo
0        5  Close

 18%|█▊        | 5/28 [00:00<00:02,  9.75it/s]

   n_datos        campo
0        5  rendimiento

   n_datos  campo
0       10  Close

 25%|██▌       | 7/28 [00:00<00:02, 10.47it/s]

   n_datos        campo
0       10  rendimiento

   n_datos  campo
0       20  Close

 32%|███▏      | 9/28 [00:00<00:01, 10.59it/s]

   n_datos        campo
0       20  rendimiento

   n_datos  campo
0       30  Close

 39%|███▉      | 11/28 [00:01<00:01, 10.81it/s]

   n_datos        campo
0       30  rendimiento

   n_datos  campo
0       50  Close

 46%|████▋     | 13/28 [00:01<00:01, 10.86it/s]

   n_datos        campo
0       50  rendimiento

   n_datos  campo
0       80  Close

 54%|█████▎    | 15/28 [00:01<00:01, 10.80it/s]

   n_datos        campo
0       80  rendimiento

   n_datos  campo
0      100  Close

 61%|██████    | 17/28 [00:01<00:01, 10.68it/s]

   n_datos        campo
0      100  rendimiento

   n_datos  campo
0      120  Close

 68%|██████▊   | 19/28 [00:01<00:00, 10.61it/s]

   n_datos        campo
0      120  rendimiento

   n_datos  campo
0      150  Close

 75%|███████▌  | 21/28 [00:02<00:00,  9.97it/s]

   n_datos        campo
0      150  rendimiento

   n_datos  campo
0      200  Close

 82%|████████▏ | 23/28 [00:02<00:00, 10.04it/s]

   n_datos        campo
0      200  rendimiento

   n_datos  campo
0      250  Close

 89%|████████▉ | 25/28 [00:02<00:00, 10.07it/s]

   n_datos        campo
0      250  rendimiento

   n_datos  campo
0      300  Close

 96%|█████████▋| 27/28 [00:02<00:00, 10.12it/s]

   n_datos        campo
0      300  rendimiento

100%|██████████| 28/28 [00:03<00:00,  7.52it/s]

GUARDAR





AMZN Amazon
Rescate en ../Cofre/Valor/ AMZN
../Cofre/Valor/AMZN
<_io.BufferedReader name='../Cofre/Valor/AMZN.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/28 [00:00<?, ?it/s]

   n_datos  campo
0        3  Close

  4%|▎         | 1/28 [00:00<00:04,  5.97it/s]

   n_datos        campo
0        3  rendimiento

  7%|▋         | 2/28 [00:00<00:04,  5.95it/s]

   n_datos  campo
0        4  Close

 11%|█         | 3/28 [00:00<00:04,  5.01it/s]

   n_datos        campo
0        4  rendimiento

 14%|█▍        | 4/28 [00:00<00:04,  5.50it/s]

   n_datos  campo
0        5  Close

 18%|█▊        | 5/28 [00:00<00:03,  5.77it/s]

   n_datos        campo
0        5  rendimiento

 21%|██▏       | 6/28 [00:01<00:03,  5.95it/s]

   n_datos  campo
0       10  Close

 25%|██▌       | 7/28 [00:01<00:03,  5.99it/s]

   n_datos        campo
0       10  rendimiento

 29%|██▊       | 8/28 [00:01<00:03,  6.06it/s]

   n_datos  campo
0       20  Close

 32%|███▏      | 9/28 [00:01<00:03,  6.26it/s]

   n_datos        campo
0       20  rendimiento

 36%|███▌      | 10/28 [00:01<00:02,  6.20it/s]

   n_datos  campo
0       30  Close

 39%|███▉      | 11/28 [00:01<00:02,  6.27it/s]

   n_datos        campo
0       30  rendimiento

 43%|████▎     | 12/28 [00:02<00:02,  6.16it/s]

   n_datos  campo
0       50  Close

 46%|████▋     | 13/28 [00:02<00:02,  6.12it/s]

   n_datos        campo
0       50  rendimiento

 50%|█████     | 14/28 [00:02<00:02,  6.25it/s]

   n_datos  campo
0       80  Close

 54%|█████▎    | 15/28 [00:02<00:02,  6.25it/s]

   n_datos        campo
0       80  rendimiento

 57%|█████▋    | 16/28 [00:02<00:02,  5.90it/s]

   n_datos  campo
0      100  Close

 61%|██████    | 17/28 [00:02<00:01,  6.04it/s]

   n_datos        campo
0      100  rendimiento

 64%|██████▍   | 18/28 [00:03<00:01,  6.03it/s]

   n_datos  campo
0      120  Close

 68%|██████▊   | 19/28 [00:03<00:01,  6.09it/s]

   n_datos        campo
0      120  rendimiento

 71%|███████▏  | 20/28 [00:03<00:01,  6.19it/s]

   n_datos  campo
0      150  Close

 75%|███████▌  | 21/28 [00:03<00:01,  6.26it/s]

   n_datos        campo
0      150  rendimiento

 79%|███████▊  | 22/28 [00:03<00:00,  6.38it/s]

   n_datos  campo
0      200  Close

 82%|████████▏ | 23/28 [00:03<00:00,  6.44it/s]

   n_datos        campo
0      200  rendimiento

 86%|████████▌ | 24/28 [00:03<00:00,  6.33it/s]

   n_datos  campo
0      250  Close

 89%|████████▉ | 25/28 [00:04<00:00,  6.07it/s]

   n_datos        campo
0      250  rendimiento

 93%|█████████▎| 26/28 [00:04<00:00,  5.84it/s]

   n_datos  campo
0      300  Close

 96%|█████████▋| 27/28 [00:04<00:00,  5.58it/s]

   n_datos        campo
0      300  rendimiento

100%|██████████| 28/28 [00:06<00:00,  4.22it/s]

GUARDAR





BRK-A Berkshire Hathaway
Rescate en ../Cofre/Valor/ BRK-A
../Cofre/Valor/BRK-A
<_io.BufferedReader name='../Cofre/Valor/BRK-A.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/28 [00:00<?, ?it/s]

   n_datos  campo
0        3  Close

  4%|▎         | 1/28 [00:00<00:07,  3.76it/s]

   n_datos        campo
0        3  rendimiento

  7%|▋         | 2/28 [00:00<00:06,  4.07it/s]

   n_datos  campo
0        4  Close

 11%|█         | 3/28 [00:00<00:05,  4.28it/s]

   n_datos        campo
0        4  rendimiento

 14%|█▍        | 4/28 [00:00<00:05,  4.39it/s]

   n_datos  campo
0        5  Close

 18%|█▊        | 5/28 [00:01<00:05,  4.38it/s]

   n_datos        campo
0        5  rendimiento

 21%|██▏       | 6/28 [00:01<00:04,  4.43it/s]

   n_datos  campo
0       10  Close

 25%|██▌       | 7/28 [00:01<00:04,  4.30it/s]

   n_datos        campo
0       10  rendimiento

 29%|██▊       | 8/28 [00:01<00:04,  4.25it/s]

   n_datos  campo
0       20  Close

 32%|███▏      | 9/28 [00:02<00:04,  4.32it/s]

   n_datos        campo
0       20  rendimiento

 36%|███▌      | 10/28 [00:02<00:04,  4.38it/s]

   n_datos  campo
0       30  Close

 39%|███▉      | 11/28 [00:02<00:04,  4.24it/s]

   n_datos        campo
0       30  rendimiento

 43%|████▎     | 12/28 [00:02<00:03,  4.34it/s]

   n_datos  campo
0       50  Close

 46%|████▋     | 13/28 [00:02<00:03,  4.45it/s]

   n_datos        campo
0       50  rendimiento

 50%|█████     | 14/28 [00:03<00:03,  4.45it/s]

   n_datos  campo
0       80  Close

 54%|█████▎    | 15/28 [00:03<00:02,  4.51it/s]

   n_datos        campo
0       80  rendimiento

 57%|█████▋    | 16/28 [00:03<00:02,  4.41it/s]

   n_datos  campo
0      100  Close

 61%|██████    | 17/28 [00:03<00:02,  4.43it/s]

   n_datos        campo
0      100  rendimiento

 64%|██████▍   | 18/28 [00:04<00:02,  4.54it/s]

   n_datos  campo
0      120  Close

 68%|██████▊   | 19/28 [00:04<00:01,  4.52it/s]

   n_datos        campo
0      120  rendimiento

 71%|███████▏  | 20/28 [00:04<00:01,  4.43it/s]

   n_datos  campo
0      150  Close

 75%|███████▌  | 21/28 [00:04<00:01,  4.36it/s]

   n_datos        campo
0      150  rendimiento

 79%|███████▊  | 22/28 [00:05<00:01,  4.36it/s]

   n_datos  campo
0      200  Close

 82%|████████▏ | 23/28 [00:05<00:01,  4.23it/s]

   n_datos        campo
0      200  rendimiento

 86%|████████▌ | 24/28 [00:05<00:00,  4.24it/s]

   n_datos  campo
0      250  Close

 89%|████████▉ | 25/28 [00:05<00:00,  4.02it/s]

   n_datos        campo
0      250  rendimiento

 93%|█████████▎| 26/28 [00:06<00:00,  4.08it/s]

   n_datos  campo
0      300  Close

 96%|█████████▋| 27/28 [00:06<00:00,  4.15it/s]

   n_datos        campo
0      300  rendimiento

100%|██████████| 28/28 [00:09<00:00,  2.91it/s]

GUARDAR

## Suavizamiento Exponencial

In [39]:
from Clase_Valor_240902 import generate_suavexp

name = 'Suavizamiento_Exponencial'

#iteradores para este POF
lista_alpha = [0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7] # Para suavizamiento exponencial
campos_suavexp = ['Close', 'rendimiento']

continuar_si_hay_menos = True

configuraciones = {'diccionario_combinaciones': {'alpha': lista_alpha, 'campo': campos_suavexp}, 'iteradores': ['alpha', 'campo'], 'incluir_dates_en_iterar': False, 'df_explicito': pd.DataFrame(), 'continuar_si_hay_menos': continuar_si_hay_menos}

modulo = generate_suavexp

for i in range(len(df_activos)):
    simbolo, nombre = df_activos.loc[i]
    print(simbolo, nombre)
    valor = Valor(simbolo, nombre, cofre, saving_step, output = output) # Si no existe el objeto, se crea
    
    #display(valor.adj_data)
    valor.crear_POF(name, configuraciones, modulo)

BTC-USD Bitcoin
Rescate en ../Cofre/Valor/ BTC-USD
../Cofre/Valor/BTC-USD
<_io.BufferedReader name='../Cofre/Valor/BTC-USD.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/16 [00:00<?, ?it/s]

   alpha  campo
0   0.05  Close

   alpha        campo
0   0.05  rendimiento

 12%|█▎        | 2/16 [00:00<00:01, 11.52it/s]

   alpha  campo
0    0.1  Close

   alpha        campo
0    0.1  rendimiento

 25%|██▌       | 4/16 [00:00<00:00, 12.04it/s]

   alpha  campo
0    0.2  Close

   alpha        campo
0    0.2  rendimiento

 38%|███▊      | 6/16 [00:00<00:00, 11.85it/s]

   alpha  campo
0    0.3  Close

   alpha        campo
0    0.3  rendimiento

 50%|█████     | 8/16 [00:00<00:00, 11.73it/s]

   alpha  campo
0    0.4  Close

   alpha        campo
0    0.4  rendimiento

 62%|██████▎   | 10/16 [00:00<00:00, 11.70it/s]

   alpha  campo
0    0.5  Close

   alpha        campo
0    0.5  rendimiento

 75%|███████▌  | 12/16 [00:01<00:00, 10.74it/s]

   alpha  campo
0    0.6  Close

   alpha        campo
0    0.6  rendimiento

 88%|████████▊ | 14/16 [00:01<00:00, 10.70it/s]

   alpha  campo
0    0.7  Close

   alpha        campo
0    0.7  rendimiento

100%|██████████| 16/16 [00:02<00:00,  6.27it/s]

GUARDAR





NFLX Netflix, Inc.
Rescate en ../Cofre/Valor/ NFLX
../Cofre/Valor/NFLX
<_io.BufferedReader name='../Cofre/Valor/NFLX.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/16 [00:00<?, ?it/s]

   alpha  campo
0   0.05  Close

  6%|▋         | 1/16 [00:00<00:01,  8.94it/s]

   alpha        campo
0   0.05  rendimiento

 12%|█▎        | 2/16 [00:00<00:01,  8.62it/s]

   alpha  campo
0    0.1  Close

 19%|█▉        | 3/16 [00:00<00:01,  8.84it/s]

   alpha        campo
0    0.1  rendimiento

 25%|██▌       | 4/16 [00:00<00:01,  8.78it/s]

   alpha  campo
0    0.2  Close

 31%|███▏      | 5/16 [00:00<00:01,  8.81it/s]

   alpha        campo
0    0.2  rendimiento

 38%|███▊      | 6/16 [00:00<00:01,  8.72it/s]

   alpha  campo
0    0.3  Close

 44%|████▍     | 7/16 [00:00<00:01,  8.50it/s]

   alpha        campo
0    0.3  rendimiento

 50%|█████     | 8/16 [00:00<00:00,  8.40it/s]

   alpha  campo
0    0.4  Close

 56%|█████▋    | 9/16 [00:01<00:00,  8.24it/s]

   alpha        campo
0    0.4  rendimiento

 62%|██████▎   | 10/16 [00:01<00:00,  8.23it/s]

   alpha  campo
0    0.5  Close

 69%|██████▉   | 11/16 [00:01<00:00,  7.91it/s]

   alpha        campo
0    0.5  rendimiento

 75%|███████▌  | 12/16 [00:01<00:00,  8.07it/s]

   alpha  campo
0    0.6  Close

 81%|████████▏ | 13/16 [00:01<00:00,  7.71it/s]

   alpha        campo
0    0.6  rendimiento

 88%|████████▊ | 14/16 [00:01<00:00,  7.86it/s]

   alpha  campo
0    0.7  Close

 94%|█████████▍| 15/16 [00:01<00:00,  7.75it/s]

   alpha        campo
0    0.7  rendimiento

100%|██████████| 16/16 [00:03<00:00,  4.38it/s]

GUARDAR





FCEL FuelCell Energy, Inc.
Rescate en ../Cofre/Valor/ FCEL
../Cofre/Valor/FCEL
<_io.BufferedReader name='../Cofre/Valor/FCEL.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/16 [00:00<?, ?it/s]

   alpha  campo
0   0.05  Close

  6%|▋         | 1/16 [00:00<00:03,  4.27it/s]

   alpha        campo
0   0.05  rendimiento

 12%|█▎        | 2/16 [00:00<00:02,  4.80it/s]

   alpha  campo
0    0.1  Close

 19%|█▉        | 3/16 [00:00<00:02,  5.06it/s]

   alpha        campo
0    0.1  rendimiento

 25%|██▌       | 4/16 [00:00<00:02,  4.92it/s]

   alpha  campo
0    0.2  Close

 31%|███▏      | 5/16 [00:01<00:02,  4.94it/s]

   alpha        campo
0    0.2  rendimiento

 38%|███▊      | 6/16 [00:01<00:01,  5.10it/s]

   alpha  campo
0    0.3  Close

 44%|████▍     | 7/16 [00:01<00:01,  5.04it/s]

   alpha        campo
0    0.3  rendimiento

 50%|█████     | 8/16 [00:01<00:01,  5.05it/s]

   alpha  campo
0    0.4  Close

 56%|█████▋    | 9/16 [00:01<00:01,  5.01it/s]

   alpha        campo
0    0.4  rendimiento

 62%|██████▎   | 10/16 [00:02<00:01,  4.45it/s]

   alpha  campo
0    0.5  Close

 69%|██████▉   | 11/16 [00:02<00:01,  4.30it/s]

   alpha        campo
0    0.5  rendimiento

 75%|███████▌  | 12/16 [00:02<00:00,  4.33it/s]

   alpha  campo
0    0.6  Close

 81%|████████▏ | 13/16 [00:02<00:00,  4.31it/s]

   alpha        campo
0    0.6  rendimiento

 88%|████████▊ | 14/16 [00:03<00:00,  4.36it/s]

   alpha  campo
0    0.7  Close

 94%|█████████▍| 15/16 [00:03<00:00,  4.25it/s]

   alpha        campo
0    0.7  rendimiento

100%|██████████| 16/16 [00:06<00:00,  2.42it/s]

GUARDAR





DVA DaVita Inc.
Rescate en ../Cofre/Valor/ DVA
../Cofre/Valor/DVA
<_io.BufferedReader name='../Cofre/Valor/DVA.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/16 [00:00<?, ?it/s]

   alpha  campo
0   0.05  Close

  6%|▋         | 1/16 [00:00<00:03,  4.89it/s]

   alpha        campo
0   0.05  rendimiento

 12%|█▎        | 2/16 [00:00<00:02,  5.13it/s]

   alpha  campo
0    0.1  Close

 19%|█▉        | 3/16 [00:00<00:02,  5.09it/s]

   alpha        campo
0    0.1  rendimiento

 25%|██▌       | 4/16 [00:00<00:02,  5.27it/s]

   alpha  campo
0    0.2  Close

 31%|███▏      | 5/16 [00:00<00:02,  5.15it/s]

   alpha        campo
0    0.2  rendimiento

 38%|███▊      | 6/16 [00:01<00:01,  5.15it/s]

   alpha  campo
0    0.3  Close

 44%|████▍     | 7/16 [00:01<00:01,  5.15it/s]

   alpha        campo
0    0.3  rendimiento

 50%|█████     | 8/16 [00:01<00:01,  5.23it/s]

   alpha  campo
0    0.4  Close

 56%|█████▋    | 9/16 [00:01<00:01,  5.20it/s]

   alpha        campo
0    0.4  rendimiento

 62%|██████▎   | 10/16 [00:02<00:01,  4.34it/s]

   alpha  campo
0    0.5  Close

 69%|██████▉   | 11/16 [00:02<00:01,  4.14it/s]

   alpha        campo
0    0.5  rendimiento

 75%|███████▌  | 12/16 [00:02<00:01,  4.00it/s]

   alpha  campo
0    0.6  Close

 81%|████████▏ | 13/16 [00:02<00:00,  3.92it/s]

   alpha        campo
0    0.6  rendimiento

 88%|████████▊ | 14/16 [00:03<00:00,  4.23it/s]

   alpha  campo
0    0.7  Close

 94%|█████████▍| 15/16 [00:03<00:00,  4.37it/s]

   alpha        campo
0    0.7  rendimiento

100%|██████████| 16/16 [00:05<00:00,  2.78it/s]

GUARDAR





AAPL AAPL
Rescate en ../Cofre/Valor/ AAPL
../Cofre/Valor/AAPL
<_io.BufferedReader name='../Cofre/Valor/AAPL.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/16 [00:00<?, ?it/s]

   alpha  campo
0   0.05  Close

  6%|▋         | 1/16 [00:00<00:05,  2.79it/s]

   alpha        campo
0   0.05  rendimiento

 12%|█▎        | 2/16 [00:00<00:04,  3.18it/s]

   alpha  campo
0    0.1  Close

 19%|█▉        | 3/16 [00:00<00:03,  3.32it/s]

   alpha        campo
0    0.1  rendimiento

 25%|██▌       | 4/16 [00:01<00:03,  3.44it/s]

   alpha  campo
0    0.2  Close

 31%|███▏      | 5/16 [00:01<00:03,  3.44it/s]

   alpha        campo
0    0.2  rendimiento

 38%|███▊      | 6/16 [00:01<00:02,  3.56it/s]

   alpha  campo
0    0.3  Close

 44%|████▍     | 7/16 [00:02<00:02,  3.44it/s]

   alpha        campo
0    0.3  rendimiento

 50%|█████     | 8/16 [00:02<00:02,  3.54it/s]

   alpha  campo
0    0.4  Close

 56%|█████▋    | 9/16 [00:02<00:01,  3.59it/s]

   alpha        campo
0    0.4  rendimiento

 62%|██████▎   | 10/16 [00:02<00:01,  3.37it/s]

   alpha  campo
0    0.5  Close

 69%|██████▉   | 11/16 [00:03<00:01,  3.40it/s]

   alpha        campo
0    0.5  rendimiento

 75%|███████▌  | 12/16 [00:03<00:01,  3.32it/s]

   alpha  campo
0    0.6  Close

 81%|████████▏ | 13/16 [00:03<00:00,  3.36it/s]

   alpha        campo
0    0.6  rendimiento

 88%|████████▊ | 14/16 [00:04<00:00,  3.53it/s]

   alpha  campo
0    0.7  Close

 94%|█████████▍| 15/16 [00:04<00:00,  3.54it/s]

   alpha        campo
0    0.7  rendimiento

100%|██████████| 16/16 [00:07<00:00,  2.04it/s]

GUARDAR





DOW DOW
Rescate en ../Cofre/Valor/ DOW
../Cofre/Valor/DOW
<_io.BufferedReader name='../Cofre/Valor/DOW.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl
generar_df_combinaciones pre merge

  0%|          | 0/16 [00:00<?, ?it/s]

   alpha  campo
0   0.05  Close

   alpha        campo
0   0.05  rendimiento

 12%|█▎        | 2/16 [00:00<00:00, 16.58it/s]

   alpha  campo
0    0.1  Close

   alpha        campo
0    0.1  rendimiento

 25%|██▌       | 4/16 [00:00<00:00, 13.55it/s]

   alpha  campo
0    0.2  Close

   alpha        campo
0    0.2  rendimiento

 38%|███▊      | 6/16 [00:00<00:00, 13.81it/s]

   alpha  campo
0    0.3  Close

   alpha        campo
0    0.3  rendimiento

 50%|█████     | 8/16 [00:00<00:00, 15.41it/s]

   alpha  campo
0    0.4  Close

   alpha        campo
0    0.4  rendimiento

 62%|██████▎   | 10/16 [00:00<00:00, 15.38it/s]

   alpha  campo
0    0.5  Close

   alpha        campo
0    0.5  rendimiento

 75%|███████▌  | 12/16 [00:00<00:00, 15.44it/s]

   alpha  campo
0    0.6  Close

   alpha        campo
0    0.6  rendimiento

 88%|████████▊ | 14/16 [00:00<00:00, 15.10it/s]

   alpha  campo
0    0.7  Close

   alpha        campo
0    0.7  rendimiento

100%|██████████| 16/16 [00:01<00:00,  9.85it/s]

GUARDAR





WMT Walmart
Rescate en ../Cofre/Valor/ WMT
../Cofre/Valor/WMT
<_io.BufferedReader name='../Cofre/Valor/WMT.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/16 [00:00<?, ?it/s]

   alpha  campo
0   0.05  Close

  6%|▋         | 1/16 [00:00<00:07,  1.99it/s]

   alpha        campo
0   0.05  rendimiento

 12%|█▎        | 2/16 [00:00<00:06,  2.17it/s]

   alpha  campo
0    0.1  Close

 19%|█▉        | 3/16 [00:01<00:05,  2.37it/s]

   alpha        campo
0    0.1  rendimiento

 25%|██▌       | 4/16 [00:01<00:04,  2.48it/s]

   alpha  campo
0    0.2  Close

 31%|███▏      | 5/16 [00:02<00:04,  2.62it/s]

   alpha        campo
0    0.2  rendimiento

 38%|███▊      | 6/16 [00:02<00:03,  2.66it/s]

   alpha  campo
0    0.3  Close

 44%|████▍     | 7/16 [00:02<00:03,  2.74it/s]

   alpha        campo
0    0.3  rendimiento

 50%|█████     | 8/16 [00:03<00:02,  2.88it/s]

   alpha  campo
0    0.4  Close

 56%|█████▋    | 9/16 [00:03<00:02,  3.02it/s]

   alpha        campo
0    0.4  rendimiento

 62%|██████▎   | 10/16 [00:03<00:02,  2.99it/s]

   alpha  campo
0    0.5  Close

 69%|██████▉   | 11/16 [00:04<00:01,  2.84it/s]

   alpha        campo
0    0.5  rendimiento

 75%|███████▌  | 12/16 [00:04<00:01,  2.52it/s]

   alpha  campo
0    0.6  Close

 81%|████████▏ | 13/16 [00:04<00:01,  2.52it/s]

   alpha        campo
0    0.6  rendimiento

 88%|████████▊ | 14/16 [00:05<00:00,  2.51it/s]

   alpha  campo
0    0.7  Close

 94%|█████████▍| 15/16 [00:05<00:00,  2.64it/s]

   alpha        campo
0    0.7  rendimiento

100%|██████████| 16/16 [00:09<00:00,  1.61it/s]

GUARDAR





TSLA Tesla
Rescate en ../Cofre/Valor/ TSLA
../Cofre/Valor/TSLA
<_io.BufferedReader name='../Cofre/Valor/TSLA.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/16 [00:00<?, ?it/s]

   alpha  campo
0   0.05  Close

  6%|▋         | 1/16 [00:00<00:01,  8.96it/s]

   alpha        campo
0   0.05  rendimiento

 12%|█▎        | 2/16 [00:00<00:01,  8.91it/s]

   alpha  campo
0    0.1  Close

 19%|█▉        | 3/16 [00:00<00:01,  9.31it/s]

   alpha        campo
0    0.1  rendimiento

   alpha  campo
0    0.2  Close

 31%|███▏      | 5/16 [00:00<00:01,  9.73it/s]

   alpha        campo
0    0.2  rendimiento

 38%|███▊      | 6/16 [00:00<00:01,  8.89it/s]

   alpha  campo
0    0.3  Close

 44%|████▍     | 7/16 [00:00<00:01,  8.68it/s]

   alpha        campo
0    0.3  rendimiento

 50%|█████     | 8/16 [00:00<00:00,  8.57it/s]

   alpha  campo
0    0.4  Close

 56%|█████▋    | 9/16 [00:01<00:00,  8.59it/s]

   alpha        campo
0    0.4  rendimiento

 62%|██████▎   | 10/16 [00:01<00:00,  8.90it/s]

   alpha  campo
0    0.5  Close

 69%|██████▉   | 11/16 [00:01<00:00,  8.99it/s]

   alpha        campo
0    0.5  rendimiento

   alpha  campo
0    0.6  Close

 81%|████████▏ | 13/16 [00:01<00:00,  9.18it/s]

   alpha        campo
0    0.6  rendimiento

 88%|████████▊ | 14/16 [00:01<00:00,  8.91it/s]

   alpha  campo
0    0.7  Close

 94%|█████████▍| 15/16 [00:01<00:00,  9.05it/s]

   alpha        campo
0    0.7  rendimiento

100%|██████████| 16/16 [00:02<00:00,  5.49it/s]

GUARDAR





AMZN Amazon
Rescate en ../Cofre/Valor/ AMZN
../Cofre/Valor/AMZN
<_io.BufferedReader name='../Cofre/Valor/AMZN.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/16 [00:00<?, ?it/s]

   alpha  campo
0   0.05  Close

  6%|▋         | 1/16 [00:00<00:02,  5.06it/s]

   alpha        campo
0   0.05  rendimiento

 12%|█▎        | 2/16 [00:00<00:02,  5.01it/s]

   alpha  campo
0    0.1  Close

 19%|█▉        | 3/16 [00:00<00:02,  4.61it/s]

   alpha        campo
0    0.1  rendimiento

 25%|██▌       | 4/16 [00:00<00:02,  4.63it/s]

   alpha  campo
0    0.2  Close

 31%|███▏      | 5/16 [00:01<00:02,  4.83it/s]

   alpha        campo
0    0.2  rendimiento

 38%|███▊      | 6/16 [00:01<00:02,  4.93it/s]

   alpha  campo
0    0.3  Close

 44%|████▍     | 7/16 [00:01<00:01,  4.59it/s]

   alpha        campo
0    0.3  rendimiento

 50%|█████     | 8/16 [00:01<00:01,  4.67it/s]

   alpha  campo
0    0.4  Close

 56%|█████▋    | 9/16 [00:01<00:01,  4.92it/s]

   alpha        campo
0    0.4  rendimiento

 62%|██████▎   | 10/16 [00:02<00:01,  5.07it/s]

   alpha  campo
0    0.5  Close

 69%|██████▉   | 11/16 [00:02<00:00,  5.16it/s]

   alpha        campo
0    0.5  rendimiento

 75%|███████▌  | 12/16 [00:02<00:00,  5.22it/s]

   alpha  campo
0    0.6  Close

 81%|████████▏ | 13/16 [00:02<00:00,  5.04it/s]

   alpha        campo
0    0.6  rendimiento

 88%|████████▊ | 14/16 [00:02<00:00,  5.28it/s]

   alpha  campo
0    0.7  Close

 94%|█████████▍| 15/16 [00:02<00:00,  5.39it/s]

   alpha        campo
0    0.7  rendimiento

100%|██████████| 16/16 [00:05<00:00,  3.00it/s]

GUARDAR





BRK-A Berkshire Hathaway
Rescate en ../Cofre/Valor/ BRK-A
../Cofre/Valor/BRK-A
<_io.BufferedReader name='../Cofre/Valor/BRK-A.pkl'>
COMENTAR FUNCION!!!!
generar_df_combinaciones NO expl

generar_df_combinaciones pre merge

  0%|          | 0/16 [00:00<?, ?it/s]

   alpha  campo
0   0.05  Close

  6%|▋         | 1/16 [00:00<00:04,  3.05it/s]

   alpha        campo
0   0.05  rendimiento

 12%|█▎        | 2/16 [00:00<00:04,  3.23it/s]

   alpha  campo
0    0.1  Close

 19%|█▉        | 3/16 [00:00<00:03,  3.41it/s]

   alpha        campo
0    0.1  rendimiento

 25%|██▌       | 4/16 [00:01<00:03,  3.41it/s]

   alpha  campo
0    0.2  Close

 31%|███▏      | 5/16 [00:01<00:03,  3.52it/s]

   alpha        campo
0    0.2  rendimiento

 38%|███▊      | 6/16 [00:01<00:02,  3.47it/s]

   alpha  campo
0    0.3  Close

 44%|████▍     | 7/16 [00:02<00:02,  3.44it/s]

   alpha        campo
0    0.3  rendimiento

 50%|█████     | 8/16 [00:02<00:02,  3.54it/s]

   alpha  campo
0    0.4  Close

 56%|█████▋    | 9/16 [00:02<00:01,  3.71it/s]

   alpha        campo
0    0.4  rendimiento

 62%|██████▎   | 10/16 [00:02<00:01,  3.88it/s]

   alpha  campo
0    0.5  Close

 69%|██████▉   | 11/16 [00:03<00:01,  3.69it/s]

   alpha        campo
0    0.5  rendimiento

 75%|███████▌  | 12/16 [00:03<00:01,  3.63it/s]

   alpha  campo
0    0.6  Close

 81%|████████▏ | 13/16 [00:03<00:00,  3.68it/s]

   alpha        campo
0    0.6  rendimiento

 88%|████████▊ | 14/16 [00:03<00:00,  3.70it/s]

   alpha  campo
0    0.7  Close

 94%|█████████▍| 15/16 [00:04<00:00,  3.44it/s]

   alpha        campo
0    0.7  rendimiento

100%|██████████| 16/16 [00:07<00:00,  2.09it/s]

GUARDAR

## Áreas (ver módulo areas)

In [40]:
sys.exit('Antes de seguir (con módulo Áreas), limpiar código FFNN_y_BusqInt_240610')

SystemExit: Antes de seguir (con módulo Áreas), limpiar código FFNN_y_BusqInt_240610

# Otros

In [ ]:
sys.exit('OK')

In [ ]:
# ANTIGUO
for i in range(len(df_activos)):
    simbolo, nombre = df_activos.loc[i]
    print(simbolo, nombre)
    
    valor = Valor(simbolo, nombre, cofre, output = True) # Si no existe el objeto, se crea
    
    valor.extraer_data()
    valor.ajustar_data()

    display(valor.adj_data.tail())

    #print('A')
    #valor.generar_figuras_all(lista_k, lista_figuras, saving_step = saving_step)
    print('B')
    valor.generar_fibonacci_all(lista_k, saving_step = saving_step)

    print('C')
    valor.generar_media_movil_all(lista_n, lista_campos, saving_step = saving_step)
    print('D')
    valor.generar_media_movil_multiplicativa_all(lista_n, lista_campos, saving_step = saving_step)
    print('E')
    valor.generar_suavizamiento_exponencial_all(lista_alpha, lista_campos, saving_step = saving_step)
    
    #print('C1: Buscar "Continuar aqui 240506"...clase red neuronal (método construir_matrices)')
    print('C2 Construir casos como: Calidad de una figura (páginas 10 & 11), dada la info obtenida en generar_figuras_all...agregar a raw_x')
    
    #print('F')
    #df_pl = valor.generar_polinomicas_all(lista_grados, lista_R, saving_step = saving_step)

    valor.generar_output_all(lista_R)
    
    valor.guardar()
    #sys.exit('Fin')
    
print('Proceso OK')

In [ ]:
sys.exit()

# Data

In [ ]:
df = valor.adj_data
df.tail()

In [ ]:
from finta import TA
TA?

In [ ]:
TA.BBANDS(df)

# TO DO

In [ ]:
#Convex Hull, algorítmo?. Partir de un punto convexo (P0), elegir el punto que tenga menor angulo entre el vector que comienza en el P0 y apunta hacia arriba y el vector que comienza en el P0 y apunta hacia el punto. Se elige el punto que tenga el menor ángulo. Se repite el proceso hasta que se llegue al punto de inicio. Se obtiene el convex hull. 
# Se puede hacer con scipy.spatial.ConvexHull